def pallet_task2_and_3_T():
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_gravity([0.0, 0.0, 9.82])
  set_target_payload(1.070000, [0.002000, 0.003000, 0.057000], [0.001723, 0.001723, 0.001723, 0.000000, 0.000000, 0.000000])
  set_safety_mode_transition_hardness(1)
  set_tool_communication(True, 1000000, 2, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(24)
  step_count_f4ed1c54_b657_4589_97a9_454c00de09a1 = 0.0
  thread Step_Counter_Thread_54d30273_1a35_4a56_9e60_44cd21649f6f():
    while (True):
      step_count_f4ed1c54_b657_4589_97a9_454c00de09a1 = step_count_f4ed1c54_b657_4589_97a9_454c00de09a1 + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_54d30273_1a35_4a56_9e60_44cd21649f6f()
  global B1empty=1
  global A2Empty=1
  global A1Empty=1
  global B2Empty=0
  global pallet_step=1
  global Pallet_1_cnt=2
  global bright_box=0
  global dark_boxes=0
  global Point_1=p[0.6913645118948067,-0.12399382748223003,0.49223711947071,-1.2983729986843258,1.1259514972191385,-1.2203503861141718]
  global referencePoin_1=p[0.3655924077144329,0.12873232638075274,0.11883144602328854,2.22834219609125,2.2063380160379844,-0.0019074373113331761]
  global referencePoin_2=p[0.3676458444694583,-0.1293909280545595,0.11502587828448332,-2.216630689520228,-2.195354976827886,-0.03292578233415494]
  global referencePoin_3=p[0.2996507856594059,0.23616603967460775,0.2662969273431384,2.247175696332654,-2.1905635169285436,0.0051919237215875364]
  global referencePoin_4=p[0.4738619713248294,0.01094800568094445,0.2696281190313883,2.2471733870198873,-2.1905205802300376,0.005151952022462617]
  global referencePoint=p[0.48764161325454886,0.006206234045797706,0.11644156571844112,2.2282166751700236,2.206466079527706,-0.0021743290203649237]
  global separatorPoin_1=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global separatorPoin_2=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global separatorPoin_3=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global separatorPoin_4=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global separatorPoint=p[0.0,0.0,0.0,0.0,0.0,0.0]
  # begin: URCap Installation Node
  #   Source: External Control, 1.0.5, FZI Research Center for Information Technology
  #   Type: External Control
  # end: URCap Installation Node
  # begin: URCap Installation Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: OnRobot Setup
  sleep(1)
  if (False):
    global rg_Busy = 0
    global rg_Depth = 0
    global rg_DepthRel = 0
    global rg_Grip_detected = 0
    global rg_Width = 0
  end
  ON_CONN_SHIFT_BOOL = 64
  ON_CONN_SHIFT_INT = 24
  ON_CONN_SHIFT_FLOAT = 24
  ON_CONN_REG_SUM_BOOL = 7
  ON_CONN_REG_SUM_INT = 4
  ON_CONN_REG_SUM_FLOAT = 3
  ON_TOOL_SHIFT_BOOL = 64
  ON_TOOL_SHIFT_INT = 25
  ON_TOOL_SHIFT_FLOAT = 24
  ON_TOOL_SHIFT_BOOL_ARR = [64, 71, 71]
  ON_TOOL_SHIFT_INT_ARR = [25, 28, 28]
  ON_TOOL_SHIFT_FLOAT_ARR = [24, 27, 27]
  ON_TOOL_REG_SUM_BOOL = 7
  ON_TOOL_REG_SUM_INT = 3
  ON_TOOL_REG_SUM_FLOAT = 3
  ON_REGISTERS_SPEEDL_FLOAT = 0
  ON_REG_USE_TOOL = False
  ON_DI_SINGLE = 0
  ON_DI_PRIMARY = 1
  ON_DI_SECONDARY = 2
  ON_DI_DUAL = 3
  on_robot_type = 10
  on_robot_cycle = 2.0
  on_conn_ip = "localhost"
  on_tool_ip = "localhost"
  on_device_socket_port = 51234
  on_conn_xmlrpc = rpc_factory("xmlrpc", "http://localhost:41414")
  on_tool_xmlrpc = rpc_factory("xmlrpc", "http://localhost:41414")
  on_RPC = rpc_factory("xmlrpc", "http://127.0.0.1:31416")
  ON_DEBUG_LOG = False
  on_isMetric = True
  on_toolConnector = True
  on_ioqc = False
  on_dual = False
  on_computebox = False
  on_devices = 1
  on_gripper = [False, False, False]
  on_custom_tcp_id = "none"
  on_custom_tcp_enabled = False
  speedlTime = 0.001
  on_ft = False
  rg_index = 0
  on_gripper[rg_index] = True
  #======    OnRobot Globals    ======#
  
  ON_MATH_PI=3.141593
  ON_ZEROPOSE=p[0.0,0.0,0.0,0.0,0.0,0.0]
  ON_ZEROFRAME=p[0.0,0.0,0.0,0.0,0.0,0.0]
  ON_ZERO3D=[0.0,0.0,0.0]
  ON_ZERO6D=[0.0,0.0,0.0,0.0,0.0,0.0]
  ON_ZERO8D=[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
  ON_FALSE3D=[False,False,False]
  ON_FALSE6D=[False,False,False,False,False,False]
  ON_FALSE8D=[False,False,False,False,False,False,False,False]
  global on_return=0
  on_speedL=ON_ZERO6D
  on_speedBase=ON_ZERO6D
  on_speedVect=ON_ZERO6D
  on_speedExtra=ON_ZERO6D
  on_speedCB=ON_ZERO6D
  on_speedGecko=ON_ZERO6D
  on_RTDE_error=0
  on_RTDE_tool_error=0
  on_dataProcess_thrd=0
  ON_DEVICE_ID_MISSING=0
  ON_INIT_WATCHDOG_HZ=5
  ON_INIT_TIMEOUT=2000
  on_robot_TCP_offset=ON_ZEROFRAME
  on_tcp_offset_actual=ON_ZEROFRAME
  on_cog_actual=ON_ZEROFRAME
  on_mass_actual=0.0
  on_robot_mount=[0.0,0.0]
  
  #======    End of OnRobot Globals    ======#
  #======    OnRobot RG Globals    ======#
  
  RG_DEVICE_ID_RG2=32
  RG_DEVICE_ID_RG6=33
  if ON_DEBUG_LOG:
  textmsg("RG Dual: False, Index: ",rg_index)
  if False:
  rg_index=-1
  end 
  end 
  rg_Width_arr=[0,0,0]
  rg_Depth_arr=[0,0,0]
  rg_DepthRel_arr=[0,0,0]
  rg_product_code_arr=[0,0,0]
  rg_device_id_arr=[0,0,0]
  rg_Status_arr=[0,0,0]
  rg_Grip_detected_arr=[False,False,False]
  rg_Busy_arr=[False,False,False]
  rg_S1_pushed_arr=[False,False,False]
  rg_S1_triggered_arr=[False,False,False]
  rg_S2_pushed_arr=[False,False,False]
  rg_S2_triggered_arr=[False,False,False]
  rg_Safety_error_arr=[False,False,False]
  rg_Speed_arr=[0,0,0]
  rg_Angle_arr=[0,0,0]
  rg_Angle_speed_arr=[0,0,0]
  rg_Depth_prev_arr=[0,0,0]
  rg_speedDC=ON_ZERO6D
  rg_data_error_arr=[0,0,0]
  rg_mounting_angle_arr=[0,0,0]
  rg_fingertip_arr=[0,0,0]
  rg_Grip_guard_arr=[False,False,False]
  
  rg_Width=0
  rg_Depth=0
  rg_DepthRel=0
  rg_Busy=False
  rg_Grip_detected=False
  def get_rg_Width():
  return rg_Width
  end 
  def get_rg_Depth():
  return rg_Depth
  end 
  def get_rg_DepthRel():
  return rg_DepthRel
  end 
  def get_rg_Busy():
  return rg_Busy
  end 
  def get_rg_Grip_detected():
  return rg_Grip_detected
  end 
  
  rg2_mount_bracket_offset=35.0/1000.0
  rg2_mount_body_offset=p[0.0,0.0,0.180,0.0,0.0,0.0]
  rg2_mount_cog_offset=p[0.0,0.0,0.065,0.0,0.0,0.0]
  rg6_mount_bracket_offset=35.0/1000.0
  rg6_mount_body_offset=p[0.0,0.0,0.230,0.0,0.0,0.0]
  rg6_mount_cog_offset=p[0.0,0.0,0.080,0.0,0.0,0.0]
  
  #======    End of OnRobot RG Globals    ======#
  #======    OnRobot Interface Messages    ======#
  
  on_devices_primary_log="OnRobot Devices"
  on_devices_secondary_log="OnRobot Secondary Device"
  on_program_halted="<br>Program halted."
  on_device_error_title="OnRobot - Device error"
  on_install_error="OnRobot Setup is not correct.<br>Check the status in the OnRobot Setup page in the Installation Tab.<br>Program halted."
  on_device_missing="No device connected.<br>Program halted."
  cb_device_missing="No OnRobot Compute Box connected.<br>Program halted."
  ft_device_missing="No OnRobot FT sensor or license detected.<br>Program halted."
  hex_device_missing="No HEX sensor connected.<br>Program halted."
  rg2ft_device_missing="No RG2-FT gripper connected.<br>Program halted."
  rg_device_missing="No RG gripper connected.<br>Program halted."
  vg_device_missing="No VG gripper connected.<br>Program halted."
  gg_device_missing="No Gecko Gripper connected.<br>Program halted."
  sg_device_missing="No Soft Gripper connected.<br>Program halted."
  tfg_device_missing="No 3FG gripper connected.<br>Program halted."
  sdr_device_missing="No OnRobot Sander connected.<br>Program halted."
  twofg_device_missing="No 2FG gripper connected.<br>Program halted."
  vgp_device_missing="No VGP gripper connected.<br>Program halted."
  mg_device_missing="No Magnetic Gripper connected.<br>Program halted."
  fgp_device_missing="No 2FGP20 Gripper connected.<br>Program halted."
  eyes_device_missing="No OnRobot Eyes connected.<br>Program halted."
  on_xmlrpc_start_ip="Connecting to OnRobot XML-RPC Server:"
  on_java_comm_error_textmsg_title="OnRobot - Communication error:"
  on_java_comm_controlsocket_open_error="Socket 'javaSocket' opening was unsuccessful."
  on_java_comm_error_title="OnRobot - Communication error"
  on_java_comm_socket_open_error="Establishing connection with the URCap was timed out.<br>Check the status in the OnRobot Setup page in the Installation Tab.<br>Program halted."
  on_rtde_feed_error_textmsg_title="OnRobot - RTDE error:"
  on_rtde_feed_error="RTDE feed error. OnRobot device count mismatch.<br>Program halted."
  on_rtde_feed_tool_error="Tool RTDE feed error. OnRobot device count mismatch.<br>Program halted."
  on_rtde_feed_open_error_textmsg="Socket 'rtdeFeed' opening was unsuccessful."
  on_rtde_feed_error_title="OnRobot - RTDE error"
  on_rtde_feed_count_error="Invalid RTDE offset setup detected. Please check RTDE Offsets at the OnRobot Setup page in the Installation Tab.<br>Program halted."
  on_rtde_feed_open_error="Establishing connection with the devices was timed out.<br>Ensure that the OnRobot devices are operational, and check the status in the OnRobot Setup page in the Installation Tab."
  
  #======    End of OnRobot Interface Messages    ======#
  #======    OnRobot Interface    ======#
  
  on_portopened_javaSocket=False
  on_rtde_feed_opened=False
  on_dataProcess_running=False
  def on_missing():
  popup(on_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def cb_missing():
  popup(cb_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def ft_missing():
  popup(ft_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def hex_missing():
  popup(hex_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def rg2ft_missing():
  popup(rg2ft_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def rg_missing():
  popup(rg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def vg_missing():
  popup(vg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def gg_missing():
  popup(gg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def sg_missing():
  popup(sg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def tfg_missing():
  popup(tfg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def sdr_missing():
  popup(sdr_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def twofg_missing():
  popup(twofg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def vgp_missing():
  popup(vgp_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def mg_missing():
  popup(mg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def fgp_missing():
  popup(fgp_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def eyes_missing():
  popup(eyes_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def on_portclose_javaSocket():
  socket_close("javaSocket")
  on_portopened_javaSocket=False
  end 
  def on_portopen_javaSocket():
  on_portclose_javaSocket()
  on_portopened_javaSocket=socket_open("127.0.0.1",44005,"javaSocket")
  if not on_portopened_javaSocket:
  textmsg(on_java_comm_error_textmsg_title,on_java_comm_controlsocket_open_error)
  popup(on_java_comm_socket_open_error,title=on_java_comm_error_title,error=True,blocking=False)
  halt
  end 
  end 
  on_conn_rtde_feed_name="rtdeFeedConn"
  on_tool_rtde_feed_name="rtdeFeedTool"
  def on_rtde_feed_close(rtdeFeedName):
  socket_close(rtdeFeedName)
  on_rtde_feed_opened=False
  end 
  def on_rtde_feed_open(deviceIP,rtdeFeedName,regStart,regSum,regSpeedl):
  on_rtde_feed_close(rtdeFeedName)
  if((regStart[0]+regSum[0])>128)or((regStart[1]+regSum[1])>48)or((regStart[2]+regSum[2])>48):
  popup(on_rtde_feed_count_error,title=on_rtde_feed_error_title,error=True,blocking=False)
  textmsg(str_cat("RegStart: ",regStart),str_cat("  -  RegSum: ",regSum))
  halt
  end 
  on_rtde_feed_opened=socket_open(deviceIP,on_device_socket_port,rtdeFeedName)
  if not on_rtde_feed_opened:
  on_rtde_feed_opened=socket_open(deviceIP,on_device_socket_port,rtdeFeedName)
  end 
  if not on_rtde_feed_opened:
  textmsg(on_rtde_feed_error_textmsg_title,on_rtde_feed_open_error_textmsg)
  popup(on_rtde_feed_open_error,title=on_rtde_feed_error_title,error=True,blocking=False)
  halt
  end 
  socket_send_int(regStart[0],rtdeFeedName)
  socket_send_int(regSum[0],rtdeFeedName)
  socket_send_int(regStart[1],rtdeFeedName)
  socket_send_int(regSum[1],rtdeFeedName)
  socket_send_int(regStart[2],rtdeFeedName)
  socket_send_int(regSum[2],rtdeFeedName)
  socket_send_int(regSpeedl,rtdeFeedName)
  socket_send_int(on_devices,rtdeFeedName)
  end 
  def on_dataRead():
  enter_critical
  on_RTDE_error=read_input_integer_register(ON_CONN_SHIFT_INT)
  if(ON_REG_USE_TOOL):
  on_RTDE_tool_error=read_input_integer_register(ON_TOOL_SHIFT_INT_ARR[0])
  end
  exit_critical
  end 
  def on_set_rtde_watchdog(updateHz=ON_INIT_WATCHDOG_HZ):
  local effect="stop"
  if(updateHz<1):
  effect="ignore"
  end 
  watchdog_conn_reg_str=str_cat("input_int_register_",ON_CONN_SHIFT_INT)
  rtde_set_watchdog(watchdog_conn_reg_str,updateHz,effect)
  if(ON_REG_USE_TOOL):
  watchdog_tool_reg_str=str_cat("input_int_register_",ON_TOOL_SHIFT_INT_ARR[0])
  rtde_set_watchdog(watchdog_tool_reg_str,updateHz,effect)
  end 
  if ON_DEBUG_LOG:
  local update_str=str_cat(" "+effect+" watchdog set to [Hz]: ",updateHz)
  textmsg(watchdog_conn_reg_str,update_str)
  if(ON_REG_USE_TOOL):
  local update_str=str_cat(" "+effect+" watchdog set to [Hz]: ",updateHz)
  textmsg(watchdog_tool_reg_str,update_str)
  end 
  end 
  end 
  def on_speedCB_get():
  return[on_speedCB[0],on_speedCB[1],on_speedCB[2],on_speedCB[3],on_speedCB[4],on_speedCB[5]]
  end 
  def on_speedGecko_get():
  local speedExtra=ON_ZERO6D
  if on_speedl_for_gecko:
  speedExtra=[on_speedGecko[0],on_speedGecko[1],on_speedGecko[2],on_speedGecko[3],on_speedGecko[4],on_speedGecko[5]]
  end 
  return speedExtra
  end 
  def on_speedGecko_set(speedGecko):
  on_speedGecko=[speedGecko[0],speedGecko[1],speedGecko[2],speedGecko[3],speedGecko[4],speedGecko[5]]
  end 
  thread on_dataProcess_thread():
  if ON_DEBUG_LOG:
  textmsg("Starting on_dataRead thread")
  end 
  local error=False
  on_dataProcess_running=True
  sync()
  while on_dataProcess_running:
  sync()
  on_dataRead()
  error=on_error((on_RTDE_error<0),on_rtde_feed_error,on_rtde_feed_error_title,error)
  error=on_error((ON_REG_USE_TOOL and(on_RTDE_tool_error<0)),on_rtde_feed_tool_error,on_rtde_feed_error_title,error)
  on_dataProcess_running=not error
  end 
  if error:
  halt
  end 
  if ON_DEBUG_LOG:
  textmsg("Stopping on_dataRead thread")
  end 
  end 
  thread on_set_watchdog_thread():
  sleep(2)
  on_set_rtde_watchdog(updateHz=ON_INIT_WATCHDOG_HZ)
  sleep(1/ON_INIT_WATCHDOG_HZ)
  on_dataProcess_running=False
  kill on_dataProcess_thrd
  end 
  
  #======    End of OnRobot Interface    ======#
  #======    OnRobot QC Setup Tool Connector    ======#
  
  def tc_setup_tool():
  if ON_DEBUG_LOG:
  textmsg("QC Setup Tool Connector start...")
  end 
  set_tool_voltage(24)
  
  set_tool_communication(True,1000000,2,1,1.5,3.5)
  
  if ON_DEBUG_LOG:
  textmsg("QC Setup Tool Connector end.")
  end 
  end 
  
  #======    End of OnRobot QC Setup Tool Connector    ======#
  #======    OnRobot RG Interface    ======#
  
  rg_dataRead_running=False
  def rg_dataRead_RTDE(tool_index):
  local reg_offset_bool=ON_TOOL_SHIFT_BOOL_ARR[tool_index]
  local reg_offset_int=ON_TOOL_SHIFT_INT_ARR[tool_index]
  local reg_offset_float=ON_TOOL_SHIFT_FLOAT_ARR[tool_index]
  enter_critical
  floatRegDummy=read_input_float_register(reg_offset_float+0)
  rg_Width_arr[tool_index]=floatRegDummy
  floatRegDummy=read_input_float_register(reg_offset_float+1)
  rg_Depth_arr[tool_index]=floatRegDummy
  floatRegDummy=read_input_float_register(reg_offset_float+2)
  rg_DepthRel_arr[tool_index]=floatRegDummy
  intRegDummy=read_input_integer_register(reg_offset_int+0)
  rg_device_id_arr[tool_index]=intRegDummy
  intRegDummy=read_input_integer_register(reg_offset_int+1)
  rg_product_code_arr[tool_index]=intRegDummy
  intRegDummy=read_input_integer_register(reg_offset_int+2)
  rg_Status_arr[tool_index]=intRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+0)
  rg_Busy_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+1)
  rg_Grip_detected_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+2)
  rg_S1_pushed_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+3)
  rg_S1_triggered_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+4)
  rg_S2_pushed_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+5)
  rg_S2_triggered_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+6)
  rg_Safety_error_arr[tool_index]=boolRegDummy
  exit_critical
  end 
  thread rg_dataRead_thread():
  if ON_DEBUG_LOG:
  textmsg("Starting rg_dataRead thread")
  end 
  while rg_dataRead_running:
  sync()
  rg_Depth_prev_arr=rg_Depth_arr
  if(rg_index==ON_DI_DUAL):
  rg_dataRead_RTDE(ON_DI_PRIMARY)
  rg_dataRead_RTDE(ON_DI_SECONDARY)
  else:
  rg_dataRead_RTDE(rg_index)
  end 
  end 
  if ON_DEBUG_LOG:
  textmsg("Stopping rg_dataRead thread")
  end 
  end 
  
  #======    End of OnRobot RG Interface    ======#
  #======    OnRobot TCP Messages    ======#
  
  on_tcp_log_msg_default="OnRobot: Robot TCP Offset set to:"
  on_tcp_log_msg_primary="OnRobot: Robot TCP Offset set to Primary:"
  on_tcp_log_msg_secondary="OnRobot: Robot TCP Offset set to Secondary:"
  
  #======    End of OnRobot TCP Messages    ======#
  #======    OnRobot TCP    ======#
  
  on_tcp_offset_actual=ON_ZEROFRAME
  on_tcp_offset_primary=ON_ZEROFRAME
  on_tcp_static_primary=ON_ZEROFRAME
  on_tcp_dynamic_primary=ON_ZEROFRAME
  on_tcp_adapters=ON_ZEROFRAME
  on_tcp_qc_primary=ON_ZEROFRAME
  on_tcp_base_primary=ON_ZEROFRAME
  on_tcp_gripper_static_primary=ON_ZEROFRAME
  on_tcp_workpiece_primary=ON_ZEROFRAME
  on_tcp_gripper_dynamic_primary=ON_ZEROFRAME
  on_tcp_gripper_primary=ON_ZEROFRAME
  on_tcp_offset_secondary=ON_ZEROFRAME
  on_tcp_static_secondary=ON_ZEROFRAME
  on_tcp_dynamic_secondary=ON_ZEROFRAME
  on_tcp_qc_secondary=ON_ZEROFRAME
  on_tcp_base_secondary=ON_ZEROFRAME
  on_tcp_gripper_static_secondary=ON_ZEROFRAME
  on_tcp_workpiece_secondary=ON_ZEROFRAME
  on_tcp_gripper_dynamic_secondary=ON_ZEROFRAME
  on_tcp_gripper_secondary=ON_ZEROFRAME
  on_tcp_custom_preset_assigned=False
  on_tcp_custom_preset=ON_ZEROFRAME
  def on_tcp_init_adapters():
  if ON_DEBUG_LOG:
  textmsg("TCP Init Adapters start..")
  end 
  enter_critical
  on_tcp_adapters=ON_ZEROFRAME
  local adapterCount=length(on_tcp_adapters_array)
  local i=0
  while(i<adapterCount):
  on_tcp_adapters=pose_trans(on_tcp_adapters,on_tcp_adapters_array[i])
  i=i+1
  end
  exit_critical
  if ON_DEBUG_LOG:
  textmsg("TCP Init Adapters end.")
  end 
  end 
  def on_tcp_update_primary():
  if ON_DEBUG_LOG:
  textmsg("TCP Update Primary start..")
  end 
  on_tcp_gripper_dynamic_primary=p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  enter_critical
  on_tcp_dynamic_primary=pose_trans(on_tcp_static_primary,on_tcp_gripper_dynamic_primary)
  on_tcp_offset_primary=pose_trans(on_tcp_dynamic_primary,on_tcp_workpiece_primary)
  exit_critical
  if ON_DEBUG_LOG:
  textmsg("TCP Update Primary end.")
  end 
  end 
  def on_tcp_init_primary():
  if ON_DEBUG_LOG:
  textmsg("TCP Init Primary start..")
  end 
  enter_critical
  on_tcp_base_primary=pose_trans(on_tcp_adapters,on_tcp_qc_primary)
  on_tcp_static_primary=pose_trans(on_tcp_base_primary,on_tcp_gripper_static_primary)
  exit_critical
  on_tcp_update_primary()
  if ON_DEBUG_LOG:
  textmsg("TCP Init Primary end.")
  end 
  end 
  def on_tcp_offset_set(TCP_offset):
  if ON_DEBUG_LOG:
  textmsg("TCP Offset set started!")
  end 
  on_tcp_offset_send(TCP_offset)
  if(on_follow_tcp):
  set_tcp(TCP_offset)
  end 
  on_robot_TCP_offset=TCP_offset
  if ON_DEBUG_LOG:
  textmsg("TCP Offset set to: ",on_robot_TCP_offset)
  end 
  end 
  def on_tcp_offset_forced_set_actual(isPrimary=True):
  if(not on_follow_tcp):
  
  local tcp_log_msg=on_tcp_log_msg_default
  
  textmsg(tcp_log_msg,on_tcp_offset_actual)
  set_tcp(on_tcp_offset_actual)
  end 
  end 
  def on_tcp_update(isPrimary=True):
  on_tcp_update_primary()
  
  on_tcp_set_actual_to(isPrimary)
  end 
  def on_tcp_set_actual_to(isPrimary=True):
  
  on_tcp_offset_actual=on_tcp_offset_primary
  if(on_follow_tcp):
  textmsg(on_tcp_log_msg_default,on_tcp_offset_actual)
  end 
  
  on_tcp_active_is_primary=isPrimary
  on_tcp_offset_set(on_tcp_offset_actual)
  end 
  def on_tcp_update_workpiece_primary(workpiece_offset):
  if ON_DEBUG_LOG:
  textmsg("TCP Update Tool Primary start..")
  end 
  on_tcp_workpiece_primary=workpiece_offset
  on_tcp_update_primary()
  if ON_DEBUG_LOG:
  textmsg("TCP Update Tool Primary end.")
  end 
  end 
  def on_tcp_workpiece_rpy_get(xyz=[0.0,0.0,0.0],rpy=[0.0,0.0,0.0]):
  local rotvec=rpy2rotvec(rpy)
  local workpiece_offset=p[xyz[0],xyz[1],xyz[2],rotvec[0],rotvec[1],rotvec[2]]
  return workpiece_offset
  end 
  
  def on_tcp_update_workpiece(workpiece_offset,tool_index=0):
  if ON_DEBUG_LOG:
  textmsg("TCP Update Tool start..")
  end 
  if(tool_index!=ON_DI_SECONDARY):
  on_tcp_update_workpiece_primary(workpiece_offset)
  local isPrimary=True
  
  end 
  on_tcp_set_actual_to(isPrimary)
  if ON_DEBUG_LOG:
  textmsg("TCP Update Tool end.")
  end 
  end 
  def on_get_tcp_for(tool_index):
  if tool_index==ON_DI_SECONDARY:
  local actual_tcp=on_tcp_static_secondary
  else:
  local actual_tcp=on_tcp_static_primary
  end 
  return actual_tcp
  end 
  def on_tcp_custom_unused():
  return ON_ZEROFRAME
  end 
  def on_tcp_update_custom():
  if ON_DEBUG_LOG:
  textmsg("TCP Update Custom start..")
  end 
  if(on_custom_tcp_enabled):
  on_tcp_custom_unused()
  on_tcp_custom_unused()
  on_tcp_custom_unused()
  on_tcp_custom_unused()
  
  end 
  if ON_DEBUG_LOG:
  textmsg("TCP Update Custom end.")
  end 
  end 
  
  #======    End of OnRobot TCP    ======#
  #======    OnRobot Payload Messages    ======#
  
  on_mass_log_msg="OnRobot: Robot Payload Mass set to:"
  on_cog_log_msg="OnRobot: Robot Payload Center of Gravity set to:"
  
  #======    End of OnRobot Payload Messages    ======#
  #======    OnRobot Payload    ======#
  
  on_cog_actual=ON_ZEROFRAME
  on_mass_actual=0.0
  on_cog_primary=ON_ZEROFRAME
  on_cog_L1L2_primary=ON_ZEROFRAME
  on_mass_primary=0.0
  on_mass_L1L2_primary=0.0
  on_cog_adapters=ON_ZEROFRAME
  on_cog_qc_primary=ON_ZEROFRAME
  on_cog_base_primary=ON_ZEROFRAME
  on_cog_gripper_primary=ON_ZEROFRAME
  on_cog_workpiece_primary=ON_ZEROFRAME
  on_mass_adapters=0.0
  on_mass_qc_primary=0.0
  on_mass_base_primary=0.0
  on_mass_gripper_primary=0.0
  on_mass_workpiece_primary=0.0
  on_cog_secondary=ON_ZEROFRAME
  on_mass_secondary=0.0
  on_cog_gripper_secondary=ON_ZEROFRAME
  on_mass_gripper_secondary=0.0
  on_cog_workpiece_secondary=ON_ZEROFRAME
  on_mass_workpiece_secondary=0.0
  ON_LB2KG001=0.45359237/100
  def on_payload_init_adapters():
  if ON_DEBUG_LOG:
  textmsg("TCP Init Adapters start..")
  end 
  enter_critical
  on_cog_adapters=ON_ZEROFRAME
  on_mass_adapters=0.0
  local massLAL0Ratio=0
  local adapterAbsCOG=ON_ZEROFRAME
  local tcp_adapter_offset=ON_ZEROFRAME
  local adapterCount=length(on_tcp_adapters_array)
  local i=0
  while(i<adapterCount):
  on_mass_adapters=on_mass_adapters+on_mass_adapters_array[i]
  if(on_mass_adapters<=0):
  massLAL0Ratio=0
  else:
  massLAL0Ratio=on_mass_adapters_array[i]/on_mass_adapters
  end
  adapterAbsCOG=pose_trans(tcp_adapter_offset,on_tcp_adapters_array[i])
  adapterAbsCOG=p[adapterAbsCOG[0],adapterAbsCOG[1],adapterAbsCOG[2],0.0,0.0,0.0]
  on_cog_adapters=interpolate_pose(on_cog_adapters,adapterAbsCOG,massLAL0Ratio)
  on_cog_adapters=p[on_cog_adapters[0],on_cog_adapters[1],on_cog_adapters[2],0.0,0.0,0.0]
  tcp_adapter_offset=pose_trans(tcp_adapter_offset,on_tcp_adapters_array[i])
  i=i+1
  sync()
  end
  exit_critical
  if ON_DEBUG_LOG:
  textmsg("TCP Init Adapters end.")
  end 
  end 
  def on_payload_update_primary():
  if ON_DEBUG_LOG:
  textmsg("Payload Update Primary start..")
  end 
  enter_critical
  on_mass_primary=on_mass_L1L2_primary+on_mass_workpiece_primary
  local massL1L2L3Ratio=on_mass_workpiece_primary/on_mass_primary
  local workpieceAbsCOG=pose_trans(on_tcp_dynamic_primary,on_cog_workpiece_primary)
  workpieceAbsCOG=p[workpieceAbsCOG[0],workpieceAbsCOG[1],workpieceAbsCOG[2],0.0,0.0,0.0]
  on_cog_primary=interpolate_pose(on_cog_L1L2_primary,workpieceAbsCOG,massL1L2L3Ratio)
  on_cog_primary=p[on_cog_primary[0],on_cog_primary[1],on_cog_primary[2],0.0,0.0,0.0]
  exit_critical
  if ON_DEBUG_LOG:
  textmsg("Payload Update Primary end.")
  end 
  end 
  def on_payload_init_primary():
  if ON_DEBUG_LOG:
  textmsg("Payload Init Primary start..")
  end 
  enter_critical
  on_mass_base_primary=on_mass_adapters+on_mass_qc_primary
  local massL0L1Ratio=on_mass_qc_primary/on_mass_base_primary
  on_mass_L1L2_primary=on_mass_base_primary+on_mass_gripper_primary
  local massL1L2Ratio=on_mass_gripper_primary/on_mass_L1L2_primary
  local qcAbsCOG=pose_trans(on_tcp_adapters,on_cog_qc_primary)
  qcAbsCOG=p[qcAbsCOG[0],qcAbsCOG[1],qcAbsCOG[2],0.0,0.0,0.0]
  on_cog_base_primary=interpolate_pose(on_cog_adapters,qcAbsCOG,massL0L1Ratio)
  on_cog_base_primary=p[on_cog_base_primary[0],on_cog_base_primary[1],on_cog_base_primary[2],0.0,0.0,0.0]
  local gripperAbsCOG=pose_trans(on_tcp_base_primary,on_cog_gripper_primary)
  gripperAbsCOG=p[gripperAbsCOG[0],gripperAbsCOG[1],gripperAbsCOG[2],0.0,0.0,0.0]
  on_cog_L1L2_primary=interpolate_pose(on_cog_base_primary,gripperAbsCOG,massL1L2Ratio)
  on_cog_L1L2_primary=p[on_cog_L1L2_primary[0],on_cog_L1L2_primary[1],on_cog_L1L2_primary[2],0.0,0.0,0.0]
  exit_critical
  on_payload_update_primary()
  if ON_DEBUG_LOG:
  textmsg("Payload Init Primary end.")
  end 
  end 
  def on_payload_update():
  on_payload_update_primary()
  
  on_mass_actual =on_mass_primary
  on_cog_actual=on_cog_primary
  
  on_payload_set_actual()
  end 
  def on_payload_set_actual():
  
  on_mass_actual =on_mass_primary
  on_cog_actual=on_cog_primary
  
  local CoG=[on_cog_actual[0],on_cog_actual[1],on_cog_actual[2]]
  on_payload_set(on_mass_actual,CoG)
  end 
  def on_payload_update_workpiece_primary(workpiece_mass=0,workpiece_cog=[0.0,0.0,0.0]):
  if ON_DEBUG_LOG:
  textmsg("Payload Update Workpiece Primary start..")
  end 
  on_cog_workpiece_primary=p[workpiece_cog[0],workpiece_cog[1],workpiece_cog[2],0.0,0.0,0.0]
  on_mass_workpiece_primary=workpiece_mass
  on_payload_update_primary()
  if ON_DEBUG_LOG:
  textmsg("Payload Update Workpiece Primary end.")
  end 
  end 
  def on_payload_set(mass,CoG):
  if ON_DEBUG_LOG:
  textmsg("Payload set started!")
  end 
  local center_of_gravity=[CoG[0],CoG[1],CoG[2]]
  on_payload_send(center_of_gravity,mass)
  if(on_isMetric):
  local roundedMass=floor(mass*100+0.5)/100
  else:
  local roundedMass=floor(mass/ON_LB2KG001+0.5)*ON_LB2KG001
  end 
  set_payload(roundedMass,center_of_gravity)
  on_mass_actual=roundedMass
  on_cog_actual=p[CoG[0],CoG[1],CoG[2],0.0,0.0,0.0]
  if ON_DEBUG_LOG:
  textmsg("Payload mass, CoG set to: ",str_cat(str_cat(mass,", "),CoG))
  end 
  end 
  
  def on_payload_update_secondary():
  end 
  def on_payload_init_secondary():
  end 
  
  def on_payload_update_workpiece(workpiece_mass,workpiece_cog=[0.0,0.0,0.0],tool_index=0):
  if ON_DEBUG_LOG:
  textmsg("Payload Update Workpiece start..")
  end 
  if(tool_index!=ON_DI_SECONDARY):
  on_cog_workpiece_primary=p[workpiece_cog[0],workpiece_cog[1],workpiece_cog[2],0.0,0.0,0.0]
  on_mass_workpiece_primary=workpiece_mass
  else:
  on_cog_workpiece_secondary=p[workpiece_cog[0],workpiece_cog[1],workpiece_cog[2],0.0,0.0,0.0]
  on_mass_workpiece_secondary=workpiece_mass
  end 
  on_payload_update()
  if ON_DEBUG_LOG:
  textmsg("Payload Update Workpiece end.")
  end 
  end 
  def on_payload_get_cog2tcp_workpiece(tool_index=0):
  if(tool_index!=ON_DI_SECONDARY):
  local cog_tool=[on_tcp_workpiece_primary[0],on_tcp_workpiece_primary[1],on_tcp_workpiece_primary[2]]
  else:
  local cog_tool=[on_tcp_workpiece_secondary[0],on_tcp_workpiece_secondary[1],on_tcp_workpiece_secondary[2]]
  end 
  return cog_tool
  end 
  
  #======    End of OnRobot Payload    ======#
  #======    OnRobot QC TCP    ======#
  
  onrobotmini=0
  
  def on_tcp_offset_send(TCP_offset):
  on_robot_TCP_offset=TCP_offset
  end 
  def on_payload_send(CoG,mass):
  on_robot_payload_cog=CoG
  on_robot_payload_mass=mass
  end 
  
  
  #======    End of OnRobot QC TCP    ======#
  #======    OnRobot RG TCP    ======#
  
  def rg_mount_tcp(gripper_angle,isRG2=True):
  if ON_DEBUG_LOG:
  textmsg("RG Mount TCP command starting..")
  end 
  if(isRG2):
  local gripperBracket=rg2_mount_bracket_offset
  local gripperBody=rg2_mount_body_offset
  else:
  local gripperBracket=rg6_mount_bracket_offset
  local gripperBody=rg6_mount_body_offset
  end 
  local gripperRotVec=rpy2rotvec([gripper_angle,0.0,0.0])
  local gripperMountOffset=p[0.0,0.0,gripperBracket,gripperRotVec[0],gripperRotVec[1],gripperRotVec[2]]
  local gripperOffsetStatic=pose_trans(gripperMountOffset,gripperBody)
  if ON_DEBUG_LOG:
  textmsg("RG Mount TCP command ended.")
  end 
  return gripperOffsetStatic
  end 
  def rg_mount_cog(gripper_angle,isRG2=True):
  if ON_DEBUG_LOG:
  textmsg("RG Mount CoG command starting..")
  end 
  if(isRG2):
  local gripperBracket=rg2_mount_bracket_offset
  local gripperCoG=rg2_mount_cog_offset
  else:
  local gripperBracket=rg6_mount_bracket_offset
  local gripperCoG=rg6_mount_cog_offset
  end 
  local gripperRotVec=rpy2rotvec([gripper_angle,0.0,0.0])
  local gripperMountOffset=p[0.0,0.0,gripperBracket,gripperRotVec[0],gripperRotVec[1],gripperRotVec[2]]
  local gripperCOGOffset=pose_trans(gripperMountOffset,gripperCoG)
  gripperCOGOffset=p[gripperCOGOffset[0],gripperCOGOffset[1],gripperCOGOffset[2],0.0,0.0,0.0]
  if ON_DEBUG_LOG:
  textmsg("RG Mount CoG command ended.")
  end 
  return gripperCOGOffset
  end 
  def rg_fcp_depth_calc_frame(tool_index=0):
  local gripperDepth=rg_Depth_arr[tool_index]
  local z_offset=-gripperDepth/1000.0
  return p[0.0,0.0,z_offset,0.0,0.0,0.0]
  end 
  def rg_tcp_dynamic_get(tool_index=0):
  local offset=rg_fcp_depth_calc_frame(tool_index)
  return offset
  end 
  def rg_payload_set(mass,tool_index=0,use_guard=False):
  if ON_DEBUG_LOG:
  textmsg("RG Payload mass command starting..")
  end 
  if(tool_index==ON_DI_SECONDARY):
  local cogTool=[on_cog_workpiece_secondary[0],on_cog_workpiece_secondary[1],on_cog_workpiece_secondary[2]]
  else:
  local cogTool=[on_cog_workpiece_primary[0],on_cog_workpiece_primary[1],on_cog_workpiece_primary[2]]
  end 
  if(use_guard and rg_Grip_detected_arr[tool_index]):
  local mass2set=mass
  rg_Grip_guard_arr[tool_index]=not on_ioqc
  else:
  local mass2set=0.0
  rg_Grip_guard_arr[tool_index]=False
  end 
  on_payload_update_workpiece(mass2set,cogTool,tool_index)
  if ON_DEBUG_LOG:
  textmsg("RG Payload mass command ended.")
  end 
  end 
  
  #======    End of OnRobot RG TCP    ======#
  #======    OnRobot  Speedl    ======#
  
  on_speedl_thread_handler=0
  on_speedl_is_enabled=False
  on_speedl_is_running=False
  on_speedl_acc=0.0
  ft_speedl_hg_caranteen_reached=False
  ft_speedl_hg_caranteen_safemode=False
  on_speedl_for_ftcontrol=False
  on_speedl_for_move=False
  on_speedl_for_handguide=False
  on_speedl_for_insertpart=False
  on_speedl_for_depthcompensation=False
  on_speedl_for_center=False
  on_speedl_for_gecko=False
  on_speedl_acc=10000.0 
  on_speedl_acc_to_zero=3.0 
  ON_SPEEDL_FTCONTROL=1
  ON_SPEEDL_HANDGUIDE=2
  ON_SPEEDL_TRAJECTORY=3
  ON_SPEEDL_MOVE=ON_SPEEDL_TRAJECTORY
  ON_SPEEDL_INSERTPART=4
  ON_SPEEDL_DEPTHCOMP=5
  ON_SPEEDL_CENTER=6
  ON_SPEEDL_GECKO=7
  def on_wait_ms(time_ms):
  local sync_time=ceil(norm(time_ms/2.0))
  while(sync_time>0):
  sync_time=sync_time-1
  sync()
  end
  end 
  def on_error(status_flag,message,title,stop_var=False):
  if(status_flag):
  popup(message,title=title,error=True,blocking=False)
  stop_var=True
  end 
  return stop_var
  end 
  def on_warning(status_flag,message,title,isPopupNeeded=False,is_shown=False):
  if(status_flag):
  if(not is_shown):
  if(isPopupNeeded):
  popup(message,title=title,warning=True,blocking=False)
  else:
  textmsg(title+": ",message)
  end 
  is_shown=True
  end 
  else:
  is_shown=False
  end 
  return is_shown
  end 
  def on_speedl_add_extra(speedBase,speedExtra):
  speedSum=ON_ZERO6D
  speedBaseP=p[speedBase[0],speedBase[1],speedBase[2],speedBase[3],speedBase[4],speedBase[5]]
  speedExtraP=p[speedExtra[0],speedExtra[1],speedExtra[2],speedExtra[3],speedExtra[4],speedExtra[5]]
  speedSumP=pose_add(speedExtraP,speedBaseP)
  speedSum=[speedSumP[0],speedSumP[1],speedSumP[2],speedSumP[3],speedSumP[4],speedSumP[5]]
  return speedSum
  end 
  
  thread on_speedl_thread():
  if ON_DEBUG_LOG:
  textmsg("Speedl thread started..")
  end 
  enter_critical
  on_speedl_is_running=True
  on_speedl_is_enabled=True
  exit_critical
  on_speedL=ON_ZERO6D
  on_speedL_last=ON_ZERO6D
  
  while on_speedl_is_running:
  on_speedBase=on_speedCB_get()
  on_speedL=on_speedBase
  
  
  if on_speedl_is_enabled:
  if(on_speedL==ON_ZERO6D):
  on_speedL=[on_speedL_last[0]/100,on_speedL_last[1]/100,on_speedL_last[2]/100,on_speedL_last[3]/100,on_speedL_last[4]/100,on_speedL_last[5]/100]
  end
  speedl(on_speedL,a=on_speedl_acc,t=speedlTime)
  else:
  speedl(ON_ZERO6D,a=on_speedl_acc_to_zero,t=speedlTime)
  end 
  on_speedL_last=on_speedL
  end 
  
  on_speedL=ON_ZERO6D
  if ON_DEBUG_LOG:
  textmsg("Speedl thread ended.")
  end 
  end 
  def on_speedl_integer_get():
  local speedl_integer=binary_list_to_integer([on_speedl_for_ftcontrol,on_speedl_for_handguide,on_speedl_for_move,on_speedl_for_insertpart,on_speedl_for_depthcompensation,on_speedl_for_center,on_speedl_for_gecko])
  return speedl_integer
  end 
  def on_speedl_start_for(speedl_id):
  if(speedl_id==ON_SPEEDL_FTCONTROL):
  on_speedl_for_ftcontrol=True
  elif(speedl_id==ON_SPEEDL_HANDGUIDE):
  on_speedl_for_handguide=True
  elif(speedl_id==ON_SPEEDL_TRAJECTORY):
  on_speedl_for_move=True
  elif(speedl_id==ON_SPEEDL_INSERTPART):
  on_speedl_for_insertpart=True
  elif(speedl_id==ON_SPEEDL_DEPTHCOMP):
  on_speedl_for_depthcompensation=True
  elif(speedl_id==ON_SPEEDL_CENTER):
  on_speedl_for_center=True
  elif(speedl_id==ON_SPEEDL_GECKO):
  on_speedl_for_gecko=True
  else:
  textmsg("Unknown Start speedl ID received: ",speedl_id)
  end 
  local speedl_integer=on_speedl_integer_get()
  if not(speedl_integer==0):
  if not on_speedl_is_running:
  on_speedl_thread_handler=run on_speedl_thread()
  end 
  end 
  return on_speedl_is_running
  end 
  def on_speedl_stop_for(speedl_id,brake=10,brakeRot=10):
  if(speedl_id==ON_SPEEDL_FTCONTROL):
  on_speedl_for_ftcontrol=False
  elif(speedl_id==ON_SPEEDL_HANDGUIDE):
  on_speedl_for_handguide=False
  elif(speedl_id==ON_SPEEDL_TRAJECTORY):
  on_speedl_for_move=False
  elif(speedl_id==ON_SPEEDL_INSERTPART):
  on_speedl_for_insertpart=False
  elif(speedl_id==ON_SPEEDL_DEPTHCOMP):
  on_speedl_for_depthcompensation=False
  elif(speedl_id==ON_SPEEDL_CENTER):
  on_speedl_for_center=False
  elif(speedl_id==ON_SPEEDL_GECKO):
  on_speedl_for_gecko=False
  on_speedGecko_set(ON_ZERO6D)
  else:
  textmsg("Unknown Stop speedl ID received: ",speedl_id)
  end 
  local speedl_integer=on_speedl_integer_get()
  if(speedl_integer==0):
  if(on_speedl_is_running):
  kill on_speedl_thread_handler
  enter_critical
  on_speedl_is_running=False
  exit_critical
  
  end 
  if ON_DEBUG_LOG:
  textmsg("Speedl thread stopped")
  end 
  stopl(brake,brakeRot)
  end 
  return on_speedl_is_running
  end 
  def on_speedl_pause():
  on_speedl_is_enabled=False
  return on_speedl_integer_get()
  end 
  def on_speedl_resume():
  on_speedl_is_enabled=True
  return on_speedl_integer_get()
  end 
  
  #======    End of OnRobot  Speedl    ======#
  #======    OnRobot RG Engine Messages    ======#
  
  rg_error_title="OnRobot - RG error"
  rg_device_id_waiting="Waiting for valid OnRobot RG ID..."
  rg_device_id_timeout="Waiting for valid OnRobot RG ID timed out.<br>Program halted."
  rg_data_error_title="OnRobot - RG Data error"
  rg_data_error_type="No or unknown Gripper connected."
  rg_data_warning_title="OnRobot - RG Data warning:"
  rg_status_error_title="OnRobot - RG Status error"
  rg_status_error_missing="Communication problem with an RG gripper. Please check the device.<br>Program halted."
  rg_else_error="Unknown error code:"
  rg_status_msg_single="RG status:"
  rg_data_error_bit0_single="Wrong size of float data received."
  rg_data_error_bit1_single="Wrong size of integer data received."
  rg_data_error_bit2_single="Wrong size of boolean data received."
  rg_status_error_mismatch_single="The RG's Status is not matching with its Safety Switches' state."
  rg_status_error_s1_triggered_single="The S1 Safety Switch has been triggered.<br>Please restart the RG gripper."
  rg_status_error_s1_pushed_single="The S1 Safety Switch has been pushed."
  rg_status_error_s2_triggered_single="The S2 Safety Switch has been triggered.<br>Please restart the RG gripper."
  rg_status_error_s2_pushed_single="The S2 Safety Switch has been pushed."
  rg_status_error_safety_system_single="Safety System error occured.<br>Please restart the RG gripper."
  rg_status_msg_primary="RG Primary status:"
  rg_data_error_bit0_primary="Wrong size of float data received for Primary RG."
  rg_data_error_bit1_primary="Wrong size of integer data received for Primary RG."
  rg_data_error_bit2_primary="Wrong size of boolean data received for Primary RG."
  rg_status_error_mismatch_primary="The Primary RG's Status is not matching with its Safety Switches' state."
  rg_status_error_s1_pushed_primary="The S1 Safety Switch has been pushed on Primary RG."
  rg_status_error_s1_triggered_primary="The S1 Safety Switch has been triggered on Primary RG.<br>Please restart the Primary RG gripper."
  rg_status_error_s2_pushed_primary="The S2 Safety Switch has been pushed on Primary RG."
  rg_status_error_s2_triggered_primary="The S2 Safety Switch has been triggered on Primary RG.<br>Please restart the Primary RG gripper."
  rg_status_error_safety_system_primary="Safety System error occured.<br>Please restart the Primary RG gripper."
  rg_status_msg_secondary="RG Secondary status:"
  rg_data_error_bit0_secondary="Wrong size of float data received for Secondary RG."
  rg_data_error_bit1_secondary="Wrong size of integer data received for Secondary RG."
  rg_data_error_bit2_secondary="Wrong size of boolean data received for Secondary RG."
  rg_status_error_mismatch_secondary="The Secondary RG's Status is not matching with its Safety Switches' state."
  rg_status_error_s1_pushed_secondary="The S1 Safety Switch has been pushed on Secondary RG."
  rg_status_error_s1_triggered_secondary="The S1 Safety Switch has been triggered on Secondary RG.<br>Please restart the Secondary RG gripper."
  rg_status_error_s2_pushed_secondary="The S2 Safety Switch has been pushed on Secondary RG."
  rg_status_error_s2_triggered_secondary="The S2 Safety Switch has been triggered on Secondary RG.<br>Please restart the Secondary RG gripper."
  rg_status_error_safety_system_secondary="The Safety System error.<br>Please restart the Secondary RG gripper."
  
  #======    End of OnRobot RG Engine Messages    ======#
  #======    OnRobot RG Engine    ======#
  
  rg_dataProcess_running=False
  rg_start_flange=ON_ZEROPOSE
  rg_start_pose=ON_ZEROPOSE
  RG_STATUS_IGNORE_SHIFT=4
  def rg_status_int_get(tool_index):
  local status_int=binary_list_to_integer([rg_S1_pushed_arr[tool_index],rg_S1_triggered_arr[tool_index],rg_S2_pushed_arr[tool_index],rg_S2_triggered_arr[tool_index],rg_Safety_error_arr[tool_index]])
  return status_int
  end 
  def rg_dataProcess_status_errors(rg_stop=False):
  enter_critical
  local tool_index=rg_index
  if(tool_index==ON_DI_DUAL):
  tool_index=ON_DI_SECONDARY
  rg_stop=on_error((rg_device_id_arr[tool_index]!=tool_index),rg_status_error_missing,rg_status_error_title,rg_stop)
  rg_stop=on_error((rg_product_code_arr[tool_index]==ON_DEVICE_ID_MISSING),rg_status_error_missing,rg_status_error_title,rg_stop)
  tool_index=ON_DI_PRIMARY
  end 
  rg_stop=on_error((rg_device_id_arr[tool_index]!=tool_index),rg_status_error_missing,rg_status_error_title,rg_stop)
  rg_stop=on_error((rg_product_code_arr[tool_index]==ON_DEVICE_ID_MISSING),rg_status_error_missing,rg_status_error_title,rg_stop)
  
  local switch_error_single=rg_status_int_get(tool_index)
  local status_error_single=floor(rg_Status_arr[tool_index]/RG_STATUS_IGNORE_SHIFT)
  if(status_error_single!=switch_error_single):
  on_warning(((status_error_single-switch_error_single)>0),str_cat(rg_else_error,rg_Status_arr[tool_index]),rg_status_error_title)
  end 
  if(switch_error_single!=0):
  rg_stop=on_error(rg_S1_pushed_arr[tool_index],rg_status_error_s1_pushed_single,rg_status_error_title,rg_stop)
  rg_stop=on_error(rg_S1_triggered_arr[tool_index],rg_status_error_s1_triggered_single,rg_status_error_title,rg_stop)
  rg_stop=on_error(rg_S2_pushed_arr[tool_index],rg_status_error_s2_pushed_single,rg_status_error_title,rg_stop)
  rg_stop=on_error(rg_S2_triggered_arr[tool_index],rg_status_error_s2_triggered_single,rg_status_error_title,rg_stop)
  rg_stop=on_error(rg_Safety_error_arr[tool_index],rg_status_error_safety_system_single,rg_status_error_title,rg_stop)
  end 
  
  exit_critical
  return rg_stop
  end 
  def rg_dataProcess():
  enter_critical
  local tool_index=rg_index
  if tool_index==ON_DI_DUAL:
  rg_Width_primary=rg_Width_arr[ON_DI_PRIMARY]
  rg_Depth_primary=rg_Depth_arr[ON_DI_PRIMARY]
  rg_DepthRel_primary=rg_DepthRel_arr[ON_DI_PRIMARY]
  rg_Busy_primary=rg_Busy_arr[ON_DI_PRIMARY]
  rg_Grip_detected_primary=rg_Grip_detected_arr[ON_DI_PRIMARY]
  rg_Width_secondary=rg_Width_arr[ON_DI_SECONDARY]
  rg_Depth_secondary=rg_Depth_arr[ON_DI_SECONDARY]
  rg_DepthRel_secondary=rg_DepthRel_arr[ON_DI_SECONDARY]
  rg_Busy_secondary=rg_Busy_arr[ON_DI_SECONDARY]
  rg_Grip_detected_secondary=rg_Grip_detected_arr[ON_DI_SECONDARY]
  else:
  rg_Width=rg_Width_arr[tool_index]
  rg_Depth=rg_Depth_arr[tool_index]
  rg_DepthRel=rg_DepthRel_arr[tool_index]
  rg_Busy=rg_Busy_arr[tool_index]
  rg_Grip_detected=rg_Grip_detected_arr[tool_index]
  end 
  exit_critical
  end 
  thread rg_dataProcess_thread():
  if ON_DEBUG_LOG:
  textmsg("Starting rg_dataProcess thread")
  end 
  while rg_dataProcess_running:
  sync()
  local rg_stop=False
  rg_stop=rg_dataProcess_status_errors(rg_stop)
  if rg_stop:
  halt
  end 
  rg_dataProcess()
  end 
  if ON_DEBUG_LOG:
  textmsg("Stopping rg_dataProcess thread")
  end 
  end 
  def rg_index_get():
  return rg_index
  end 
  
  #======    End of OnRobot RG Engine    ======#
  rg_mounting_angle_arr[0] = 0.0
  rg_fingertip_arr[0] = 4.599999904632568
  rg_Depth_arr[0] = 38.29999923706054
  textmsg(on_devices_primary_log, ": Quick Changer + RG2 + [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]")
  on_follow_tcp = False
  on_tcp_active_is_primary = True
  on_tcp_adapters_array = []
  on_cog_adapters_array = []
  on_mass_adapters_array = []
  on_tcp_qc_primary = p[0.0, 0.0, 0.0136, 0.0, 0.0, 0.0]
  on_cog_qc_primary = p[0.0, 0.0, 0.004, 0.0, 0.0, 0.0]
  on_mass_qc_primary = 0.06
  on_tcp_gripper_static_primary = rg_mount_tcp(rg_mounting_angle_arr[0])
  on_cog_gripper_primary = rg_mount_cog(rg_mounting_angle_arr[0])
  on_mass_gripper_primary = 0.78
  on_tcp_workpiece_primary = p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  on_cog_workpiece_primary = p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  on_mass_workpiece_primary = 0.0
  
  #======    End of OnRobot RG Depth    ======#
  #======    OnRobot RG Width Messages    ======#
  
  rg_grip_title="OnRobot - RG Grip"
  rg_grip_return_error_n1="RG Grip command returned with error.<br>Please be sure that the required width is between the limits.<br>Program halted."
  
  #======    End of OnRobot RG Width Messages    ======#
  #======    OnRobot RG Width    ======#
  
  RG_MIN_WIDTH=0
  RG_MAX_WIDTH_RG2=110
  RG_MAX_WIDTH_RG6=160
  RG_MIN_FORCE=0
  RG_MAX_FORCE_RG2=40
  RG_MAX_FORCE_RG6=120
  rg__grip_param_warning_width="The parameter 'width' is out of the limits. Limited value sent: "
  rg__grip_param_warning_force="The parameter 'force' is out of the limits. Limited value sent: "
  def rg_depth_compensate(tool_index,start_depth_mm):
  local timeout=0
  while not rg_Busy_arr[tool_index]:
  sleep(0.008)
  timeout=timeout+1
  if timeout>20:
  break
  end
  end
  local start_pose=get_forward_kin()
  if(tool_index==ON_DI_SECONDARY):
  local tcp_static=on_tcp_static_secondary
  else:
  local tcp_static=on_tcp_static_primary
  end 
  local t_w_rg=pose_trans(get_actual_tool_flange_pose(),tcp_static)
  local t_rg_w=pose_inv(t_w_rg)
  local compensation_depth_mm=0
  local after_ready_continue_count=10
  while True:
  local busy=rg_Busy_arr[tool_index]
  if not busy:
  if after_ready_continue_count>0:
  after_ready_continue_count=after_ready_continue_count-1
  else:
  break
  end
  end
  local measure_depth_mm=rg_Depth_arr[tool_index]
  compensation_depth_mm=measure_depth_mm-start_depth_mm
  local target_pose=pose_add(start_pose,pose_trans(pose_trans(t_w_rg,p[0,0,compensation_depth_mm/1000.0,0,0,0]),t_rg_w))
  servoj(get_inverse_kin(target_pose),t=0.008,lookahead_time=0.033,gain=1500)
  end
  stopj(20)
  end
  def rg_grip(width,force,tool_index=0,blocking=True,depth_comp=False,popupmsg=True):
  if ON_DEBUG_LOG:
  textmsg("RG Grip start..")
  end 
  local retVal=0
  local limitOffset=(2.0*rg_fingertip_arr[tool_index])
  local width2send=width
  if limitOffset>0:
  local minWidth=RG_MIN_WIDTH
  else:
  local minWidth=RG_MIN_WIDTH-limitOffset
  end 
  if not(width2send>=minWidth):
  width2send=minWidth
  textmsg(rg__grip_param_warning_width,width2send)
  elif not(force>=RG_MIN_FORCE):
  force=RG_MIN_FORCE
  textmsg(rg__grip_param_warning_force,force)
  end 
  if(rg_product_code_arr[tool_index]==RG_DEVICE_ID_RG6):
  if not(width2send<=RG_MAX_WIDTH_RG6-limitOffset):
  width2send=RG_MAX_WIDTH_RG6-limitOffset
  textmsg(rg__grip_param_warning_width,width2send)
  elif not(force<=RG_MAX_FORCE_RG6):
  force=RG_MAX_FORCE_RG6
  textmsg(rg__grip_param_warning_force,force)
  end 
  else:
  if not(width2send<=RG_MAX_WIDTH_RG2-limitOffset):
  width2send=RG_MAX_WIDTH_RG2-limitOffset
  textmsg(rg__grip_param_warning_width,width2send)
  elif not((force<=RG_MAX_FORCE_RG2)):
  force=RG_MAX_FORCE_RG2
  textmsg(rg__grip_param_warning_force,force)
  end 
  end 
  rg_Grip_guard_arr[tool_index]=False
  sync()
  if(tool_index==ON_DI_SECONDARY):
  local isPrimary=False
  else:
  local isPrimary=True
  end 
  if(on_follow_tcp):
  on_tcp_set_actual_to(isPrimary)
  end 
  if depth_comp:
  local start_depth_mm=rg_Depth_arr[tool_index]
  end 
  sync()
  retVal=on_tool_xmlrpc.rg_grip(tool_index,width2send+0.0,force+0.0)
  if(retVal!=0):
  popup(rg_grip_return_error_n1,rg_grip_title,error=True,blocking=False)
  halt
  end 
  if depth_comp:
  rg_depth_compensate(tool_index,start_depth_mm)
  end 
  if blocking:
  if not depth_comp:
  local timeout=0
  while not rg_Busy_arr[tool_index]:
  sleep(0.008)
  timeout=timeout+1
  if timeout>20:
  break
  end 
  end 
  end 
  while(rg_Busy_arr[tool_index]==True):
  sync()
  end 
  end 
  if(on_follow_tcp):
  on_tcp_update(isPrimary)
  end 
  if ON_DEBUG_LOG:
  textmsg("RG Grip ended.")
  end 
  return retVal
  end 
  
  #======    End of OnRobot RG Width    ======#
  #======    OnRobot VG Monitor Messages    ======#
  
  rg_monitor_error_title="OnRobot - RG Grip lost"
  rg_monitor_grip_lost_error="Grip lost detected.<br>Program halted."
  
  #======    End of OnRobot VG Monitor Messages    ======#
  #======    OnRobot RG Monitor    ======#
  
  thread rg_monitor_thread():
  while True:
  sync()
  local rg_error=False
  if(rg_index==ON_DI_DUAL):
  local tool_index=ON_DI_SECONDARY
  rg_error=rg_monitor_check(tool_index)
  local tool_index=ON_DI_PRIMARY
  else:
  local tool_index=rg_index
  end 
  rg_error=rg_error or rg_monitor_check(tool_index)
  if rg_error:
  halt
  end 
  end 
  end 
  def rg_monitor_check(tool_index=0):
  local error=False
  if rg_Grip_guard_arr[tool_index]and not rg_Grip_detected_arr[tool_index]:
  popup(rg_monitor_grip_lost_error,title=rg_monitor_error_title,error=True,blocking=False)
  rg_payload_set(0,tool_index=tool_index)
  error=True
  end 
  return error
  end 
  
  #======    End of OnRobot RG Monitor    ======#
  #======    OnRobot Run    ======#
  
  on_portopen_javaSocket()
  sync()
  textmsg(on_xmlrpc_start_ip,on_conn_ip)
  if(ON_REG_USE_TOOL):
  on_regStart_conn=[ON_CONN_SHIFT_BOOL,ON_CONN_SHIFT_INT,ON_CONN_SHIFT_FLOAT]
  on_regSum_conn=[ON_CONN_REG_SUM_BOOL,ON_CONN_REG_SUM_INT,ON_CONN_REG_SUM_FLOAT]
  on_rtde_feed_open(on_conn_ip,on_conn_rtde_feed_name,on_regStart_conn,on_regSum_conn,ON_REGISTERS_SPEEDL_FLOAT)
  sync()
  textmsg(on_xmlrpc_start_ip,on_tool_ip)
  on_regStart_tool=[ON_TOOL_SHIFT_BOOL,ON_TOOL_SHIFT_INT,ON_TOOL_SHIFT_FLOAT]
  on_regSum_tool=[ON_TOOL_REG_SUM_BOOL,ON_TOOL_REG_SUM_INT,ON_TOOL_REG_SUM_FLOAT]
  on_rtde_feed_open(on_tool_ip,on_tool_rtde_feed_name,on_regStart_tool,on_regSum_tool,0)
  sync()
  else:
  on_regStart_conn=[ON_CONN_SHIFT_BOOL,ON_CONN_SHIFT_INT,ON_CONN_SHIFT_FLOAT]
  on_regSum_conn=[ON_CONN_REG_SUM_BOOL,ON_CONN_REG_SUM_INT,ON_CONN_REG_SUM_FLOAT]
  on_rtde_feed_open(on_conn_ip,on_conn_rtde_feed_name,on_regStart_conn,on_regSum_conn,ON_REGISTERS_SPEEDL_FLOAT)
  sync()
  end
  on_set_rtde_watchdog(updateHz=0.2)
  sync()
  on_dataProcess_thrd=run on_dataProcess_thread()
  sync()
  on_tcp_init_adapters()
  on_payload_init_adapters()
  on_tcp_init_primary()
  on_payload_init_primary()
  
  on_tcp_update_custom()
  on_tcp_set_actual_to(on_tcp_active_is_primary)
  if(on_follow_tcp):
  on_payload_set_actual()
  end 
  on_watchdog_thrd=run on_set_watchdog_thread()
  sync()
  def done_waiting_for_init(device_name,product_code,tool_index=0):
  textmsg(str_cat(device_name,str_cat(str_cat("[",tool_index),"]: ")),product_code)
  end
  
  #======    End of OnRobot Run    ======#
  #======    OnRobot QC Start    ======#
  
  if(on_toolConnector):
  tc_setup_tool()
  end 
  sync()
  
  #======    End of OnRobot QC Start    ======#
  #======    OnRobot RG Run    ======#
  
  def rg_wait_for_init(tool_index):
  local rg_timeout=0
  while not((rg_product_code_arr[tool_index]==RG_DEVICE_ID_RG2)or(rg_product_code_arr[tool_index]==RG_DEVICE_ID_RG6)):
  sync()
  rg_timeout=rg_timeout+1
  if(rg_timeout>ON_INIT_TIMEOUT):
  popup(rg_device_id_timeout,rg_error_title,error=True,blocking=False)
  halt
  end 
  end 
  done_waiting_for_init("RG",rg_product_code_arr[tool_index],tool_index)
  end 
  rg_dataRead_running=True
  sync()
  rg_dataRead_thrd=run rg_dataRead_thread()
  sync()
  textmsg(rg_device_id_waiting)
  if(rg_index==ON_DI_DUAL):
  rg_wait_for_init(ON_DI_PRIMARY)
  rg_wait_for_init(ON_DI_SECONDARY)
  else:
  rg_wait_for_init(rg_index)
  end 
  sync()
  rg_dataProcess_running=True
  sync()
  rg_dataProcess_thrd=run rg_dataProcess_thread()
  sync()
  rg_monitor_thread_handle=run rg_monitor_thread()
  sync()
  
  #======    End of OnRobot RG Run    ======#
  # end: URCap Installation Node
  global Pallet_1_cnt_1=1
  global Pallet_1_lct=1
  global Pallet_1_lno=1
  global Pallet_1_sep= False 
  global Pallet_1_tct=1
  global Pallet_2_cnt=1
  global Pallet_2_lct=1
  global Pallet_2_lno=1
  global Pallet_2_sep= False 
  global Pallet_2_tct=1
  global Pallet_3_cnt=1
  global Pallet_3_lct=1
  global Pallet_3_lno=1
  global Pallet_3_sep= False 
  global Pallet_3_tct=1
  global Pallet_4_cnt=1
  global Pallet_4_lct=1
  global Pallet_4_lno=1
  global Pallet_4_sep= False 
  global Pallet_4_tct=1
  global Pallet_5_cnt=1
  global Pallet_5_lct=1
  global Pallet_5_lno=1
  global Pallet_5_sep= False 
  global Pallet_5_tct=1
  global hp_p=p[.319681363846, .015299262925, .369468637951, 2.220701322114, -2.190713279097, .003090160414]
  global hp_q=[0.6262712478637695, -1.4167909634164353, -2.2861475944519043, -4.173284193078512, -1.5685938040362757, -2.524599854146139]
  global Approach_p=p[.297017361321, .236034431087, .306206878599, 2.247158174641, -2.190466749873, .005307345620]
  global Approach_q=[1.149627685546875, -1.6082774601378382, -2.2424657344818115, -4.00833048442983, -1.5717485586749476, -2.0126073996173304]
  global ToolActionPoint_p=p[.296989870783, .236006861759, .269053131804, 2.247037920822, -2.190654475295, .005171745446]
  global ToolActionPoint_q=[1.1497442722320557, -1.6615997753539027, -2.2730040550231934, -3.924399038354391, -1.5716093222247522, -2.0120752493487757]
  global Exit_1_p=p[.296997268642, .235994968187, .299832519098, 2.247047763467, -2.190402466132, .005283514382]
  global Exit_1_q=[1.1496323347091675, -1.6169754467406214, -2.248058795928955, -3.994150539437765, -1.571772877370016, -2.0125353972064417]
  global Approach_6_p=p[.470972033859, .012999670601, .326331981646, 2.221998244795, -2.215958365523, .004887116918]
  global Approach_6_q=[0.407408744096756, -1.7359382114806117, -2.0511882305145264, -4.069623848000997, -1.5694416205035608, -2.7321341673480433]
  global ToolActionPoi_6_p=p[.470976604026, .013036707296, .265940553111, 2.235751061734, -2.201893431820, .005288918706]
  global ToolActionPoi_6_q=[0.4076489210128784, -1.8086935482420863, -2.0966391563415527, -3.951421638528341, -1.5688679854022425, -2.744049612675802]
  global Exit_7_p=p[.471037924053, .013004879140, .283240200074, 2.247256997746, -2.190406922935, .005289109546]
  global Exit_7_q=[0.4074883460998535, -1.786666055718893, -2.0846290588378906, -3.985268016854757, -1.569010082875387, -2.754678551350729]
  global Approach_5_p=p[.470878531294, .009178999597, .274148842452, -2.171525530191, 2.245417031444, .016371484035]
  global Approach_5_q=[0.39414384961128235, -1.7944914303221644, -2.0916779041290283, -3.9556108913817347, -1.5896433035479944, -2.708776299153463]
  global ToolActionPoi_5_p=p[.470999555222, .008624208358, .263976812363, -2.174212634692, 2.248127105270, .009744591355]
  global ToolActionPoi_5_q=[0.39428988099098206, -1.808049818078512, -2.0985283851623535, -3.9371990166106166, -1.5842536131488245, -2.708644215260641]
  global Exit_6_p=p[.469398668719, .010095289889, .296313589454, -2.217537160237, 2.217341255476, -.008792447064]
  global Exit_6_q=[0.40248680114746094, -1.7652493915953578, -2.0793778896331787, -4.002708574334616, -1.5703852812396448, -2.7342265287982386]
  global Waypoint_2_p=p[.343194716737, .015136729708, .389494181926, 2.210760885227, -2.229284741516, .003213995338]
  global Waypoint_2_q=[0.5759528279304504, -1.4386144441417237, -2.2214462757110596, -4.19599523166799, -1.5720966498004358, -2.554185930882589]
  global Waypoint_1_p=p[.343191673318, .015130816737, .281124678479, 2.210730629743, -2.229287204423, .003242849749]
  global Waypoint_1_q=[0.5764562487602234, -1.5776668987669886, -2.3315269947052, -3.9468804798521937, -1.5715869108783167, -2.5527613798724573]
  global Approach_1_p=p[.174044696055, .233964210216, .297981067912, -2.211444147878, 2.230105853911, .004169116790]
  global Approach_1_q=[1.5719661712646484, -1.442255051141121, -2.4149832725524902, -3.9948793850340785, -1.575156037007467, -1.556385342274801]
  global ToolActionPoi_1_p=p[.174043605332, .237481852869, .269916680343, 2.210229320019, -2.228975978211, .001493801459]
  global ToolActionPoi_1_q=[1.5721074342727661, -1.4983287763646622, -2.4359450340270996, -3.9228583774962367, -1.5749157110797327, -1.5559504667865198]
  global Exit_2_p=p[.176061093700, .234189993070, .290595575307, -2.172034893576, 2.265496597684, .007031752300]
  global Exit_2_q=[1.5635604858398438, -1.4562681478312989, -2.41986346244812, -3.973156591454977, -1.574798885975973, -1.5309999624835413]
  global Approach_2_p=p[.173318532303, -.211743222252, .282827770878, 2.228716382569, -2.212414033390, .002733332574]
  global Approach_2_q=[-0.1922367254840296, -1.424960882668831, -2.465012550354004, -3.9639181099333705, -1.571937386189596, -3.33625299135317]
  global ToolActionPoi_2_p=p[.173324894215, -.211741465090, .273290187467, 2.228701268801, -2.212428270615, .002695618889]
  global ToolActionPoi_2_q=[-0.19216901460756475, -1.4421763581088562, -2.4743270874023438, -3.937408824960226, -1.5718854109393519, -3.3360803763019007]
  global Exit_3_p=p[.173335768857, -.211732658630, .298768559537, 2.228670857403, -2.212476219844, .002714799110]
  global Exit_3_q=[-0.1922844091998499, -1.3977401864579697, -2.4487504959106445, -4.007403751412863, -1.5720532576190394, -3.336404863988058]
  while (True):
    $ 1 "Robot Program"
    $ 2 "MoveL"
    $ 3 "hp" "breakAfter"
    movel(hp_p, a=1.2, v=0.25)
    # begin: URCap Program Node
    #   Source: OnRobot, 6.2.0, OnRobot A/S
    #   Type: RG Grip
    $ 4 "RG Grip"
on_return = rg_grip(100.0, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
    # end: URCap Program Node
    $ 5 "Loop 6 times"
    Loop_2 = 0
    while (Loop_2 < 6):
      $ 6 "R"
      def R_trans(pose):
      return p[pose[0], pose[1], pose[2], 0, 0, 0]
    end
    def R_rot(pose):
    return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def R_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(R_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), R_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(R_rot(T_feature_referencePoint_taught), pose_trans(R_rot(T_referencePoint_approach_taught), pose_inv(R_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(R_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, R_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_4_tct = 6
  if (Pallet_4_cnt > 6 or Pallet_4_cnt < 1):
    Pallet_4_cnt = 1
  end
  $ 7 "Patterns" "noBreak"
  $ 8 "Line_Pattern_5" "noBreak"
  $ 11 "Layers" "noBreak"
  if (Pallet_4_cnt < 7):
    Pallet_4_lno = 1
    Pallet_4_lct = Pallet_4_cnt
    global StartItem_5=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.297033418747, .236015327134, .270248081440, 2.210808848390, -2.229386293156, .003317685500]))
    global EndItem_5=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.168863152256, .236015625568, .270217897295, 2.210846462943, -2.229271573491, .003306065598]))
    referencePoin_3 = interpolate_pose(StartItem_5, EndItem_5, (Pallet_4_lct - 1)/5)
    direction = p[0,0,1,0,0,0]
    referencePoin_3 = pose_add (referencePoin_3,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_p = R_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.2996507856594059,0.23616603967460775,0.2662969273431384,2.2471756963327714,-2.1905635169286577,0.0051919237216115684]), p[2.5303903356863056E-4,0.002640270352822105,-0.03990891376066347,-5.721179256762881E-6,1.0850896876343003E-4,-3.637399589660038E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_3)
  Approach_p = pose_trans(p[0.2996507856594059,0.23616603967460775,0.2662969273431384,2.247175696332654,-2.1905635169285436,0.0051919237215875364], pose_trans(pose_inv(referencePoin_3), Approach_p))
  ToolActionPoint_p = R_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.2996507856594059,0.23616603967460775,0.2662969273431384,2.2471756963327714,-2.1905635169286577,0.0051919237216115684]), p[1.0427342160532205E-4,0.002664409617871899,-0.0027554522423710037,-3.4395094588474536E-5,1.537903940366468E-5,1.0272056647417081E-4], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_3)
  ToolActionPoint_p = pose_trans(p[0.2996507856594059,0.23616603967460775,0.2662969273431384,2.247175696332654,-2.1905635169285436,0.0051919237215875364], pose_trans(pose_inv(referencePoin_3), ToolActionPoint_p))
  Exit_1_p = R_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.2996507856594059,0.23616603967460775,0.2662969273431384,2.2471756963327714,-2.1905635169286577,0.0051919237216115684]), p[2.61844728983468E-4,0.002660669080957523,-0.03353443915984855,-1.0505093211106325E-4,1.8426504836996924E-4,-1.682367682892444E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_3)
  Exit_1_p = pose_trans(p[0.2996507856594059,0.23616603967460775,0.2662969273431384,2.247175696332654,-2.1905635169285436,0.0051919237215875364], pose_trans(pose_inv(referencePoin_3), Exit_1_p))
  $ 12 "At Each Item" "noBreak"
  $ 13 "Generated Movements" "noBreak"
  $ 14 "MoveJ" "noBreak"
  $ 15 "Approach" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_3, pose_trans(p[.227183739889, .305548767090, .267407076223, -2.247175696333, 2.190563516929, -.005191923722], Approach_p)), qnear=Approach_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 16 "MoveJ" "noBreak"
  $ 17 "ToolActionPoint" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_3, pose_trans(p[.227183739889, .305548767090, .267407076223, -2.247175696333, 2.190563516929, -.005191923722], ToolActionPoint_p)), qnear=ToolActionPoint_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 18 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 19 "RG Grip" "noBreak"
on_return = rg_grip(73.0, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 20 "MoveJ" "noBreak"
  $ 21 "Exit_1" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_3, pose_trans(p[.227183739889, .305548767090, .267407076223, -2.247175696333, 2.190563516929, -.005191923722], Exit_1_p)), qnear=Exit_1_q), a=1.3962634015954636, v=1.0471975511965976)
  Pallet_4_sep = False
  if (Pallet_4_cnt >= 6):
    Pallet_4_cnt = 1
  else:
    Pallet_4_cnt = Pallet_4_cnt + 1
  end
  $ 22 "hp" "breakAfter"
  movel(hp_p, a=1.2, v=0.25)
  $ 23 "R2M"
  def R2M_trans(pose):
  return p[pose[0], pose[1], pose[2], 0, 0, 0]
  end
  def R2M_rot(pose):
  return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def R2M_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(R2M_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), R2M_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(R2M_rot(T_feature_referencePoint_taught), pose_trans(R2M_rot(T_referencePoint_approach_taught), pose_inv(R2M_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(R2M_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, R2M_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_5_tct = 6
  if (Pallet_5_cnt > 6 or Pallet_5_cnt < 1):
    Pallet_5_cnt = 1
  end
  $ 24 "Patterns" "noBreak"
  $ 25 "Line_Pattern_6" "noBreak"
  $ 28 "Line_Pattern_7" "noBreak"
  $ 31 "Layers" "noBreak"
  if (Pallet_5_cnt < 4):
    Pallet_5_lno = 1
    Pallet_5_lct = Pallet_5_cnt
    global StartItem_6=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.462498424417, .013314534124, .272846491034, -2.187661277556, 2.206084381716, -.059209120771]))
    global EndItem_6=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.407264993957, .013357651204, .272777789660, -2.186932595754, 2.204856535406, -.060909390596]))
    referencePoin_4 = interpolate_pose(StartItem_6, EndItem_6, (Pallet_5_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoin_4 = pose_add (referencePoin_4,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  elif (Pallet_5_cnt < 7):
    Pallet_5_lno = 2
    Pallet_5_lct = Pallet_5_cnt - 3
    global StartItem_7=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.448764020364, -.010902474949, .282911063554, 3.137598182711, -.000201554691, -.000200371763]))
    global EndItem_7=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.448810595476, .038813508781, .282890082662, 3.137969859039, -.000051016575, -.000321690714]))
    referencePoin_4 = interpolate_pose(StartItem_7, EndItem_7, (Pallet_5_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoin_4 = pose_add (referencePoin_4,p[1.0E-5*direction[0],1.0E-5*direction[1],1.0E-5*direction[2],0,0,0])
  end
  Approach_6_p = R2M_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.4738619713248294,0.01094800568094445,0.2696281190313883,2.247173387019771,-2.190520580229924,0.005151952022470285]), p[-0.0018564906301029485,0.0028450912632042025,-0.056712855695487174,-2.200658619845263E-4,-7.509705361195392E-5,0.022808714674944153], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_4)
  Approach_6_p = pose_trans(p[0.4738619713248294,0.01094800568094445,0.2696281190313883,2.2471733870198873,-2.1905205802300376,0.005151952022511608], pose_trans(pose_inv(referencePoin_4), Approach_6_p))
  ToolActionPoi_6_p = R2M_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.4738619713248294,0.01094800568094445,0.2696281190313883,2.247173387019771,-2.190520580229924,0.005151952022470285]), p[-0.0021791018484351183,0.002830555648328903,0.003677720919003258,-1.0580641676333753E-4,2.0094681028249306E-4,0.010271934699241123], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_4)
  ToolActionPoi_6_p = pose_trans(p[0.4738619713248294,0.01094800568094445,0.2696281190313883,2.2471733870198873,-2.1905205802300376,0.005151952022511608], pose_trans(pose_inv(referencePoin_4), ToolActionPoi_6_p))
  Exit_7_p = R2M_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.4738619713248294,0.01094800568094445,0.2696281190313883,2.247173387019771,-2.190520580229924,0.005151952022470285]), p[-0.0020638767271972448,0.0027726523927347757,-0.013621583362470269,4.74685401650623E-5,7.603984838268058E-5,-8.89465853281351E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_4)
  Exit_7_p = pose_trans(p[0.4738619713248294,0.01094800568094445,0.2696281190313883,2.2471733870198873,-2.1905205802300376,0.005151952022511608], pose_trans(pose_inv(referencePoin_4), Exit_7_p))
  $ 32 "At Each Item" "noBreak"
  $ 33 "Generated Movements" "noBreak"
  $ 34 "MoveJ" "noBreak"
  $ 35 "Approach_6" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_4, pose_trans(p[-.002428220833, .473946740727, .269690452123, -2.247173387020, 2.190520580230, -.005151952022], Approach_6_p)), qnear=Approach_6_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 36 "MoveL" "noBreak"
  $ 37 "ToolActionPoi_6" "noBreak"
  movel(pose_trans(referencePoin_4, pose_trans(p[-.002428220833, .473946740727, .269690452123, -2.247173387020, 2.190520580230, -.005151952022], ToolActionPoi_6_p)), a=1.2, v=0.25)
  $ 38 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 39 "RG Grip" "noBreak"
on_return = rg_grip(100.0, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 40 "MoveL" "noBreak"
  $ 41 "Exit_7" "noBreak"
  movel(pose_trans(referencePoin_4, pose_trans(p[-.002428220833, .473946740727, .269690452123, -2.247173387020, 2.190520580230, -.005151952022], Exit_7_p)), a=1.2, v=0.25)
  Pallet_5_sep = False
  if (Pallet_5_cnt >= 6):
    Pallet_5_cnt = 1
  else:
    Pallet_5_cnt = Pallet_5_cnt + 1
  end
  Loop_2 = Loop_2 + 1
  end
  $ 42 "hp" "breakAfter"
  movel(hp_p, a=1.2, v=0.25)
  $ 43 "MoveL"
  $ 44 "hp" "breakAfter"
  movel(hp_p, a=1.2, v=0.25)
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 45 "RG Grip"
on_return = rg_grip(100.0, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 46 "Loop 6 times"
  Loop_1 = 0
  while (Loop_1 < 6):
    $ 47 "Pallet_1"
    def Pallet_1_trans(pose):
    return p[pose[0], pose[1], pose[2], 0, 0, 0]
  end
  def Pallet_1_rot(pose):
  return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def Pallet_1_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(Pallet_1_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), Pallet_1_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(Pallet_1_rot(T_feature_referencePoint_taught), pose_trans(Pallet_1_rot(T_referencePoint_approach_taught), pose_inv(Pallet_1_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(Pallet_1_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, Pallet_1_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_1_tct = 6
  if (Pallet_1_cnt_1 > 6 or Pallet_1_cnt_1 < 1):
    Pallet_1_cnt_1 = 1
  end
  $ 48 "Patterns" "noBreak"
  $ 49 "Line_Pattern_11" "noBreak"
  $ 52 "Line_Pattern_12" "noBreak"
  $ 55 "Layers" "noBreak"
  if (Pallet_1_cnt_1 < 4):
    Pallet_1_lno = 1
    Pallet_1_lct = Pallet_1_cnt_1
    global StartItem_11=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.443448327631, -.014006188789, .279652391165, -3.141458333979, -.017996988632, -.004444130443]))
    global EndItem_11=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.442845709685, .038810157407, .279634845788, -3.141455709316, -.017943460984, -.004380416872]))
    referencePoint = interpolate_pose(StartItem_11, EndItem_11, (Pallet_1_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoint = pose_add (referencePoint,p[1.0E-5*direction[0],1.0E-5*direction[1],1.0E-5*direction[2],0,0,0])
  elif (Pallet_1_cnt_1 < 7):
    Pallet_1_lno = 2
    Pallet_1_lct = Pallet_1_cnt_1 - 3
    global StartItem_12=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.470995971305, .011989615809, .264824388200, 2.210655051110, -2.229063336812, .003442280175]))
    global EndItem_12=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.419053335611, .013219037711, .264868712135, 2.210921670170, -2.229331014722, .003320478277]))
    referencePoint = interpolate_pose(StartItem_12, EndItem_12, (Pallet_1_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoint = pose_add (referencePoint,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_5_p = Pallet_1_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.48764161325454886,0.006206234045797706,0.11644156571844112,2.228216675170024,2.206466079527706,-0.0021743290203899914]), p[0.0020134607524399176,-0.016299753312083665,-0.1577709967141637,-0.03908303941143952,-0.0030315308641454515,-3.117657552084787], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoint)
  Approach_5_p = pose_trans(p[0.48764161325454886,0.006206234045797706,0.11644156571844112,2.2282166751700236,2.206466079527706,-0.0021743290203649237], pose_trans(pose_inv(referencePoint), Approach_5_p))
  ToolActionPoi_5_p = Pallet_1_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.48764161325454886,0.006206234045797706,0.11644156571844112,2.228216675170024,2.206466079527706,-0.0021743290203899914]), p[0.0015111402795587297,-0.01620500472158476,-0.14759596191956917,-0.030224471576164258,-0.0035842950547329304,-3.1177932638642836], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoint)
  ToolActionPoi_5_p = pose_trans(p[0.48764161325454886,0.006206234045797706,0.11644156571844112,2.2282166751700236,2.206466079527706,-0.0021743290203649237], pose_trans(pose_inv(referencePoint), ToolActionPoi_5_p))
  Exit_6_p = Pallet_1_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.48764161325454886,0.006206234045797706,0.11644156571844112,2.228216675170024,2.206466079527706,-0.0021743290203899914]), p[0.002803496873397421,-0.01771943011266186,-0.17994453841425773,0.008018906356708167,0.007620060650501306,3.1316958103179986], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoint)
  Exit_6_p = pose_trans(p[0.48764161325454886,0.006206234045797706,0.11644156571844112,2.2282166751700236,2.206466079527706,-0.0021743290203649237], pose_trans(pose_inv(referencePoint), Exit_6_p))
  $ 56 "At Each Item" "noBreak"
  $ 57 "Generated Movements" "noBreak"
  $ 58 "MoveL" "noBreak"
  $ 59 "Approach_5" "noBreak"
  movel(pose_trans(referencePoint, pose_trans(p[-.010406280350, -.487917945150, .114975156776, -2.228216675170, -2.206466079528, .002174329020], Approach_5_p)), a=1.2, v=0.25)
  $ 60 "MoveL" "noBreak"
  $ 61 "ToolActionPoi_5" "noBreak"
  movel(pose_trans(referencePoint, pose_trans(p[-.010406280350, -.487917945150, .114975156776, -2.228216675170, -2.206466079528, .002174329020], ToolActionPoi_5_p)), a=1.2, v=0.25)
  $ 62 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 63 "RG Grip" "noBreak"
on_return = rg_grip(73.0, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 64 "MoveL" "noBreak"
  $ 65 "Exit_6" "noBreak"
  movel(pose_trans(referencePoint, pose_trans(p[-.010406280350, -.487917945150, .114975156776, -2.228216675170, -2.206466079528, .002174329020], Exit_6_p)), a=1.2, v=0.25)
  Pallet_1_sep = False
  if (Pallet_1_cnt_1 >= 6):
    Pallet_1_cnt_1 = 1
  else:
    Pallet_1_cnt_1 = Pallet_1_cnt_1 + 1
  end
  $ 66 "MoveL"
  $ 67 "Waypoint_2" "breakAfter"
  movel(Waypoint_2_p, a=1.2, v=0.25)
  $ 68 "Waypoint_1" "breakAfter"
  movel(Waypoint_1_p, a=1.2, v=0.25)
  $ 69 "Wait: 1.0"
  sleep(1.0)
  $ 70 "If analog_in[0]<5"
  if (get_standard_analog_in(0)<5):
    $ 71 "MoveJ"
    $ 72 "hp" "breakAfter"
    movej(get_inverse_kin(hp_p, qnear=hp_q), a=1.3962634015954636, v=1.0471975511965976)
    $ 73 "Pallet_2"
    def Pallet_2_trans(pose):
    return p[pose[0], pose[1], pose[2], 0, 0, 0]
  end
  def Pallet_2_rot(pose):
  return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def Pallet_2_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(Pallet_2_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), Pallet_2_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(Pallet_2_rot(T_feature_referencePoint_taught), pose_trans(Pallet_2_rot(T_referencePoint_approach_taught), pose_inv(Pallet_2_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(Pallet_2_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, Pallet_2_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_2_tct = 6
  if (Pallet_2_cnt > 6 or Pallet_2_cnt < 1):
    Pallet_2_cnt = 1
  end
  $ 74 "Patterns" "noBreak"
  $ 75 "Line_Pattern_2" "noBreak"
  $ 78 "Layers" "noBreak"
  if (Pallet_2_cnt < 7):
    Pallet_2_lno = 1
    Pallet_2_lct = Pallet_2_cnt
    global StartItem_2=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.171963410167, .237558178807, .272637280149, -2.200265788714, 2.218514742943, -.020628593053]))
    global EndItem_2=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.297011377890, .235313766461, .271318955672, -2.207610684079, 2.225985771876, .010100960003]))
    referencePoin_1 = interpolate_pose(StartItem_2, EndItem_2, (Pallet_2_lct - 1)/5)
    direction = p[0,0,1,0,0,0]
    referencePoin_1 = pose_add (referencePoin_1,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_1_p = Pallet_2_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.3655924077144329,0.12873232638075274,0.11883144602328854,2.228342196091278,2.2063380160380115,-0.00190743731132561]), p[0.10244207703102304,-0.19200064928177465,-0.18027821213133235,0.011675398088698207,-0.007032227236982022,3.140043683137175], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_1)
  Approach_1_p = pose_trans(p[0.3655924077144329,0.12873232638075274,0.11883144602328854,2.228342196091223,2.2063380160379573,-0.0019074373113203604], pose_trans(pose_inv(referencePoin_1), Approach_1_p))
  ToolActionPoi_1_p = Pallet_2_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.3655924077144329,0.12873232638075274,0.11883144602328854,2.228342196091278,2.2063380160380115,-0.00190743731132561]), p[0.10609750922717442,-0.1921274873390388,-0.15223172592975145,0.003803987928264092,-0.0068574170388772965,3.1400983401434455], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_1)
  ToolActionPoi_1_p = pose_trans(p[0.3655924077144329,0.12873232638075274,0.11883144602328854,2.228342196091223,2.2063380160379573,-0.0019074373113203604], pose_trans(pose_inv(referencePoin_1), ToolActionPoi_1_p))
  Exit_2_p = Pallet_2_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.3655924077144329,0.12873232638075274,0.11883144602328854,2.228342196091278,2.2063380160380115,-0.00190743731132561]), p[0.1027241921592964,-0.1900105132323025,-0.17288753503455376,-0.015870364512612225,0.006738182523376051,-3.109345503886611], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_1)
  Exit_2_p = pose_trans(p[0.3655924077144329,0.12873232638075274,0.11883144602328854,2.228342196091223,2.2063380160379573,-0.0019074373113203604], pose_trans(pose_inv(referencePoin_1), Exit_2_p))
  $ 79 "At Each Item" "noBreak"
  $ 80 "Generated Movements" "noBreak"
  $ 81 "MoveJ" "noBreak"
  $ 82 "Approach_1" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_1, pose_trans(p[-.131770826506, -.364680842518, .118300741249, -2.228342196091, -2.206338016038, .001907437311], Approach_1_p)), qnear=Approach_1_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 83 "MoveL" "noBreak"
  $ 84 "ToolActionPoi_1" "noBreak"
  movel(pose_trans(referencePoin_1, pose_trans(p[-.131770826506, -.364680842518, .118300741249, -2.228342196091, -2.206338016038, .001907437311], ToolActionPoi_1_p)), a=1.2, v=0.25)
  $ 85 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 86 "RG Grip" "noBreak"
on_return = rg_grip(100.0, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 87 "MoveL" "noBreak"
  $ 88 "Exit_2" "noBreak"
  movel(pose_trans(referencePoin_1, pose_trans(p[-.131770826506, -.364680842518, .118300741249, -2.228342196091, -2.206338016038, .001907437311], Exit_2_p)), a=1.2, v=0.25)
  Pallet_2_sep = False
  if (Pallet_2_cnt >= 6):
    Pallet_2_cnt = 1
  else:
    Pallet_2_cnt = Pallet_2_cnt + 1
  end
  else:
    $ 89 "Else" "noBreak"
    $ 90 "MoveL"
    $ 91 "hp" "breakAfter"
    movel(hp_p, a=1.2, v=0.25)
    $ 92 "Pallet_3"
    def Pallet_3_trans(pose):
    return p[pose[0], pose[1], pose[2], 0, 0, 0]
  end
  def Pallet_3_rot(pose):
  return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def Pallet_3_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(Pallet_3_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), Pallet_3_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(Pallet_3_rot(T_feature_referencePoint_taught), pose_trans(Pallet_3_rot(T_referencePoint_approach_taught), pose_inv(Pallet_3_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(Pallet_3_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, Pallet_3_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_3_tct = 6
  if (Pallet_3_cnt > 6 or Pallet_3_cnt < 1):
    Pallet_3_cnt = 1
  end
  $ 93 "Patterns" "noBreak"
  $ 94 "Line_Pattern_3" "noBreak"
  $ 97 "Layers" "noBreak"
  if (Pallet_3_cnt < 7):
    Pallet_3_lno = 1
    Pallet_3_lct = Pallet_3_cnt
    global StartItem_3=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.173324016410, -.211754342694, .270267675435, 2.228638551560, -2.212441755069, .002769422738]))
    global EndItem_3=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.299778781186, -.211741973517, .270237077971, 2.228649089429, -2.212310869989, .002462638281]))
    referencePoin_2 = interpolate_pose(StartItem_3, EndItem_3, (Pallet_3_lct - 1)/5)
    direction = p[0,0,1,0,0,0]
    referencePoin_2 = pose_add (referencePoin_2,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_2_p = Pallet_3_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.3676458444694583,-0.1293909280545595,0.11502587828448332,-2.216630689520228,-2.195354976827886,-0.0329257823341622]), p[-0.07911504750836279,-0.19361224004514627,-0.17016929668416914,-0.05048610442483482,0.001008729686679407,3.124195411004688], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_2)
  Approach_2_p = pose_trans(p[0.3676458444694583,-0.1293909280545595,0.11502587828448332,-2.216630689520228,-2.195354976827886,-0.03292578233415494], pose_trans(pose_inv(referencePoin_2), Approach_2_p))
  ToolActionPoi_2_p = Pallet_3_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.3676458444694583,-0.1293909280545595,0.11502587828448332,-2.216630689520228,-2.195354976827886,-0.0329257823341622]), p[-0.07940143603559163,-0.19360091879432528,-0.16063601842719438,-0.0504607226180918,9.81586282365755E-4,3.12420930730501], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_2)
  ToolActionPoi_2_p = pose_trans(p[0.3676458444694583,-0.1293909280545595,0.11502587828448332,-2.216630689520228,-2.195354976827886,-0.03292578233415494], pose_trans(pose_inv(referencePoin_2), ToolActionPoi_2_p))
  Exit_3_p = Pallet_3_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.3676458444694583,-0.1293909280545595,0.11502587828448332,-2.216630689520228,-2.195354976827886,-0.0329257823341622]), p[-0.07862262501128658,-0.19360342375130665,-0.1861024882701784,-0.050461136512251405,0.0010094100080279902,3.1242443482402686], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_2)
  Exit_3_p = pose_trans(p[0.3676458444694583,-0.1293909280545595,0.11502587828448332,-2.216630689520228,-2.195354976827886,-0.03292578233415494], pose_trans(pose_inv(referencePoin_2), Exit_3_p))
  $ 98 "At Each Item" "noBreak"
  $ 99 "Generated Movements" "noBreak"
  $ 100 "MoveL" "noBreak"
  $ 101 "Approach_2" "noBreak"
  movel(pose_trans(referencePoin_2, pose_trans(p[.122303008962, -.368815567665, .118968411524, 2.216630689520, 2.195354976828, .032925782334], Approach_2_p)), a=1.2, v=0.25)
  $ 102 "MoveL" "noBreak"
  $ 103 "ToolActionPoi_2" "noBreak"
  movel(pose_trans(referencePoin_2, pose_trans(p[.122303008962, -.368815567665, .118968411524, 2.216630689520, 2.195354976828, .032925782334], ToolActionPoi_2_p)), a=1.2, v=0.25)
  $ 104 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 105 "RG Grip" "noBreak"
on_return = rg_grip(100.0, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 106 "MoveL" "noBreak"
  $ 107 "Exit_3" "noBreak"
  movel(pose_trans(referencePoin_2, pose_trans(p[.122303008962, -.368815567665, .118968411524, 2.216630689520, 2.195354976828, .032925782334], Exit_3_p)), a=1.2, v=0.25)
  Pallet_3_sep = False
  if (Pallet_3_cnt >= 6):
    Pallet_3_cnt = 1
  else:
    Pallet_3_cnt = Pallet_3_cnt + 1
  end
  end
  Loop_1 = Loop_1 + 1
  end
  $ 108 "hp" "breakAfter"
  movel(hp_p, a=1.2, v=0.25)
  $ 109 "Halt"
  halt
  end
end
