  #======    OnRobot Speedl    ======#
  
  of_speedl_thread_handler=0
  of_speedl_is_enabled=False
  of_speedl_is_running=False
  of_speedbase=[0,0,0,0,0,0]
  of_speedl_acc=0
  of_speedl_hg_caranteen_reached=False
  of_speedl_hg_caranteen_safemode=False
  of_speedl_for_limit=False
  of_speedl_for_ft_control=False
  of_speedl_for_move=False
  of_speedl_for_hand_guide=False
  of_speedl_for_insert_pin=False
  of_speedl_for_gripper_set_width=False
  of_speedl_for_gripper_centering=False
  of_speedl_acc=10000.0 
  of_speedl_acc_to_zero=3.0 
  thread of_speedl_thread():
  if OF_DEBUG_STATE:
  textmsg("Speedl stream started..")
  end 
  enter_critical
  of_speedl_is_running=True
  of_speedl_is_enabled=True
  exit_critical
  of_speedbase=[0,0,0,0,0,0]
  while of_speedl_is_running:
  of_speedbase=get_of_appvect()
  if of_speedl_for_hand_guide:
  if of_speedl_hg_caranteen_reached:
  if of_speedl_hg_caranteen_safemode:
  local XYplane=get_actual_tool_flange_pose()
  if(XYplane[0]<0 and of_speedbase[0]>0)or(XYplane[0]>0 and of_speedbase[0]<0):
  of_speedbase[0]=0
  end 
  if(XYplane[1]<0 and of_speedbase[1]>0)or(XYplane[1]>0 and of_speedbase[1]<0):
  of_speedbase[1]=0
  end 
  else:
  of_speedbase=[0,0,0,0,0,0]
  end 
  end 
  end 
  if of_speedl_is_enabled:
  speedl(of_speedbase,a=of_speedl_acc,t=0.001)
  else:
  speedl([0,0,0,0,0,0],a=of_speedl_acc_to_zero,t=0.001)
  end 
  end 
  if OF_DEBUG_STATE:
  textmsg("Speedl stream ended.")
  end 
  end 
  def of_speedl_start_for_CMD(start_for_CMD):
  if(start_for_CMD==OF_CMD_LIMIT):
  of_speedl_for_limit=True
  elif(start_for_CMD==OF_CMD_FT_CONTROL):
  of_speedl_for_ft_control=True
  elif(start_for_CMD==OF_CMD_MOVE):
  of_speedl_for_move=True
  elif(start_for_CMD==OF_CMD_HAND_GUIDE):
  of_speedl_for_hand_guide=True
  elif(start_for_CMD==OF_CMD_INSERT_PIN):
  of_speedl_for_insert_pin=True
  elif(start_for_CMD==OF_CMD_GRIPPER_SET_WIDTH):
  of_speedl_for_gripper_set_width=True
  elif(start_for_CMD==OF_CMD_GRIPPER_CENTERING):
  of_speedl_for_gripper_centering=True
  else:
  textmsg("Unknown Start speedl CMD received: ",start_for_CMD)
  end 
  local speedl_integer=binary_list_to_integer([of_speedl_for_limit,of_speedl_for_ft_control,of_speedl_for_hand_guide,of_speedl_for_move,of_speedl_for_insert_pin,of_speedl_for_gripper_set_width,of_speedl_for_gripper_centering])
  if not(speedl_integer==0):
  if not of_speedl_is_running:
  of_speedl_thread_handler=run of_speedl_thread()
  end 
  end 
  return of_speedl_is_running
  end 
  def of_speedl_stop_for_CMD(stop_for_CMD,brake=10):
  if(stop_for_CMD==OF_CMD_LIMIT):
  of_speedl_for_limit=False
  elif(stop_for_CMD==OF_CMD_FT_CONTROL):
  of_speedl_for_ft_control=False
  elif(stop_for_CMD==OF_CMD_MOVE):
  of_speedl_for_move=False
  elif(stop_for_CMD==OF_CMD_HAND_GUIDE):
  of_speedl_for_hand_guide=False
  elif(stop_for_CMD==OF_CMD_INSERT_PIN):
  of_speedl_for_insert_pin=False
  elif(stop_for_CMD==OF_CMD_GRIPPER_SET_WIDTH):
  of_speedl_for_gripper_set_width=False
  elif(stop_for_CMD==OF_CMD_GRIPPER_CENTERING):
  of_speedl_for_gripper_centering=False
  else:
  textmsg("Unknown Stop speedl CMD received: ",stop_for_CMD)
  end 
  local speedl_integer=binary_list_to_integer([of_speedl_for_limit,of_speedl_for_ft_control,of_speedl_for_hand_guide,of_speedl_for_move,of_speedl_for_insert_pin,of_speedl_for_gripper_set_width,of_speedl_for_gripper_centering])
  if(speedl_integer==0):
  kill of_speedl_thread_handler
  enter_critical
  of_speedl_is_running=False
  exit_critical
  if OF_DEBUG_STATE:
  textmsg("Speedl stream stopped")
  end 
  stopl(brake)
  end 
  return of_speedl_is_running
  end 
  
  
  #======    End of OnRobot Speedl    ======#
