def grpB222():
  set_tool_communication(True, 1000000, 2, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(24)
  step_count_65039403_9bb0_4e39_987a_3eb88a1e0481 = 0.0
  thread Step_Counter_Thread_3b649fb8_2f2f_4f6f_a632_3f7f340aab8c():
    while (True):
      step_count_65039403_9bb0_4e39_987a_3eb88a1e0481 = step_count_65039403_9bb0_4e39_987a_3eb88a1e0481 + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_3b649fb8_2f2f_4f6f_a632_3f7f340aab8c()
  set_target_payload(1.070000, [0.002000, 0.003000, 0.057000], [0.001723, 0.001723, 0.001723, 0.000000, 0.000000, 0.000000])
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_gravity([0.0, 0.0, 9.82])
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_safety_mode_transition_hardness(1)
  global B1empty=False
  global A2Empty=0
  global A1Empty=0
  global B2Empty=False
  global pallet_step=0
  global bright_box=0
  global Pallet_1_cnt=2
  global dark_boxes=0
  global Point_1=p[0.6913645118948067,-0.12399382748223003,0.49223711947071,-1.2983729986843258,1.1259514972191385,-1.2203503861141718]
  global referencePoin_1=p[0.48495785704999833,0.009632097732523529,0.2683733122601669,2.2342174598175246,-2.1886002447867967,-0.024602472595921344]
  global referencePoin_2=p[0.2314612243898091,0.23667738567998564,0.26637182886507205,2.234349404124065,-2.188413039780224,-0.02441526098344384]
  global referencePoin_3=p[0.44730669700166137,-0.020806760417117386,0.28415052390196704,7.591243583087015E-5,3.1329016644813947,0.03411921466967655]
  global referencePoin_4=p[0.28419762524861225,0.24393418865565097,0.26723322157501056,2.1774047816749937,-2.2603486689658716,0.07027164031923824]
  global referencePoin_5=p[0.45112556212727756,0.029446302098062132,0.2627518661225257,0.04277753130003624,3.138451806196285,0.06448548807705987]
  global referencePoin_6=p[0.28640468532845853,-0.20578567759056574,0.2672246206895357,2.177405596580439,-2.260347723500142,0.07032064822259228]
  global referencePoint=p[0.3066407646125005,0.23665602835080357,0.2628303736863845,2.2343665974248883,-2.1885255464110065,-0.024466520317326636]
  global separatorPoin_1=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global separatorPoin_2=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global separatorPoin_3=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global separatorPoin_4=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global separatorPoin_5=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global separatorPoin_6=p[0.0,0.0,0.0,0.0,0.0,0.0]
  global separatorPoint=p[0.0,0.0,0.0,0.0,0.0,0.0]
  # begin: URCap Installation Node
  #   Source: External Control, 1.0.5, FZI Research Center for Information Technology
  #   Type: External Control
  # end: URCap Installation Node
  # begin: URCap Installation Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: OnRobot Setup
  sleep(1)
  if (False):
    global rg_Busy = 0
    global rg_Depth = 0
    global rg_DepthRel = 0
    global rg_Grip_detected = 0
    global rg_Width = 0
  end
  ON_CONN_SHIFT_BOOL = 64
  ON_CONN_SHIFT_INT = 24
  ON_CONN_SHIFT_FLOAT = 24
  ON_CONN_REG_SUM_BOOL = 7
  ON_CONN_REG_SUM_INT = 4
  ON_CONN_REG_SUM_FLOAT = 3
  ON_TOOL_SHIFT_BOOL = 64
  ON_TOOL_SHIFT_INT = 25
  ON_TOOL_SHIFT_FLOAT = 24
  ON_TOOL_SHIFT_BOOL_ARR = [64, 71, 71]
  ON_TOOL_SHIFT_INT_ARR = [25, 28, 28]
  ON_TOOL_SHIFT_FLOAT_ARR = [24, 27, 27]
  ON_TOOL_REG_SUM_BOOL = 7
  ON_TOOL_REG_SUM_INT = 3
  ON_TOOL_REG_SUM_FLOAT = 3
  ON_REGISTERS_SPEEDL_FLOAT = 0
  ON_REG_USE_TOOL = False
  ON_DI_SINGLE = 0
  ON_DI_PRIMARY = 1
  ON_DI_SECONDARY = 2
  ON_DI_DUAL = 3
  on_robot_type = 10
  on_robot_cycle = 2.0
  on_conn_ip = "localhost"
  on_tool_ip = "localhost"
  on_device_socket_port = 51234
  on_conn_xmlrpc = rpc_factory("xmlrpc", "http://localhost:41414")
  on_tool_xmlrpc = rpc_factory("xmlrpc", "http://localhost:41414")
  on_RPC = rpc_factory("xmlrpc", "http://127.0.0.1:31416")
  ON_DEBUG_LOG = False
  on_isMetric = True
  on_toolConnector = True
  on_ioqc = False
  on_dual = False
  on_computebox = False
  on_devices = 1
  on_gripper = [False, False, False]
  on_custom_tcp_id = "none"
  on_custom_tcp_enabled = False
  speedlTime = 0.001
  on_ft = False
  rg_index = 0
  on_gripper[rg_index] = True
  #======    OnRobot Globals    ======#
  
  ON_MATH_PI=3.141593
  ON_ZEROPOSE=p[0.0,0.0,0.0,0.0,0.0,0.0]
  ON_ZEROFRAME=p[0.0,0.0,0.0,0.0,0.0,0.0]
  ON_ZERO3D=[0.0,0.0,0.0]
  ON_ZERO6D=[0.0,0.0,0.0,0.0,0.0,0.0]
  ON_ZERO8D=[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
  ON_FALSE3D=[False,False,False]
  ON_FALSE6D=[False,False,False,False,False,False]
  ON_FALSE8D=[False,False,False,False,False,False,False,False]
  global on_return=0
  on_speedL=ON_ZERO6D
  on_speedBase=ON_ZERO6D
  on_speedVect=ON_ZERO6D
  on_speedExtra=ON_ZERO6D
  on_speedCB=ON_ZERO6D
  on_speedGecko=ON_ZERO6D
  on_RTDE_error=0
  on_RTDE_tool_error=0
  on_dataProcess_thrd=0
  ON_DEVICE_ID_MISSING=0
  ON_INIT_WATCHDOG_HZ=5
  ON_INIT_TIMEOUT=2000
  on_robot_TCP_offset=ON_ZEROFRAME
  on_tcp_offset_actual=ON_ZEROFRAME
  on_cog_actual=ON_ZEROFRAME
  on_mass_actual=0.0
  on_robot_mount=[0.0,0.0]
  
  #======    End of OnRobot Globals    ======#
  #======    OnRobot RG Globals    ======#
  
  RG_DEVICE_ID_RG2=32
  RG_DEVICE_ID_RG6=33
  if ON_DEBUG_LOG:
  textmsg("RG Dual: False, Index: ",rg_index)
  if False:
  rg_index=-1
  end 
  end 
  rg_Width_arr=[0,0,0]
  rg_Depth_arr=[0,0,0]
  rg_DepthRel_arr=[0,0,0]
  rg_product_code_arr=[0,0,0]
  rg_device_id_arr=[0,0,0]
  rg_Status_arr=[0,0,0]
  rg_Grip_detected_arr=[False,False,False]
  rg_Busy_arr=[False,False,False]
  rg_S1_pushed_arr=[False,False,False]
  rg_S1_triggered_arr=[False,False,False]
  rg_S2_pushed_arr=[False,False,False]
  rg_S2_triggered_arr=[False,False,False]
  rg_Safety_error_arr=[False,False,False]
  rg_Speed_arr=[0,0,0]
  rg_Angle_arr=[0,0,0]
  rg_Angle_speed_arr=[0,0,0]
  rg_Depth_prev_arr=[0,0,0]
  rg_speedDC=ON_ZERO6D
  rg_data_error_arr=[0,0,0]
  rg_mounting_angle_arr=[0,0,0]
  rg_fingertip_arr=[0,0,0]
  rg_Grip_guard_arr=[False,False,False]
  
  rg_Width=0
  rg_Depth=0
  rg_DepthRel=0
  rg_Busy=False
  rg_Grip_detected=False
  def get_rg_Width():
  return rg_Width
  end 
  def get_rg_Depth():
  return rg_Depth
  end 
  def get_rg_DepthRel():
  return rg_DepthRel
  end 
  def get_rg_Busy():
  return rg_Busy
  end 
  def get_rg_Grip_detected():
  return rg_Grip_detected
  end 
  
  rg2_mount_bracket_offset=35.0/1000.0
  rg2_mount_body_offset=p[0.0,0.0,0.180,0.0,0.0,0.0]
  rg2_mount_cog_offset=p[0.0,0.0,0.065,0.0,0.0,0.0]
  rg6_mount_bracket_offset=35.0/1000.0
  rg6_mount_body_offset=p[0.0,0.0,0.230,0.0,0.0,0.0]
  rg6_mount_cog_offset=p[0.0,0.0,0.080,0.0,0.0,0.0]
  
  #======    End of OnRobot RG Globals    ======#
  #======    OnRobot Interface Messages    ======#
  
  on_devices_primary_log="OnRobot Devices"
  on_devices_secondary_log="OnRobot Secondary Device"
  on_program_halted="<br>Program halted."
  on_device_error_title="OnRobot - Device error"
  on_install_error="OnRobot Setup is not correct.<br>Check the status in the OnRobot Setup page in the Installation Tab.<br>Program halted."
  on_device_missing="No device connected.<br>Program halted."
  cb_device_missing="No OnRobot Compute Box connected.<br>Program halted."
  ft_device_missing="No OnRobot FT sensor or license detected.<br>Program halted."
  hex_device_missing="No HEX sensor connected.<br>Program halted."
  rg2ft_device_missing="No RG2-FT gripper connected.<br>Program halted."
  rg_device_missing="No RG gripper connected.<br>Program halted."
  vg_device_missing="No VG gripper connected.<br>Program halted."
  gg_device_missing="No Gecko Gripper connected.<br>Program halted."
  sg_device_missing="No Soft Gripper connected.<br>Program halted."
  tfg_device_missing="No 3FG gripper connected.<br>Program halted."
  sdr_device_missing="No OnRobot Sander connected.<br>Program halted."
  twofg_device_missing="No 2FG gripper connected.<br>Program halted."
  vgp_device_missing="No VGP gripper connected.<br>Program halted."
  mg_device_missing="No Magnetic Gripper connected.<br>Program halted."
  fgp_device_missing="No 2FGP20 Gripper connected.<br>Program halted."
  eyes_device_missing="No OnRobot Eyes connected.<br>Program halted."
  on_xmlrpc_start_ip="Connecting to OnRobot XML-RPC Server:"
  on_java_comm_error_textmsg_title="OnRobot - Communication error:"
  on_java_comm_controlsocket_open_error="Socket 'javaSocket' opening was unsuccessful."
  on_java_comm_error_title="OnRobot - Communication error"
  on_java_comm_socket_open_error="Establishing connection with the URCap was timed out.<br>Check the status in the OnRobot Setup page in the Installation Tab.<br>Program halted."
  on_rtde_feed_error_textmsg_title="OnRobot - RTDE error:"
  on_rtde_feed_error="RTDE feed error. OnRobot device count mismatch.<br>Program halted."
  on_rtde_feed_tool_error="Tool RTDE feed error. OnRobot device count mismatch.<br>Program halted."
  on_rtde_feed_open_error_textmsg="Socket 'rtdeFeed' opening was unsuccessful."
  on_rtde_feed_error_title="OnRobot - RTDE error"
  on_rtde_feed_count_error="Invalid RTDE offset setup detected. Please check RTDE Offsets at the OnRobot Setup page in the Installation Tab.<br>Program halted."
  on_rtde_feed_open_error="Establishing connection with the devices was timed out.<br>Ensure that the OnRobot devices are operational, and check the status in the OnRobot Setup page in the Installation Tab."
  
  #======    End of OnRobot Interface Messages    ======#
  #======    OnRobot Interface    ======#
  
  on_portopened_javaSocket=False
  on_rtde_feed_opened=False
  on_dataProcess_running=False
  def on_missing():
  popup(on_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def cb_missing():
  popup(cb_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def ft_missing():
  popup(ft_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def hex_missing():
  popup(hex_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def rg2ft_missing():
  popup(rg2ft_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def rg_missing():
  popup(rg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def vg_missing():
  popup(vg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def gg_missing():
  popup(gg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def sg_missing():
  popup(sg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def tfg_missing():
  popup(tfg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def sdr_missing():
  popup(sdr_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def twofg_missing():
  popup(twofg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def vgp_missing():
  popup(vgp_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def mg_missing():
  popup(mg_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def fgp_missing():
  popup(fgp_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def eyes_missing():
  popup(eyes_device_missing,title=on_device_error_title,error=True,blocking=False)
  halt
  end 
  def on_portclose_javaSocket():
  socket_close("javaSocket")
  on_portopened_javaSocket=False
  end 
  def on_portopen_javaSocket():
  on_portclose_javaSocket()
  on_portopened_javaSocket=socket_open("127.0.0.1",44005,"javaSocket")
  if not on_portopened_javaSocket:
  textmsg(on_java_comm_error_textmsg_title,on_java_comm_controlsocket_open_error)
  popup(on_java_comm_socket_open_error,title=on_java_comm_error_title,error=True,blocking=False)
  halt
  end 
  end 
  on_conn_rtde_feed_name="rtdeFeedConn"
  on_tool_rtde_feed_name="rtdeFeedTool"
  def on_rtde_feed_close(rtdeFeedName):
  socket_close(rtdeFeedName)
  on_rtde_feed_opened=False
  end 
  def on_rtde_feed_open(deviceIP,rtdeFeedName,regStart,regSum,regSpeedl):
  on_rtde_feed_close(rtdeFeedName)
  if((regStart[0]+regSum[0])>128)or((regStart[1]+regSum[1])>48)or((regStart[2]+regSum[2])>48):
  popup(on_rtde_feed_count_error,title=on_rtde_feed_error_title,error=True,blocking=False)
  textmsg(str_cat("RegStart: ",regStart),str_cat("  -  RegSum: ",regSum))
  halt
  end 
  on_rtde_feed_opened=socket_open(deviceIP,on_device_socket_port,rtdeFeedName)
  if not on_rtde_feed_opened:
  on_rtde_feed_opened=socket_open(deviceIP,on_device_socket_port,rtdeFeedName)
  end 
  if not on_rtde_feed_opened:
  textmsg(on_rtde_feed_error_textmsg_title,on_rtde_feed_open_error_textmsg)
  popup(on_rtde_feed_open_error,title=on_rtde_feed_error_title,error=True,blocking=False)
  halt
  end 
  socket_send_int(regStart[0],rtdeFeedName)
  socket_send_int(regSum[0],rtdeFeedName)
  socket_send_int(regStart[1],rtdeFeedName)
  socket_send_int(regSum[1],rtdeFeedName)
  socket_send_int(regStart[2],rtdeFeedName)
  socket_send_int(regSum[2],rtdeFeedName)
  socket_send_int(regSpeedl,rtdeFeedName)
  socket_send_int(on_devices,rtdeFeedName)
  end 
  def on_dataRead():
  enter_critical
  on_RTDE_error=read_input_integer_register(ON_CONN_SHIFT_INT)
  if(ON_REG_USE_TOOL):
  on_RTDE_tool_error=read_input_integer_register(ON_TOOL_SHIFT_INT_ARR[0])
  end
  exit_critical
  end 
  def on_set_rtde_watchdog(updateHz=ON_INIT_WATCHDOG_HZ):
  local effect="stop"
  if(updateHz<1):
  effect="ignore"
  end 
  watchdog_conn_reg_str=str_cat("input_int_register_",ON_CONN_SHIFT_INT)
  rtde_set_watchdog(watchdog_conn_reg_str,updateHz,effect)
  if(ON_REG_USE_TOOL):
  watchdog_tool_reg_str=str_cat("input_int_register_",ON_TOOL_SHIFT_INT_ARR[0])
  rtde_set_watchdog(watchdog_tool_reg_str,updateHz,effect)
  end 
  if ON_DEBUG_LOG:
  local update_str=str_cat(" "+effect+" watchdog set to [Hz]: ",updateHz)
  textmsg(watchdog_conn_reg_str,update_str)
  if(ON_REG_USE_TOOL):
  local update_str=str_cat(" "+effect+" watchdog set to [Hz]: ",updateHz)
  textmsg(watchdog_tool_reg_str,update_str)
  end 
  end 
  end 
  def on_speedCB_get():
  return[on_speedCB[0],on_speedCB[1],on_speedCB[2],on_speedCB[3],on_speedCB[4],on_speedCB[5]]
  end 
  def on_speedGecko_get():
  local speedExtra=ON_ZERO6D
  if on_speedl_for_gecko:
  speedExtra=[on_speedGecko[0],on_speedGecko[1],on_speedGecko[2],on_speedGecko[3],on_speedGecko[4],on_speedGecko[5]]
  end 
  return speedExtra
  end 
  def on_speedGecko_set(speedGecko):
  on_speedGecko=[speedGecko[0],speedGecko[1],speedGecko[2],speedGecko[3],speedGecko[4],speedGecko[5]]
  end 
  thread on_dataProcess_thread():
  if ON_DEBUG_LOG:
  textmsg("Starting on_dataRead thread")
  end 
  local error=False
  on_dataProcess_running=True
  sync()
  while on_dataProcess_running:
  sync()
  on_dataRead()
  error=on_error((on_RTDE_error<0),on_rtde_feed_error,on_rtde_feed_error_title,error)
  error=on_error((ON_REG_USE_TOOL and(on_RTDE_tool_error<0)),on_rtde_feed_tool_error,on_rtde_feed_error_title,error)
  on_dataProcess_running=not error
  end 
  if error:
  halt
  end 
  if ON_DEBUG_LOG:
  textmsg("Stopping on_dataRead thread")
  end 
  end 
  thread on_set_watchdog_thread():
  sleep(2)
  on_set_rtde_watchdog(updateHz=ON_INIT_WATCHDOG_HZ)
  sleep(1/ON_INIT_WATCHDOG_HZ)
  on_dataProcess_running=False
  kill on_dataProcess_thrd
  end 
  
  #======    End of OnRobot Interface    ======#
  #======    OnRobot QC Setup Tool Connector    ======#
  
  def tc_setup_tool():
  if ON_DEBUG_LOG:
  textmsg("QC Setup Tool Connector start...")
  end 
  set_tool_voltage(24)
  
  set_tool_communication(True,1000000,2,1,1.5,3.5)
  
  if ON_DEBUG_LOG:
  textmsg("QC Setup Tool Connector end.")
  end 
  end 
  
  #======    End of OnRobot QC Setup Tool Connector    ======#
  #======    OnRobot RG Interface    ======#
  
  rg_dataRead_running=False
  def rg_dataRead_RTDE(tool_index):
  local reg_offset_bool=ON_TOOL_SHIFT_BOOL_ARR[tool_index]
  local reg_offset_int=ON_TOOL_SHIFT_INT_ARR[tool_index]
  local reg_offset_float=ON_TOOL_SHIFT_FLOAT_ARR[tool_index]
  enter_critical
  floatRegDummy=read_input_float_register(reg_offset_float+0)
  rg_Width_arr[tool_index]=floatRegDummy
  floatRegDummy=read_input_float_register(reg_offset_float+1)
  rg_Depth_arr[tool_index]=floatRegDummy
  floatRegDummy=read_input_float_register(reg_offset_float+2)
  rg_DepthRel_arr[tool_index]=floatRegDummy
  intRegDummy=read_input_integer_register(reg_offset_int+0)
  rg_device_id_arr[tool_index]=intRegDummy
  intRegDummy=read_input_integer_register(reg_offset_int+1)
  rg_product_code_arr[tool_index]=intRegDummy
  intRegDummy=read_input_integer_register(reg_offset_int+2)
  rg_Status_arr[tool_index]=intRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+0)
  rg_Busy_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+1)
  rg_Grip_detected_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+2)
  rg_S1_pushed_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+3)
  rg_S1_triggered_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+4)
  rg_S2_pushed_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+5)
  rg_S2_triggered_arr[tool_index]=boolRegDummy
  boolRegDummy=read_input_boolean_register(reg_offset_bool+6)
  rg_Safety_error_arr[tool_index]=boolRegDummy
  exit_critical
  end 
  thread rg_dataRead_thread():
  if ON_DEBUG_LOG:
  textmsg("Starting rg_dataRead thread")
  end 
  while rg_dataRead_running:
  sync()
  rg_Depth_prev_arr=rg_Depth_arr
  if(rg_index==ON_DI_DUAL):
  rg_dataRead_RTDE(ON_DI_PRIMARY)
  rg_dataRead_RTDE(ON_DI_SECONDARY)
  else:
  rg_dataRead_RTDE(rg_index)
  end 
  end 
  if ON_DEBUG_LOG:
  textmsg("Stopping rg_dataRead thread")
  end 
  end 
  
  #======    End of OnRobot RG Interface    ======#
  #======    OnRobot TCP Messages    ======#
  
  on_tcp_log_msg_default="OnRobot: Robot TCP Offset set to:"
  on_tcp_log_msg_primary="OnRobot: Robot TCP Offset set to Primary:"
  on_tcp_log_msg_secondary="OnRobot: Robot TCP Offset set to Secondary:"
  
  #======    End of OnRobot TCP Messages    ======#
  #======    OnRobot TCP    ======#
  
  on_tcp_offset_actual=ON_ZEROFRAME
  on_tcp_offset_primary=ON_ZEROFRAME
  on_tcp_static_primary=ON_ZEROFRAME
  on_tcp_dynamic_primary=ON_ZEROFRAME
  on_tcp_adapters=ON_ZEROFRAME
  on_tcp_qc_primary=ON_ZEROFRAME
  on_tcp_base_primary=ON_ZEROFRAME
  on_tcp_gripper_static_primary=ON_ZEROFRAME
  on_tcp_workpiece_primary=ON_ZEROFRAME
  on_tcp_gripper_dynamic_primary=ON_ZEROFRAME
  on_tcp_gripper_primary=ON_ZEROFRAME
  on_tcp_offset_secondary=ON_ZEROFRAME
  on_tcp_static_secondary=ON_ZEROFRAME
  on_tcp_dynamic_secondary=ON_ZEROFRAME
  on_tcp_qc_secondary=ON_ZEROFRAME
  on_tcp_base_secondary=ON_ZEROFRAME
  on_tcp_gripper_static_secondary=ON_ZEROFRAME
  on_tcp_workpiece_secondary=ON_ZEROFRAME
  on_tcp_gripper_dynamic_secondary=ON_ZEROFRAME
  on_tcp_gripper_secondary=ON_ZEROFRAME
  on_tcp_custom_preset_assigned=False
  on_tcp_custom_preset=ON_ZEROFRAME
  def on_tcp_init_adapters():
  if ON_DEBUG_LOG:
  textmsg("TCP Init Adapters start..")
  end 
  enter_critical
  on_tcp_adapters=ON_ZEROFRAME
  local adapterCount=length(on_tcp_adapters_array)
  local i=0
  while(i<adapterCount):
  on_tcp_adapters=pose_trans(on_tcp_adapters,on_tcp_adapters_array[i])
  i=i+1
  end
  exit_critical
  if ON_DEBUG_LOG:
  textmsg("TCP Init Adapters end.")
  end 
  end 
  def on_tcp_update_primary():
  if ON_DEBUG_LOG:
  textmsg("TCP Update Primary start..")
  end 
  on_tcp_gripper_dynamic_primary=p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  enter_critical
  on_tcp_dynamic_primary=pose_trans(on_tcp_static_primary,on_tcp_gripper_dynamic_primary)
  on_tcp_offset_primary=pose_trans(on_tcp_dynamic_primary,on_tcp_workpiece_primary)
  exit_critical
  if ON_DEBUG_LOG:
  textmsg("TCP Update Primary end.")
  end 
  end 
  def on_tcp_init_primary():
  if ON_DEBUG_LOG:
  textmsg("TCP Init Primary start..")
  end 
  enter_critical
  on_tcp_base_primary=pose_trans(on_tcp_adapters,on_tcp_qc_primary)
  on_tcp_static_primary=pose_trans(on_tcp_base_primary,on_tcp_gripper_static_primary)
  exit_critical
  on_tcp_update_primary()
  if ON_DEBUG_LOG:
  textmsg("TCP Init Primary end.")
  end 
  end 
  def on_tcp_offset_set(TCP_offset):
  if ON_DEBUG_LOG:
  textmsg("TCP Offset set started!")
  end 
  on_tcp_offset_send(TCP_offset)
  if(on_follow_tcp):
  set_tcp(TCP_offset)
  end 
  on_robot_TCP_offset=TCP_offset
  if ON_DEBUG_LOG:
  textmsg("TCP Offset set to: ",on_robot_TCP_offset)
  end 
  end 
  def on_tcp_offset_forced_set_actual(isPrimary=True):
  if(not on_follow_tcp):
  
  local tcp_log_msg=on_tcp_log_msg_default
  
  textmsg(tcp_log_msg,on_tcp_offset_actual)
  set_tcp(on_tcp_offset_actual)
  end 
  end 
  def on_tcp_update(isPrimary=True):
  on_tcp_update_primary()
  
  on_tcp_set_actual_to(isPrimary)
  end 
  def on_tcp_set_actual_to(isPrimary=True):
  
  on_tcp_offset_actual=on_tcp_offset_primary
  if(on_follow_tcp):
  textmsg(on_tcp_log_msg_default,on_tcp_offset_actual)
  end 
  
  on_tcp_active_is_primary=isPrimary
  on_tcp_offset_set(on_tcp_offset_actual)
  end 
  def on_tcp_update_workpiece_primary(workpiece_offset):
  if ON_DEBUG_LOG:
  textmsg("TCP Update Tool Primary start..")
  end 
  on_tcp_workpiece_primary=workpiece_offset
  on_tcp_update_primary()
  if ON_DEBUG_LOG:
  textmsg("TCP Update Tool Primary end.")
  end 
  end 
  def on_tcp_workpiece_rpy_get(xyz=[0.0,0.0,0.0],rpy=[0.0,0.0,0.0]):
  local rotvec=rpy2rotvec(rpy)
  local workpiece_offset=p[xyz[0],xyz[1],xyz[2],rotvec[0],rotvec[1],rotvec[2]]
  return workpiece_offset
  end 
  
  def on_tcp_update_workpiece(workpiece_offset,tool_index=0):
  if ON_DEBUG_LOG:
  textmsg("TCP Update Tool start..")
  end 
  if(tool_index!=ON_DI_SECONDARY):
  on_tcp_update_workpiece_primary(workpiece_offset)
  local isPrimary=True
  
  end 
  on_tcp_set_actual_to(isPrimary)
  if ON_DEBUG_LOG:
  textmsg("TCP Update Tool end.")
  end 
  end 
  def on_get_tcp_for(tool_index):
  if tool_index==ON_DI_SECONDARY:
  local actual_tcp=on_tcp_static_secondary
  else:
  local actual_tcp=on_tcp_static_primary
  end 
  return actual_tcp
  end 
  def on_tcp_custom_unused():
  return ON_ZEROFRAME
  end 
  def on_tcp_update_custom():
  if ON_DEBUG_LOG:
  textmsg("TCP Update Custom start..")
  end 
  if(on_custom_tcp_enabled):
  on_tcp_custom_unused()
  on_tcp_custom_unused()
  on_tcp_custom_unused()
  on_tcp_custom_unused()
  
  end 
  if ON_DEBUG_LOG:
  textmsg("TCP Update Custom end.")
  end 
  end 
  
  #======    End of OnRobot TCP    ======#
  #======    OnRobot Payload Messages    ======#
  
  on_mass_log_msg="OnRobot: Robot Payload Mass set to:"
  on_cog_log_msg="OnRobot: Robot Payload Center of Gravity set to:"
  
  #======    End of OnRobot Payload Messages    ======#
  #======    OnRobot Payload    ======#
  
  on_cog_actual=ON_ZEROFRAME
  on_mass_actual=0.0
  on_cog_primary=ON_ZEROFRAME
  on_cog_L1L2_primary=ON_ZEROFRAME
  on_mass_primary=0.0
  on_mass_L1L2_primary=0.0
  on_cog_adapters=ON_ZEROFRAME
  on_cog_qc_primary=ON_ZEROFRAME
  on_cog_base_primary=ON_ZEROFRAME
  on_cog_gripper_primary=ON_ZEROFRAME
  on_cog_workpiece_primary=ON_ZEROFRAME
  on_mass_adapters=0.0
  on_mass_qc_primary=0.0
  on_mass_base_primary=0.0
  on_mass_gripper_primary=0.0
  on_mass_workpiece_primary=0.0
  on_cog_secondary=ON_ZEROFRAME
  on_mass_secondary=0.0
  on_cog_gripper_secondary=ON_ZEROFRAME
  on_mass_gripper_secondary=0.0
  on_cog_workpiece_secondary=ON_ZEROFRAME
  on_mass_workpiece_secondary=0.0
  ON_LB2KG001=0.45359237/100
  def on_payload_init_adapters():
  if ON_DEBUG_LOG:
  textmsg("TCP Init Adapters start..")
  end 
  enter_critical
  on_cog_adapters=ON_ZEROFRAME
  on_mass_adapters=0.0
  local massLAL0Ratio=0
  local adapterAbsCOG=ON_ZEROFRAME
  local tcp_adapter_offset=ON_ZEROFRAME
  local adapterCount=length(on_tcp_adapters_array)
  local i=0
  while(i<adapterCount):
  on_mass_adapters=on_mass_adapters+on_mass_adapters_array[i]
  if(on_mass_adapters<=0):
  massLAL0Ratio=0
  else:
  massLAL0Ratio=on_mass_adapters_array[i]/on_mass_adapters
  end
  adapterAbsCOG=pose_trans(tcp_adapter_offset,on_tcp_adapters_array[i])
  adapterAbsCOG=p[adapterAbsCOG[0],adapterAbsCOG[1],adapterAbsCOG[2],0.0,0.0,0.0]
  on_cog_adapters=interpolate_pose(on_cog_adapters,adapterAbsCOG,massLAL0Ratio)
  on_cog_adapters=p[on_cog_adapters[0],on_cog_adapters[1],on_cog_adapters[2],0.0,0.0,0.0]
  tcp_adapter_offset=pose_trans(tcp_adapter_offset,on_tcp_adapters_array[i])
  i=i+1
  sync()
  end
  exit_critical
  if ON_DEBUG_LOG:
  textmsg("TCP Init Adapters end.")
  end 
  end 
  def on_payload_update_primary():
  if ON_DEBUG_LOG:
  textmsg("Payload Update Primary start..")
  end 
  enter_critical
  on_mass_primary=on_mass_L1L2_primary+on_mass_workpiece_primary
  local massL1L2L3Ratio=on_mass_workpiece_primary/on_mass_primary
  local workpieceAbsCOG=pose_trans(on_tcp_dynamic_primary,on_cog_workpiece_primary)
  workpieceAbsCOG=p[workpieceAbsCOG[0],workpieceAbsCOG[1],workpieceAbsCOG[2],0.0,0.0,0.0]
  on_cog_primary=interpolate_pose(on_cog_L1L2_primary,workpieceAbsCOG,massL1L2L3Ratio)
  on_cog_primary=p[on_cog_primary[0],on_cog_primary[1],on_cog_primary[2],0.0,0.0,0.0]
  exit_critical
  if ON_DEBUG_LOG:
  textmsg("Payload Update Primary end.")
  end 
  end 
  def on_payload_init_primary():
  if ON_DEBUG_LOG:
  textmsg("Payload Init Primary start..")
  end 
  enter_critical
  on_mass_base_primary=on_mass_adapters+on_mass_qc_primary
  local massL0L1Ratio=on_mass_qc_primary/on_mass_base_primary
  on_mass_L1L2_primary=on_mass_base_primary+on_mass_gripper_primary
  local massL1L2Ratio=on_mass_gripper_primary/on_mass_L1L2_primary
  local qcAbsCOG=pose_trans(on_tcp_adapters,on_cog_qc_primary)
  qcAbsCOG=p[qcAbsCOG[0],qcAbsCOG[1],qcAbsCOG[2],0.0,0.0,0.0]
  on_cog_base_primary=interpolate_pose(on_cog_adapters,qcAbsCOG,massL0L1Ratio)
  on_cog_base_primary=p[on_cog_base_primary[0],on_cog_base_primary[1],on_cog_base_primary[2],0.0,0.0,0.0]
  local gripperAbsCOG=pose_trans(on_tcp_base_primary,on_cog_gripper_primary)
  gripperAbsCOG=p[gripperAbsCOG[0],gripperAbsCOG[1],gripperAbsCOG[2],0.0,0.0,0.0]
  on_cog_L1L2_primary=interpolate_pose(on_cog_base_primary,gripperAbsCOG,massL1L2Ratio)
  on_cog_L1L2_primary=p[on_cog_L1L2_primary[0],on_cog_L1L2_primary[1],on_cog_L1L2_primary[2],0.0,0.0,0.0]
  exit_critical
  on_payload_update_primary()
  if ON_DEBUG_LOG:
  textmsg("Payload Init Primary end.")
  end 
  end 
  def on_payload_update():
  on_payload_update_primary()
  
  on_mass_actual =on_mass_primary
  on_cog_actual=on_cog_primary
  
  on_payload_set_actual()
  end 
  def on_payload_set_actual():
  
  on_mass_actual =on_mass_primary
  on_cog_actual=on_cog_primary
  
  local CoG=[on_cog_actual[0],on_cog_actual[1],on_cog_actual[2]]
  on_payload_set(on_mass_actual,CoG)
  end 
  def on_payload_update_workpiece_primary(workpiece_mass=0,workpiece_cog=[0.0,0.0,0.0]):
  if ON_DEBUG_LOG:
  textmsg("Payload Update Workpiece Primary start..")
  end 
  on_cog_workpiece_primary=p[workpiece_cog[0],workpiece_cog[1],workpiece_cog[2],0.0,0.0,0.0]
  on_mass_workpiece_primary=workpiece_mass
  on_payload_update_primary()
  if ON_DEBUG_LOG:
  textmsg("Payload Update Workpiece Primary end.")
  end 
  end 
  def on_payload_set(mass,CoG):
  if ON_DEBUG_LOG:
  textmsg("Payload set started!")
  end 
  local center_of_gravity=[CoG[0],CoG[1],CoG[2]]
  on_payload_send(center_of_gravity,mass)
  if(on_isMetric):
  local roundedMass=floor(mass*100+0.5)/100
  else:
  local roundedMass=floor(mass/ON_LB2KG001+0.5)*ON_LB2KG001
  end 
  set_payload(roundedMass,center_of_gravity)
  on_mass_actual=roundedMass
  on_cog_actual=p[CoG[0],CoG[1],CoG[2],0.0,0.0,0.0]
  if ON_DEBUG_LOG:
  textmsg("Payload mass, CoG set to: ",str_cat(str_cat(mass,", "),CoG))
  end 
  end 
  
  def on_payload_update_secondary():
  end 
  def on_payload_init_secondary():
  end 
  
  def on_payload_update_workpiece(workpiece_mass,workpiece_cog=[0.0,0.0,0.0],tool_index=0):
  if ON_DEBUG_LOG:
  textmsg("Payload Update Workpiece start..")
  end 
  if(tool_index!=ON_DI_SECONDARY):
  on_cog_workpiece_primary=p[workpiece_cog[0],workpiece_cog[1],workpiece_cog[2],0.0,0.0,0.0]
  on_mass_workpiece_primary=workpiece_mass
  else:
  on_cog_workpiece_secondary=p[workpiece_cog[0],workpiece_cog[1],workpiece_cog[2],0.0,0.0,0.0]
  on_mass_workpiece_secondary=workpiece_mass
  end 
  on_payload_update()
  if ON_DEBUG_LOG:
  textmsg("Payload Update Workpiece end.")
  end 
  end 
  def on_payload_get_cog2tcp_workpiece(tool_index=0):
  if(tool_index!=ON_DI_SECONDARY):
  local cog_tool=[on_tcp_workpiece_primary[0],on_tcp_workpiece_primary[1],on_tcp_workpiece_primary[2]]
  else:
  local cog_tool=[on_tcp_workpiece_secondary[0],on_tcp_workpiece_secondary[1],on_tcp_workpiece_secondary[2]]
  end 
  return cog_tool
  end 
  
  #======    End of OnRobot Payload    ======#
  #======    OnRobot QC TCP    ======#
  
  onrobotmini=0
  
  def on_tcp_offset_send(TCP_offset):
  on_robot_TCP_offset=TCP_offset
  end 
  def on_payload_send(CoG,mass):
  on_robot_payload_cog=CoG
  on_robot_payload_mass=mass
  end 
  
  
  #======    End of OnRobot QC TCP    ======#
  #======    OnRobot RG TCP    ======#
  
  def rg_mount_tcp(gripper_angle,isRG2=True):
  if ON_DEBUG_LOG:
  textmsg("RG Mount TCP command starting..")
  end 
  if(isRG2):
  local gripperBracket=rg2_mount_bracket_offset
  local gripperBody=rg2_mount_body_offset
  else:
  local gripperBracket=rg6_mount_bracket_offset
  local gripperBody=rg6_mount_body_offset
  end 
  local gripperRotVec=rpy2rotvec([gripper_angle,0.0,0.0])
  local gripperMountOffset=p[0.0,0.0,gripperBracket,gripperRotVec[0],gripperRotVec[1],gripperRotVec[2]]
  local gripperOffsetStatic=pose_trans(gripperMountOffset,gripperBody)
  if ON_DEBUG_LOG:
  textmsg("RG Mount TCP command ended.")
  end 
  return gripperOffsetStatic
  end 
  def rg_mount_cog(gripper_angle,isRG2=True):
  if ON_DEBUG_LOG:
  textmsg("RG Mount CoG command starting..")
  end 
  if(isRG2):
  local gripperBracket=rg2_mount_bracket_offset
  local gripperCoG=rg2_mount_cog_offset
  else:
  local gripperBracket=rg6_mount_bracket_offset
  local gripperCoG=rg6_mount_cog_offset
  end 
  local gripperRotVec=rpy2rotvec([gripper_angle,0.0,0.0])
  local gripperMountOffset=p[0.0,0.0,gripperBracket,gripperRotVec[0],gripperRotVec[1],gripperRotVec[2]]
  local gripperCOGOffset=pose_trans(gripperMountOffset,gripperCoG)
  gripperCOGOffset=p[gripperCOGOffset[0],gripperCOGOffset[1],gripperCOGOffset[2],0.0,0.0,0.0]
  if ON_DEBUG_LOG:
  textmsg("RG Mount CoG command ended.")
  end 
  return gripperCOGOffset
  end 
  def rg_fcp_depth_calc_frame(tool_index=0):
  local gripperDepth=rg_Depth_arr[tool_index]
  local z_offset=-gripperDepth/1000.0
  return p[0.0,0.0,z_offset,0.0,0.0,0.0]
  end 
  def rg_tcp_dynamic_get(tool_index=0):
  local offset=rg_fcp_depth_calc_frame(tool_index)
  return offset
  end 
  def rg_payload_set(mass,tool_index=0,use_guard=False):
  if ON_DEBUG_LOG:
  textmsg("RG Payload mass command starting..")
  end 
  if(tool_index==ON_DI_SECONDARY):
  local cogTool=[on_cog_workpiece_secondary[0],on_cog_workpiece_secondary[1],on_cog_workpiece_secondary[2]]
  else:
  local cogTool=[on_cog_workpiece_primary[0],on_cog_workpiece_primary[1],on_cog_workpiece_primary[2]]
  end 
  if(use_guard and rg_Grip_detected_arr[tool_index]):
  local mass2set=mass
  rg_Grip_guard_arr[tool_index]=not on_ioqc
  else:
  local mass2set=0.0
  rg_Grip_guard_arr[tool_index]=False
  end 
  on_payload_update_workpiece(mass2set,cogTool,tool_index)
  if ON_DEBUG_LOG:
  textmsg("RG Payload mass command ended.")
  end 
  end 
  
  #======    End of OnRobot RG TCP    ======#
  #======    OnRobot  Speedl    ======#
  
  on_speedl_thread_handler=0
  on_speedl_is_enabled=False
  on_speedl_is_running=False
  on_speedl_acc=0.0
  ft_speedl_hg_caranteen_reached=False
  ft_speedl_hg_caranteen_safemode=False
  on_speedl_for_ftcontrol=False
  on_speedl_for_move=False
  on_speedl_for_handguide=False
  on_speedl_for_insertpart=False
  on_speedl_for_depthcompensation=False
  on_speedl_for_center=False
  on_speedl_for_gecko=False
  on_speedl_acc=10000.0 
  on_speedl_acc_to_zero=3.0 
  ON_SPEEDL_FTCONTROL=1
  ON_SPEEDL_HANDGUIDE=2
  ON_SPEEDL_TRAJECTORY=3
  ON_SPEEDL_MOVE=ON_SPEEDL_TRAJECTORY
  ON_SPEEDL_INSERTPART=4
  ON_SPEEDL_DEPTHCOMP=5
  ON_SPEEDL_CENTER=6
  ON_SPEEDL_GECKO=7
  def on_wait_ms(time_ms):
  local sync_time=ceil(norm(time_ms/2.0))
  while(sync_time>0):
  sync_time=sync_time-1
  sync()
  end
  end 
  def on_error(status_flag,message,title,stop_var=False):
  if(status_flag):
  popup(message,title=title,error=True,blocking=False)
  stop_var=True
  end 
  return stop_var
  end 
  def on_warning(status_flag,message,title,isPopupNeeded=False,is_shown=False):
  if(status_flag):
  if(not is_shown):
  if(isPopupNeeded):
  popup(message,title=title,warning=True,blocking=False)
  else:
  textmsg(title+": ",message)
  end 
  is_shown=True
  end 
  else:
  is_shown=False
  end 
  return is_shown
  end 
  def on_speedl_add_extra(speedBase,speedExtra):
  speedSum=ON_ZERO6D
  speedBaseP=p[speedBase[0],speedBase[1],speedBase[2],speedBase[3],speedBase[4],speedBase[5]]
  speedExtraP=p[speedExtra[0],speedExtra[1],speedExtra[2],speedExtra[3],speedExtra[4],speedExtra[5]]
  speedSumP=pose_add(speedExtraP,speedBaseP)
  speedSum=[speedSumP[0],speedSumP[1],speedSumP[2],speedSumP[3],speedSumP[4],speedSumP[5]]
  return speedSum
  end 
  
  thread on_speedl_thread():
  if ON_DEBUG_LOG:
  textmsg("Speedl thread started..")
  end 
  enter_critical
  on_speedl_is_running=True
  on_speedl_is_enabled=True
  exit_critical
  on_speedL=ON_ZERO6D
  on_speedL_last=ON_ZERO6D
  
  while on_speedl_is_running:
  on_speedBase=on_speedCB_get()
  on_speedL=on_speedBase
  
  
  if on_speedl_is_enabled:
  if(on_speedL==ON_ZERO6D):
  on_speedL=[on_speedL_last[0]/100,on_speedL_last[1]/100,on_speedL_last[2]/100,on_speedL_last[3]/100,on_speedL_last[4]/100,on_speedL_last[5]/100]
  end
  speedl(on_speedL,a=on_speedl_acc,t=speedlTime)
  else:
  speedl(ON_ZERO6D,a=on_speedl_acc_to_zero,t=speedlTime)
  end 
  on_speedL_last=on_speedL
  end 
  
  on_speedL=ON_ZERO6D
  if ON_DEBUG_LOG:
  textmsg("Speedl thread ended.")
  end 
  end 
  def on_speedl_integer_get():
  local speedl_integer=binary_list_to_integer([on_speedl_for_ftcontrol,on_speedl_for_handguide,on_speedl_for_move,on_speedl_for_insertpart,on_speedl_for_depthcompensation,on_speedl_for_center,on_speedl_for_gecko])
  return speedl_integer
  end 
  def on_speedl_start_for(speedl_id):
  if(speedl_id==ON_SPEEDL_FTCONTROL):
  on_speedl_for_ftcontrol=True
  elif(speedl_id==ON_SPEEDL_HANDGUIDE):
  on_speedl_for_handguide=True
  elif(speedl_id==ON_SPEEDL_TRAJECTORY):
  on_speedl_for_move=True
  elif(speedl_id==ON_SPEEDL_INSERTPART):
  on_speedl_for_insertpart=True
  elif(speedl_id==ON_SPEEDL_DEPTHCOMP):
  on_speedl_for_depthcompensation=True
  elif(speedl_id==ON_SPEEDL_CENTER):
  on_speedl_for_center=True
  elif(speedl_id==ON_SPEEDL_GECKO):
  on_speedl_for_gecko=True
  else:
  textmsg("Unknown Start speedl ID received: ",speedl_id)
  end 
  local speedl_integer=on_speedl_integer_get()
  if not(speedl_integer==0):
  if not on_speedl_is_running:
  on_speedl_thread_handler=run on_speedl_thread()
  end 
  end 
  return on_speedl_is_running
  end 
  def on_speedl_stop_for(speedl_id,brake=10,brakeRot=10):
  if(speedl_id==ON_SPEEDL_FTCONTROL):
  on_speedl_for_ftcontrol=False
  elif(speedl_id==ON_SPEEDL_HANDGUIDE):
  on_speedl_for_handguide=False
  elif(speedl_id==ON_SPEEDL_TRAJECTORY):
  on_speedl_for_move=False
  elif(speedl_id==ON_SPEEDL_INSERTPART):
  on_speedl_for_insertpart=False
  elif(speedl_id==ON_SPEEDL_DEPTHCOMP):
  on_speedl_for_depthcompensation=False
  elif(speedl_id==ON_SPEEDL_CENTER):
  on_speedl_for_center=False
  elif(speedl_id==ON_SPEEDL_GECKO):
  on_speedl_for_gecko=False
  on_speedGecko_set(ON_ZERO6D)
  else:
  textmsg("Unknown Stop speedl ID received: ",speedl_id)
  end 
  local speedl_integer=on_speedl_integer_get()
  if(speedl_integer==0):
  if(on_speedl_is_running):
  kill on_speedl_thread_handler
  enter_critical
  on_speedl_is_running=False
  exit_critical
  
  end 
  if ON_DEBUG_LOG:
  textmsg("Speedl thread stopped")
  end 
  stopl(brake,brakeRot)
  end 
  return on_speedl_is_running
  end 
  def on_speedl_pause():
  on_speedl_is_enabled=False
  return on_speedl_integer_get()
  end 
  def on_speedl_resume():
  on_speedl_is_enabled=True
  return on_speedl_integer_get()
  end 
  
  #======    End of OnRobot  Speedl    ======#
  #======    OnRobot RG Engine Messages    ======#
  
  rg_error_title="OnRobot - RG error"
  rg_device_id_waiting="Waiting for valid OnRobot RG ID..."
  rg_device_id_timeout="Waiting for valid OnRobot RG ID timed out.<br>Program halted."
  rg_data_error_title="OnRobot - RG Data error"
  rg_data_error_type="No or unknown Gripper connected."
  rg_data_warning_title="OnRobot - RG Data warning:"
  rg_status_error_title="OnRobot - RG Status error"
  rg_status_error_missing="Communication problem with an RG gripper. Please check the device.<br>Program halted."
  rg_else_error="Unknown error code:"
  rg_status_msg_single="RG status:"
  rg_data_error_bit0_single="Wrong size of float data received."
  rg_data_error_bit1_single="Wrong size of integer data received."
  rg_data_error_bit2_single="Wrong size of boolean data received."
  rg_status_error_mismatch_single="The RG's Status is not matching with its Safety Switches' state."
  rg_status_error_s1_triggered_single="The S1 Safety Switch has been triggered.<br>Please restart the RG gripper."
  rg_status_error_s1_pushed_single="The S1 Safety Switch has been pushed."
  rg_status_error_s2_triggered_single="The S2 Safety Switch has been triggered.<br>Please restart the RG gripper."
  rg_status_error_s2_pushed_single="The S2 Safety Switch has been pushed."
  rg_status_error_safety_system_single="Safety System error occured.<br>Please restart the RG gripper."
  rg_status_msg_primary="RG Primary status:"
  rg_data_error_bit0_primary="Wrong size of float data received for Primary RG."
  rg_data_error_bit1_primary="Wrong size of integer data received for Primary RG."
  rg_data_error_bit2_primary="Wrong size of boolean data received for Primary RG."
  rg_status_error_mismatch_primary="The Primary RG's Status is not matching with its Safety Switches' state."
  rg_status_error_s1_pushed_primary="The S1 Safety Switch has been pushed on Primary RG."
  rg_status_error_s1_triggered_primary="The S1 Safety Switch has been triggered on Primary RG.<br>Please restart the Primary RG gripper."
  rg_status_error_s2_pushed_primary="The S2 Safety Switch has been pushed on Primary RG."
  rg_status_error_s2_triggered_primary="The S2 Safety Switch has been triggered on Primary RG.<br>Please restart the Primary RG gripper."
  rg_status_error_safety_system_primary="Safety System error occured.<br>Please restart the Primary RG gripper."
  rg_status_msg_secondary="RG Secondary status:"
  rg_data_error_bit0_secondary="Wrong size of float data received for Secondary RG."
  rg_data_error_bit1_secondary="Wrong size of integer data received for Secondary RG."
  rg_data_error_bit2_secondary="Wrong size of boolean data received for Secondary RG."
  rg_status_error_mismatch_secondary="The Secondary RG's Status is not matching with its Safety Switches' state."
  rg_status_error_s1_pushed_secondary="The S1 Safety Switch has been pushed on Secondary RG."
  rg_status_error_s1_triggered_secondary="The S1 Safety Switch has been triggered on Secondary RG.<br>Please restart the Secondary RG gripper."
  rg_status_error_s2_pushed_secondary="The S2 Safety Switch has been pushed on Secondary RG."
  rg_status_error_s2_triggered_secondary="The S2 Safety Switch has been triggered on Secondary RG.<br>Please restart the Secondary RG gripper."
  rg_status_error_safety_system_secondary="The Safety System error.<br>Please restart the Secondary RG gripper."
  
  #======    End of OnRobot RG Engine Messages    ======#
  #======    OnRobot RG Engine    ======#
  
  rg_dataProcess_running=False
  rg_start_flange=ON_ZEROPOSE
  rg_start_pose=ON_ZEROPOSE
  RG_STATUS_IGNORE_SHIFT=4
  def rg_status_int_get(tool_index):
  local status_int=binary_list_to_integer([rg_S1_pushed_arr[tool_index],rg_S1_triggered_arr[tool_index],rg_S2_pushed_arr[tool_index],rg_S2_triggered_arr[tool_index],rg_Safety_error_arr[tool_index]])
  return status_int
  end 
  def rg_dataProcess_status_errors(rg_stop=False):
  enter_critical
  local tool_index=rg_index
  if(tool_index==ON_DI_DUAL):
  tool_index=ON_DI_SECONDARY
  rg_stop=on_error((rg_device_id_arr[tool_index]!=tool_index),rg_status_error_missing,rg_status_error_title,rg_stop)
  rg_stop=on_error((rg_product_code_arr[tool_index]==ON_DEVICE_ID_MISSING),rg_status_error_missing,rg_status_error_title,rg_stop)
  tool_index=ON_DI_PRIMARY
  end 
  rg_stop=on_error((rg_device_id_arr[tool_index]!=tool_index),rg_status_error_missing,rg_status_error_title,rg_stop)
  rg_stop=on_error((rg_product_code_arr[tool_index]==ON_DEVICE_ID_MISSING),rg_status_error_missing,rg_status_error_title,rg_stop)
  
  local switch_error_single=rg_status_int_get(tool_index)
  local status_error_single=floor(rg_Status_arr[tool_index]/RG_STATUS_IGNORE_SHIFT)
  if(status_error_single!=switch_error_single):
  on_warning(((status_error_single-switch_error_single)>0),str_cat(rg_else_error,rg_Status_arr[tool_index]),rg_status_error_title)
  end 
  if(switch_error_single!=0):
  rg_stop=on_error(rg_S1_pushed_arr[tool_index],rg_status_error_s1_pushed_single,rg_status_error_title,rg_stop)
  rg_stop=on_error(rg_S1_triggered_arr[tool_index],rg_status_error_s1_triggered_single,rg_status_error_title,rg_stop)
  rg_stop=on_error(rg_S2_pushed_arr[tool_index],rg_status_error_s2_pushed_single,rg_status_error_title,rg_stop)
  rg_stop=on_error(rg_S2_triggered_arr[tool_index],rg_status_error_s2_triggered_single,rg_status_error_title,rg_stop)
  rg_stop=on_error(rg_Safety_error_arr[tool_index],rg_status_error_safety_system_single,rg_status_error_title,rg_stop)
  end 
  
  exit_critical
  return rg_stop
  end 
  def rg_dataProcess():
  enter_critical
  local tool_index=rg_index
  if tool_index==ON_DI_DUAL:
  rg_Width_primary=rg_Width_arr[ON_DI_PRIMARY]
  rg_Depth_primary=rg_Depth_arr[ON_DI_PRIMARY]
  rg_DepthRel_primary=rg_DepthRel_arr[ON_DI_PRIMARY]
  rg_Busy_primary=rg_Busy_arr[ON_DI_PRIMARY]
  rg_Grip_detected_primary=rg_Grip_detected_arr[ON_DI_PRIMARY]
  rg_Width_secondary=rg_Width_arr[ON_DI_SECONDARY]
  rg_Depth_secondary=rg_Depth_arr[ON_DI_SECONDARY]
  rg_DepthRel_secondary=rg_DepthRel_arr[ON_DI_SECONDARY]
  rg_Busy_secondary=rg_Busy_arr[ON_DI_SECONDARY]
  rg_Grip_detected_secondary=rg_Grip_detected_arr[ON_DI_SECONDARY]
  else:
  rg_Width=rg_Width_arr[tool_index]
  rg_Depth=rg_Depth_arr[tool_index]
  rg_DepthRel=rg_DepthRel_arr[tool_index]
  rg_Busy=rg_Busy_arr[tool_index]
  rg_Grip_detected=rg_Grip_detected_arr[tool_index]
  end 
  exit_critical
  end 
  thread rg_dataProcess_thread():
  if ON_DEBUG_LOG:
  textmsg("Starting rg_dataProcess thread")
  end 
  while rg_dataProcess_running:
  sync()
  local rg_stop=False
  rg_stop=rg_dataProcess_status_errors(rg_stop)
  if rg_stop:
  halt
  end 
  rg_dataProcess()
  end 
  if ON_DEBUG_LOG:
  textmsg("Stopping rg_dataProcess thread")
  end 
  end 
  def rg_index_get():
  return rg_index
  end 
  
  #======    End of OnRobot RG Engine    ======#
  rg_mounting_angle_arr[0] = 0.0
  rg_fingertip_arr[0] = 4.599999904632568
  rg_Depth_arr[0] = 39.59999847412109
  textmsg(on_devices_primary_log, ": Quick Changer + RG2 + [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]")
  on_follow_tcp = False
  on_tcp_active_is_primary = True
  on_tcp_adapters_array = []
  on_cog_adapters_array = []
  on_mass_adapters_array = []
  on_tcp_qc_primary = p[0.0, 0.0, 0.0136, 0.0, 0.0, 0.0]
  on_cog_qc_primary = p[0.0, 0.0, 0.004, 0.0, 0.0, 0.0]
  on_mass_qc_primary = 0.06
  on_tcp_gripper_static_primary = rg_mount_tcp(rg_mounting_angle_arr[0])
  on_cog_gripper_primary = rg_mount_cog(rg_mounting_angle_arr[0])
  on_mass_gripper_primary = 0.78
  on_tcp_workpiece_primary = p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  on_cog_workpiece_primary = p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  on_mass_workpiece_primary = 0.0
  
  #======    End of OnRobot RG Depth    ======#
  #======    OnRobot RG Width Messages    ======#
  
  rg_grip_title="OnRobot - RG Grip"
  rg_grip_return_error_n1="RG Grip command returned with error.<br>Please be sure that the required width is between the limits.<br>Program halted."
  
  #======    End of OnRobot RG Width Messages    ======#
  #======    OnRobot RG Width    ======#
  
  RG_MIN_WIDTH=0
  RG_MAX_WIDTH_RG2=110
  RG_MAX_WIDTH_RG6=160
  RG_MIN_FORCE=0
  RG_MAX_FORCE_RG2=40
  RG_MAX_FORCE_RG6=120
  rg__grip_param_warning_width="The parameter 'width' is out of the limits. Limited value sent: "
  rg__grip_param_warning_force="The parameter 'force' is out of the limits. Limited value sent: "
  def rg_depth_compensate(tool_index,start_depth_mm):
  local timeout=0
  while not rg_Busy_arr[tool_index]:
  sleep(0.008)
  timeout=timeout+1
  if timeout>20:
  break
  end
  end
  local start_pose=get_forward_kin()
  if(tool_index==ON_DI_SECONDARY):
  local tcp_static=on_tcp_static_secondary
  else:
  local tcp_static=on_tcp_static_primary
  end 
  local t_w_rg=pose_trans(get_actual_tool_flange_pose(),tcp_static)
  local t_rg_w=pose_inv(t_w_rg)
  local compensation_depth_mm=0
  local after_ready_continue_count=10
  while True:
  local busy=rg_Busy_arr[tool_index]
  if not busy:
  if after_ready_continue_count>0:
  after_ready_continue_count=after_ready_continue_count-1
  else:
  break
  end
  end
  local measure_depth_mm=rg_Depth_arr[tool_index]
  compensation_depth_mm=measure_depth_mm-start_depth_mm
  local target_pose=pose_add(start_pose,pose_trans(pose_trans(t_w_rg,p[0,0,compensation_depth_mm/1000.0,0,0,0]),t_rg_w))
  servoj(get_inverse_kin(target_pose),t=0.008,lookahead_time=0.033,gain=1500)
  end
  stopj(20)
  end
  def rg_grip(width,force,tool_index=0,blocking=True,depth_comp=False,popupmsg=True):
  if ON_DEBUG_LOG:
  textmsg("RG Grip start..")
  end 
  local retVal=0
  local limitOffset=(2.0*rg_fingertip_arr[tool_index])
  local width2send=width
  if limitOffset>0:
  local minWidth=RG_MIN_WIDTH
  else:
  local minWidth=RG_MIN_WIDTH-limitOffset
  end 
  if not(width2send>=minWidth):
  width2send=minWidth
  textmsg(rg__grip_param_warning_width,width2send)
  elif not(force>=RG_MIN_FORCE):
  force=RG_MIN_FORCE
  textmsg(rg__grip_param_warning_force,force)
  end 
  if(rg_product_code_arr[tool_index]==RG_DEVICE_ID_RG6):
  if not(width2send<=RG_MAX_WIDTH_RG6-limitOffset):
  width2send=RG_MAX_WIDTH_RG6-limitOffset
  textmsg(rg__grip_param_warning_width,width2send)
  elif not(force<=RG_MAX_FORCE_RG6):
  force=RG_MAX_FORCE_RG6
  textmsg(rg__grip_param_warning_force,force)
  end 
  else:
  if not(width2send<=RG_MAX_WIDTH_RG2-limitOffset):
  width2send=RG_MAX_WIDTH_RG2-limitOffset
  textmsg(rg__grip_param_warning_width,width2send)
  elif not((force<=RG_MAX_FORCE_RG2)):
  force=RG_MAX_FORCE_RG2
  textmsg(rg__grip_param_warning_force,force)
  end 
  end 
  rg_Grip_guard_arr[tool_index]=False
  sync()
  if(tool_index==ON_DI_SECONDARY):
  local isPrimary=False
  else:
  local isPrimary=True
  end 
  if(on_follow_tcp):
  on_tcp_set_actual_to(isPrimary)
  end 
  if depth_comp:
  local start_depth_mm=rg_Depth_arr[tool_index]
  end 
  sync()
  retVal=on_tool_xmlrpc.rg_grip(tool_index,width2send+0.0,force+0.0)
  if(retVal!=0):
  popup(rg_grip_return_error_n1,rg_grip_title,error=True,blocking=False)
  halt
  end 
  if depth_comp:
  rg_depth_compensate(tool_index,start_depth_mm)
  end 
  if blocking:
  if not depth_comp:
  local timeout=0
  while not rg_Busy_arr[tool_index]:
  sleep(0.008)
  timeout=timeout+1
  if timeout>20:
  break
  end 
  end 
  end 
  while(rg_Busy_arr[tool_index]==True):
  sync()
  end 
  end 
  if(on_follow_tcp):
  on_tcp_update(isPrimary)
  end 
  if ON_DEBUG_LOG:
  textmsg("RG Grip ended.")
  end 
  return retVal
  end 
  
  #======    End of OnRobot RG Width    ======#
  #======    OnRobot VG Monitor Messages    ======#
  
  rg_monitor_error_title="OnRobot - RG Grip lost"
  rg_monitor_grip_lost_error="Grip lost detected.<br>Program halted."
  
  #======    End of OnRobot VG Monitor Messages    ======#
  #======    OnRobot RG Monitor    ======#
  
  thread rg_monitor_thread():
  while True:
  sync()
  local rg_error=False
  if(rg_index==ON_DI_DUAL):
  local tool_index=ON_DI_SECONDARY
  rg_error=rg_monitor_check(tool_index)
  local tool_index=ON_DI_PRIMARY
  else:
  local tool_index=rg_index
  end 
  rg_error=rg_error or rg_monitor_check(tool_index)
  if rg_error:
  halt
  end 
  end 
  end 
  def rg_monitor_check(tool_index=0):
  local error=False
  if rg_Grip_guard_arr[tool_index]and not rg_Grip_detected_arr[tool_index]:
  popup(rg_monitor_grip_lost_error,title=rg_monitor_error_title,error=True,blocking=False)
  rg_payload_set(0,tool_index=tool_index)
  error=True
  end 
  return error
  end 
  
  #======    End of OnRobot RG Monitor    ======#
  #======    OnRobot Run    ======#
  
  on_portopen_javaSocket()
  sync()
  textmsg(on_xmlrpc_start_ip,on_conn_ip)
  if(ON_REG_USE_TOOL):
  on_regStart_conn=[ON_CONN_SHIFT_BOOL,ON_CONN_SHIFT_INT,ON_CONN_SHIFT_FLOAT]
  on_regSum_conn=[ON_CONN_REG_SUM_BOOL,ON_CONN_REG_SUM_INT,ON_CONN_REG_SUM_FLOAT]
  on_rtde_feed_open(on_conn_ip,on_conn_rtde_feed_name,on_regStart_conn,on_regSum_conn,ON_REGISTERS_SPEEDL_FLOAT)
  sync()
  textmsg(on_xmlrpc_start_ip,on_tool_ip)
  on_regStart_tool=[ON_TOOL_SHIFT_BOOL,ON_TOOL_SHIFT_INT,ON_TOOL_SHIFT_FLOAT]
  on_regSum_tool=[ON_TOOL_REG_SUM_BOOL,ON_TOOL_REG_SUM_INT,ON_TOOL_REG_SUM_FLOAT]
  on_rtde_feed_open(on_tool_ip,on_tool_rtde_feed_name,on_regStart_tool,on_regSum_tool,0)
  sync()
  else:
  on_regStart_conn=[ON_CONN_SHIFT_BOOL,ON_CONN_SHIFT_INT,ON_CONN_SHIFT_FLOAT]
  on_regSum_conn=[ON_CONN_REG_SUM_BOOL,ON_CONN_REG_SUM_INT,ON_CONN_REG_SUM_FLOAT]
  on_rtde_feed_open(on_conn_ip,on_conn_rtde_feed_name,on_regStart_conn,on_regSum_conn,ON_REGISTERS_SPEEDL_FLOAT)
  sync()
  end
  on_set_rtde_watchdog(updateHz=0.2)
  sync()
  on_dataProcess_thrd=run on_dataProcess_thread()
  sync()
  on_tcp_init_adapters()
  on_payload_init_adapters()
  on_tcp_init_primary()
  on_payload_init_primary()
  
  on_tcp_update_custom()
  on_tcp_set_actual_to(on_tcp_active_is_primary)
  if(on_follow_tcp):
  on_payload_set_actual()
  end 
  on_watchdog_thrd=run on_set_watchdog_thread()
  sync()
  def done_waiting_for_init(device_name,product_code,tool_index=0):
  textmsg(str_cat(device_name,str_cat(str_cat("[",tool_index),"]: ")),product_code)
  end
  
  #======    End of OnRobot Run    ======#
  #======    OnRobot QC Start    ======#
  
  if(on_toolConnector):
  tc_setup_tool()
  end 
  sync()
  
  #======    End of OnRobot QC Start    ======#
  #======    OnRobot RG Run    ======#
  
  def rg_wait_for_init(tool_index):
  local rg_timeout=0
  while not((rg_product_code_arr[tool_index]==RG_DEVICE_ID_RG2)or(rg_product_code_arr[tool_index]==RG_DEVICE_ID_RG6)):
  sync()
  rg_timeout=rg_timeout+1
  if(rg_timeout>ON_INIT_TIMEOUT):
  popup(rg_device_id_timeout,rg_error_title,error=True,blocking=False)
  halt
  end 
  end 
  done_waiting_for_init("RG",rg_product_code_arr[tool_index],tool_index)
  end 
  rg_dataRead_running=True
  sync()
  rg_dataRead_thrd=run rg_dataRead_thread()
  sync()
  textmsg(rg_device_id_waiting)
  if(rg_index==ON_DI_DUAL):
  rg_wait_for_init(ON_DI_PRIMARY)
  rg_wait_for_init(ON_DI_SECONDARY)
  else:
  rg_wait_for_init(rg_index)
  end 
  sync()
  rg_dataProcess_running=True
  sync()
  rg_dataProcess_thrd=run rg_dataProcess_thread()
  sync()
  rg_monitor_thread_handle=run rg_monitor_thread()
  sync()
  
  #======    End of OnRobot RG Run    ======#
  # end: URCap Installation Node
  global Pallet_1_cnt_1=1
  global Pallet_1_lct=1
  global Pallet_1_lno=1
  global Pallet_1_sep= False 
  global Pallet_1_tct=1
  global Pallet_2_cnt=1
  global Pallet_2_lct=1
  global Pallet_2_lno=1
  global Pallet_2_sep= False 
  global Pallet_2_tct=1
  global Pallet_3_cnt=1
  global Pallet_3_lct=1
  global Pallet_3_lno=1
  global Pallet_3_sep= False 
  global Pallet_3_tct=1
  global Pallet_4_cnt=1
  global Pallet_4_lct=1
  global Pallet_4_lno=1
  global Pallet_4_sep= False 
  global Pallet_4_tct=1
  global Pallet_5_cnt=1
  global Pallet_5_lct=1
  global Pallet_5_lno=1
  global Pallet_5_sep= False 
  global Pallet_5_tct=1
  global Pallet_6_cnt=1
  global Pallet_6_lct=1
  global Pallet_6_lno=1
  global Pallet_6_sep= False 
  global Pallet_6_tct=1
  global Pallet_7_cnt=1
  global Pallet_7_lct=1
  global Pallet_7_lno=1
  global Pallet_7_sep= False 
  global Pallet_7_tct=1
  global home_p=p[.349210888563, -.001071710312, .358337133080, 2.234324981439, -2.188536069758, -.024472846726]
  global home_q=[0.5152868032455444, -1.4912899148515244, -2.2449679374694824, -4.13602938274526, -1.585261646901266, -2.6426876227008265]
  global Approach_p=p[.306638447182, .236630213426, .332959075215, 2.234240095386, -2.188556589961, -.024431835562]
  global Approach_q=[1.1175873279571062, -1.5913764439031972, -2.200937509536545, -4.070533176463183, -1.593075577412776, -2.040055100115909]
  global ToolActionPoint_p=p[.306640764613, .236656028351, .262830373686, 2.234366597425, -2.188525546411, -.024466520317]
  global ToolActionPoint_q=[1.1177921295162405, -1.6875902614994223, -2.259657144546299, -3.915514846842262, -1.5927117506624384, -2.0394046942345883]
  global Exit_1_p=p[.306626106331, .236608034550, .333664354464, 2.234210709265, -2.188514412491, -.024452724626]
  global Exit_1_q=[1.1175798177718557, -1.5904919109741762, -2.2003085613250057, -4.072090288202064, -1.593107525502444, -2.0400746504411487]
  global Approach_1_p=p[.484930783603, .009609875221, .335590434103, 2.234107925264, -2.188617929103, -.024672153318]
  global Approach_1_q=[0.3848293423650908, -1.7537619076178288, -2.0135951042172326, -4.106383939784536, -1.5825393835655532, -2.7727649847598244]
  global ToolActionPoi_1_p=p[.484957857050, .009632097733, .268373312260, 2.234217459818, -2.188600244787, -.024602472596]
  global ToolActionPoi_1_q=[0.3849461376666472, -1.8319150410109613, -2.0640125274651133, -3.977731605573368, -1.582241360341757, -2.7722855250036904]
  global Exit_2_p=p[.484936096171, .009612458124, .328275208304, 2.234143380031, -2.188528634036, -.024639924357]
  global Exit_2_q=[0.3848496675493278, -1.76158632854683, -2.019710302352655, -4.092470308345643, -1.5824783484082987, -2.772754494343703]
  global Approach_2_p=p[.231461575763, .236660672645, .325113863042, 2.234297772276, -2.188403273557, -.024420594814]
  global Approach_2_q=[1.3428397178671183, -1.492740259768489, -2.311947107316043, -4.053708931004088, -1.5945799986418407, -1.814867321646343]
  global ToolActionPoi_2_p=p[.231461224390, .236677385680, .266371828865, 2.234349404124, -2.188413039780, -.024415260983]
  global ToolActionPoi_2_q=[1.343090772628912, -1.5818606815730423, -2.3656153678894967, -3.910870452919845, -1.5942190329176462, -1.8141487280473942]
  global Exit_3_p=p[.231462695623, .236695563792, .330217268489, 2.234350100485, -2.188462438739, -.024457498149]
  global Exit_3_q=[1.3428515195848476, -1.485901669866637, -2.3067409992215833, -4.065674682660035, -1.5945828596693907, -1.8148930708536923]
  global Approach_3_p=p[.447315421202, -.020799432501, .329805306808, .000124213877, 3.132843471219, .034204818944]
  global Approach_3_q=[0.34824037551848597, -1.6906377277764282, -2.092965602874866, -4.0554644070050365, -1.5912478605863063, -1.21756345430419]
  global ToolActionPoi_3_p=p[.447306697002, -.020806760417, .284150523902, .000075912436, 3.132901664481, .034119214670]
  global ToolActionPoi_3_q=[0.3483197987073474, -1.7457395992658693, -2.130041122436971, -3.9633537731521296, -1.5910037199627878, -1.2172163168602346]
  global Exit_4_p=p[.447314473140, -.020797724065, .338088189356, .000061917746, 3.132869707736, .034072620144]
  global Exit_4_q=[0.34824922680625026, -1.6814500294146555, -2.0855958461750443, -4.072075506253242, -1.5912111441321484, -1.217650715505247]
  global Approach_4_p=p[.451103604164, .029447318532, .331486553718, .042757281870, 3.138543834415, .064451168041]
  global Approach_4_q=[0.4509325027465381, -1.695590635339233, -2.0824117660522603, -4.0562018356718585, -1.6094010511981942, -1.0874913374530912]
  global ToolActionPoi_4_p=p[.451125562127, .029446302098, .262751866123, .042777531300, 3.138451806196, .064485488077]
  global ToolActionPoi_4_q=[0.45102557539962945, -1.7801858387377258, -2.1359744071965903, -3.9179336033234717, -1.6090491453743319, -1.0869405905303573]
  global Exit_5_p=p[.451118561364, .029438687322, .357266423625, .042810486898, 3.138459990780, .064447940885]
  global Exit_5_q=[0.45086050033576974, -1.668151517907722, -2.058767318725587, -4.107219596902773, -1.6094644705396632, -1.0876987616163412]
  global Waypoint_1_p=p[.349207170713, .003599254909, .284439499821, 2.234296895850, -2.188534271831, -.024536811873]
  global Waypoint_1_q=[0.5287984609603882, -1.5910164318480433, -2.315638780593872, -3.9655024013915003, -1.5851782003985804, -2.628573242818014]
  global Approach_6_p=p[.284192810366, .243921496661, .349082232338, 2.177363819916, -2.260344213821, .070263413768]
  global Approach_6_q=[1.2071821689595996, -1.547059371403531, -2.2137856483453975, -4.1151892147486615, -1.5344761053694125, -1.8920348326297738]
  global ToolActionPoi_6_p=p[.284197625249, .243934188656, .267233221575, 2.177404781675, -2.260348668966, .070271640319]
  global ToolActionPoi_6_q=[1.2074255943234844, -1.658938547174893, -2.2859950065594474, -3.9311086140065044, -1.5340541044998286, -1.8911812941227737]
  global Exit_7_p=p[.284178269189, .243943836351, .339008126906, 2.177449449738, -2.260179264433, .070283498101]
  global Exit_7_q=[1.2072744369509685, -1.559209590111596, -2.2237443923952247, -4.093143840827995, -1.5344484488110552, -1.891976181658336]
  global Approach_5_p=p[.286417470873, -.205780032071, .342030608352, 2.177479564447, -2.260342193757, .070235725384]
  global Approach_5_q=[-0.0942414442638082, -1.4956775543140957, -2.263182401657345, -4.063449760476262, -1.5430529753295943, -3.194308821353518]
  global ToolActionPoi_5_p=p[.286404685328, -.205785677591, .267224620690, 2.177405596580, -2.260347723500, .070320648223]
  global ToolActionPoi_5_q=[-0.09397966066538643, -1.6013246975351816, -2.332792520522611, -3.888208290141485, -1.5425604025486095, -3.193427149449901]
  global Exit_6_p=p[.286404393325, -.205790637272, .349599680009, 2.177424987485, -2.260410196992, .070369921100]
  global Exit_6_q=[-0.09429103532869476, -1.4865179967932747, -2.2552361488342774, -4.080479284326586, -1.5430420080763092, -3.1943643728839364]
  while (True):
    $ 1 "Robot Program"
    $ 2 "MoveJ"
    $ 3 "home" "breakAfter"
    movej(get_inverse_kin(home_p, qnear=home_q), a=1.3962634015954636, v=1.0471975511965976)
    # begin: URCap Program Node
    #   Source: OnRobot, 6.2.0, OnRobot A/S
    #   Type: RG Grip
    $ 4 "RG Grip"
on_return = rg_grip(101.4, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
    # end: URCap Program Node
    $ 5 "Loop 3 times"
    Loop_1 = 0
    while (Loop_1 < 3):
      $ 6 "Pallet_1"
      def Pallet_1_trans(pose):
      return p[pose[0], pose[1], pose[2], 0, 0, 0]
    end
    def Pallet_1_rot(pose):
    return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def Pallet_1_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(Pallet_1_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), Pallet_1_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(Pallet_1_rot(T_feature_referencePoint_taught), pose_trans(Pallet_1_rot(T_referencePoint_approach_taught), pose_inv(Pallet_1_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(Pallet_1_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, Pallet_1_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_1_tct = 3
  if (Pallet_1_cnt_1 > 3 or Pallet_1_cnt_1 < 1):
    Pallet_1_cnt_1 = 1
  end
  $ 7 "Patterns" "noBreak"
  $ 8 "Line_Pattern_1" "noBreak"
  $ 11 "Layers" "noBreak"
  if (Pallet_1_cnt_1 < 4):
    Pallet_1_lno = 1
    Pallet_1_lct = Pallet_1_cnt_1
    global StartItem_1=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.306642658610, .236662557551, .266490991030, 2.234347648523, -2.188537550932, -.024459887620]))
    global EndItem_1=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.252245780355, .236661279711, .266348147405, 2.234309645051, -2.188378132021, -.024411946530]))
    referencePoint = interpolate_pose(StartItem_1, EndItem_1, (Pallet_1_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoint = pose_add (referencePoint,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_p = Pallet_1_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.3066407646125005,0.23665602835080357,0.2628303736863845,2.2343665974248883,-2.188525546411007,-0.024466520317351616]), p[-7.730481461379335E-5,0.0014654565438411704,-0.07011335044745298,-3.3901666657269E-5,6.308214021019877E-5,7.14703363566861E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoint)
  Approach_p = pose_trans(p[0.3066407646125005,0.23665602835080357,0.2628303736863845,2.2343665974248657,-2.1885255464109843,-0.02446652031733731], pose_trans(pose_inv(referencePoint), Approach_p))
  ToolActionPoint_p = Pallet_1_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.3066407646125005,0.23665602835080357,0.2628303736863845,2.2343665974248883,-2.188525546411007,-0.024466520317351616]), p[0.0,0.0,0.0,0.0,0.0,0.0], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoint)
  ToolActionPoint_p = pose_trans(p[0.3066407646125005,0.23665602835080357,0.2628303736863845,2.2343665974248657,-2.1885255464109843,-0.02446652031733731], pose_trans(pose_inv(referencePoint), ToolActionPoint_p))
  Exit_1_p = Pallet_1_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.3066407646125005,0.23665602835080357,0.2628303736863845,2.2343665974248883,-2.188525546411007,-0.024466520317351616]), p[-5.6422845804787736E-5,0.0014929613023946797,-0.07081824082902222,-7.939274344868303E-5,8.864952183710194E-5,6.565241248385462E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoint)
  Exit_1_p = pose_trans(p[0.3066407646125005,0.23665602835080357,0.2628303736863845,2.2343665974248657,-2.1885255464109843,-0.02446652031733731], pose_trans(pose_inv(referencePoint), Exit_1_p))
  $ 12 "At Each Item" "noBreak"
  $ 13 "Generated Movements" "noBreak"
  $ 14 "MoveJ" "noBreak"
  $ 15 "Approach" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoint, pose_trans(p[.230640317562, .305934192179, .268930759824, -2.234366597425, 2.188525546411, .024466520317], Approach_p)), qnear=Approach_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 16 "MoveL" "noBreak"
  $ 17 "ToolActionPoint" "noBreak"
  movel(pose_trans(referencePoint, pose_trans(p[.230640317562, .305934192179, .268930759824, -2.234366597425, 2.188525546411, .024466520317], ToolActionPoint_p)), a=1.2, v=0.25)
  $ 18 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 19 "RG Grip" "noBreak"
on_return = rg_grip(74.7, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 20 "MoveL" "noBreak"
  $ 21 "Exit_1" "noBreak"
  movel(pose_trans(referencePoint, pose_trans(p[.230640317562, .305934192179, .268930759824, -2.234366597425, 2.188525546411, .024466520317], Exit_1_p)), a=1.2, v=0.25)
  Pallet_1_sep = False
  if (Pallet_1_cnt_1 >= 3):
    Pallet_1_cnt_1 = 1
  else:
    Pallet_1_cnt_1 = Pallet_1_cnt_1 + 1
  end
  $ 22 "Pallet_2"
  def Pallet_2_trans(pose):
  return p[pose[0], pose[1], pose[2], 0, 0, 0]
  end
  def Pallet_2_rot(pose):
  return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def Pallet_2_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(Pallet_2_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), Pallet_2_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(Pallet_2_rot(T_feature_referencePoint_taught), pose_trans(Pallet_2_rot(T_referencePoint_approach_taught), pose_inv(Pallet_2_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(Pallet_2_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, Pallet_2_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_2_tct = 3
  if (Pallet_2_cnt > 3 or Pallet_2_cnt < 1):
    Pallet_2_cnt = 1
  end
  $ 23 "Patterns" "noBreak"
  $ 24 "Line_Pattern_2" "noBreak"
  $ 27 "Layers" "noBreak"
  if (Pallet_2_cnt < 4):
    Pallet_2_lno = 1
    Pallet_2_lct = Pallet_2_cnt
    global StartItem_2=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.481355800811, .009609468259, .262384997768, 2.234237315611, -2.188654377655, -.024349921696]))
    global EndItem_2=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.424742723766, .009673063290, .268353078328, 2.234321559038, -2.188500992991, -.024658315167]))
    referencePoin_1 = interpolate_pose(StartItem_2, EndItem_2, (Pallet_2_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoin_1 = pose_add (referencePoin_1,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_1_p = Pallet_2_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.48495785704999833,0.009632097732523529,0.2683733122601669,2.234217459817548,-2.188600244786819,-0.02460247259590475]), p[-7.874103662702282E-5,0.001436061069294281,-0.06720174271611329,-7.803022077303864E-5,1.3046423385353933E-5,5.729012977279522E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_1)
  Approach_1_p = pose_trans(p[0.48495785704999833,0.009632097732523529,0.2683733122601669,2.234217459817519,-2.1886002447867914,-0.0246024725959321], pose_trans(pose_inv(referencePoin_1), Approach_1_p))
  ToolActionPoi_1_p = Pallet_2_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.48495785704999833,0.009632097732523529,0.2683733122601669,2.234217459817548,-2.188600244786819,-0.02460247259590475]), p[0.0,0.0,0.0,0.0,0.0,0.0], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_1)
  ToolActionPoi_1_p = pose_trans(p[0.48495785704999833,0.009632097732523529,0.2683733122601669,2.234217459817519,-2.1886002447867914,-0.0246024725959321], pose_trans(pose_inv(referencePoin_1), ToolActionPoi_1_p))
  Exit_2_p = Pallet_2_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.48495785704999833,0.009632097732523529,0.2683733122601669,2.234217459817548,-2.188600244786819,-0.02460247259590475]), p[-7.028729401293123E-5,0.0012774062931829588,-0.05988824009563121,-9.050768758763442E-5,5.4407020931315515E-5,1.0746796289545092E-6], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_1)
  Exit_2_p = pose_trans(p[0.48495785704999833,0.009632097732523529,0.2683733122601669,2.234217459817519,-2.1886002447867914,-0.0246024725959321], pose_trans(pose_inv(referencePoin_1), Exit_2_p))
  $ 28 "At Each Item" "noBreak"
  $ 29 "Generated Movements" "noBreak"
  $ 30 "MoveJ" "noBreak"
  $ 31 "Approach_1" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_1, pose_trans(p[.000035798118, .479323058149, .278478975508, -2.234217459818, 2.188600244787, .024602472596], Approach_1_p)), qnear=Approach_1_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 32 "MoveL" "noBreak"
  $ 33 "ToolActionPoi_1" "noBreak"
  movel(pose_trans(referencePoin_1, pose_trans(p[.000035798118, .479323058149, .278478975508, -2.234217459818, 2.188600244787, .024602472596], ToolActionPoi_1_p)), a=1.2, v=0.25)
  $ 34 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 35 "RG Grip" "noBreak"
on_return = rg_grip(101.4, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 36 "MoveL" "noBreak"
  $ 37 "Exit_2" "noBreak"
  movel(pose_trans(referencePoin_1, pose_trans(p[.000035798118, .479323058149, .278478975508, -2.234217459818, 2.188600244787, .024602472596], Exit_2_p)), a=1.2, v=0.25)
  Pallet_2_sep = False
  if (Pallet_2_cnt >= 3):
    Pallet_2_cnt = 1
  else:
    Pallet_2_cnt = Pallet_2_cnt + 1
  end
  Loop_1 = Loop_1 + 1
  end
  $ 38 "Loop 3 times"
  Loop_2 = 0
  while (Loop_2 < 3):
    $ 39 "Pallet_3"
    def Pallet_3_trans(pose):
    return p[pose[0], pose[1], pose[2], 0, 0, 0]
  end
  def Pallet_3_rot(pose):
  return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def Pallet_3_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(Pallet_3_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), Pallet_3_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(Pallet_3_rot(T_feature_referencePoint_taught), pose_trans(Pallet_3_rot(T_referencePoint_approach_taught), pose_inv(Pallet_3_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(Pallet_3_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, Pallet_3_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_3_tct = 3
  if (Pallet_3_cnt > 3 or Pallet_3_cnt < 1):
    Pallet_3_cnt = 1
  end
  $ 40 "Patterns" "noBreak"
  $ 41 "Line_Pattern_3" "noBreak"
  $ 44 "Layers" "noBreak"
  if (Pallet_3_cnt < 4):
    Pallet_3_lno = 1
    Pallet_3_lct = Pallet_3_cnt
    global StartItem_3=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.231461224390, .236677385680, .266371828865, 2.234349404124, -2.188413039780, -.024415260983]))
    global EndItem_3=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.174466232156, .236662410008, .266360318323, 2.234298193141, -2.188453240588, -.024427674379]))
    referencePoin_2 = interpolate_pose(StartItem_3, EndItem_3, (Pallet_3_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoin_2 = pose_add (referencePoin_2,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_2_p = Pallet_3_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.2314612243898091,0.23667738567998564,0.26637182886507205,2.234349404124048,-2.1884130397802073,-0.024415260983447852]), p[-6.452830422623568E-5,0.0012276253218893862,-0.058729171889359055,-3.372884862343651E-5,2.7773833246212307E-5,1.8955340389377872E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_2)
  Approach_2_p = pose_trans(p[0.2314612243898091,0.23667738567998564,0.26637182886507205,2.2343494041240644,-2.188413039780224,-0.024415260983445364], pose_trans(pose_inv(referencePoin_2), Approach_2_p))
  ToolActionPoi_2_p = Pallet_3_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.2314612243898091,0.23667738567998564,0.26637182886507205,2.234349404124048,-2.1884130397802073,-0.024415260983447852]), p[0.0,-2.7755575615628914E-17,0.0,0.0,0.0,0.0], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_2)
  ToolActionPoi_2_p = pose_trans(p[0.2314612243898091,0.23667738567998564,0.26637182886507205,2.2343494041240644,-2.188413039780224,-0.024415260983445364], pose_trans(pose_inv(referencePoin_2), ToolActionPoi_2_p))
  Exit_3_p = Pallet_3_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.2314612243898091,0.23667738567998564,0.26637182886507205,2.234349404124048,-2.1884130397802073,-0.024415260983447852]), p[-1.064470825177799E-4,0.001332435183076075,-0.0638314481962799,6.5235322472909356E-6,-4.4164474931583704E-5,2.1790194812636874E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_2)
  Exit_3_p = pose_trans(p[0.2314612243898091,0.23667738567998564,0.26637182886507205,2.2343494041240644,-2.188413039780224,-0.024415260983445364], pose_trans(pose_inv(referencePoin_2), Exit_3_p))
  $ 45 "At Each Item" "noBreak"
  $ 46 "Generated Movements" "noBreak"
  $ 47 "MoveJ" "noBreak"
  $ 48 "Approach_2" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_2, pose_trans(p[.232190378902, .230712114941, .270931693358, -2.234349404124, 2.188413039780, .024415260983], Approach_2_p)), qnear=Approach_2_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 49 "MoveL" "noBreak"
  $ 50 "ToolActionPoi_2" "noBreak"
  movel(pose_trans(referencePoin_2, pose_trans(p[.232190378902, .230712114941, .270931693358, -2.234349404124, 2.188413039780, .024415260983], ToolActionPoi_2_p)), a=1.2, v=0.25)
  $ 51 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 52 "RG Grip" "noBreak"
on_return = rg_grip(74.4, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 53 "MoveL" "noBreak"
  $ 54 "Exit_3" "noBreak"
  movel(pose_trans(referencePoin_2, pose_trans(p[.232190378902, .230712114941, .270931693358, -2.234349404124, 2.188413039780, .024415260983], Exit_3_p)), a=1.2, v=0.25)
  Pallet_3_sep = False
  if (Pallet_3_cnt >= 3):
    Pallet_3_cnt = 1
  else:
    Pallet_3_cnt = Pallet_3_cnt + 1
  end
  $ 55 "Pallet_4"
  def Pallet_4_trans(pose):
  return p[pose[0], pose[1], pose[2], 0, 0, 0]
  end
  def Pallet_4_rot(pose):
  return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def Pallet_4_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(Pallet_4_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), Pallet_4_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(Pallet_4_rot(T_feature_referencePoint_taught), pose_trans(Pallet_4_rot(T_referencePoint_approach_taught), pose_inv(Pallet_4_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(Pallet_4_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, Pallet_4_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_4_tct = 3
  if (Pallet_4_cnt > 3 or Pallet_4_cnt < 1):
    Pallet_4_cnt = 1
  end
  $ 56 "Patterns" "noBreak"
  $ 57 "Line_Pattern_4" "noBreak"
  $ 60 "Layers" "noBreak"
  if (Pallet_4_cnt < 4):
    Pallet_4_lno = 1
    Pallet_4_lct = Pallet_4_cnt
    global StartItem_4=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.447317094651, -.025086105144, .278753662416, -.000040286005, 3.132850621885, .034153668064]))
    global EndItem_4=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.447311238704, .034553202922, .278752100120, .000209167754, 3.132904314214, .034193663536]))
    referencePoin_3 = interpolate_pose(StartItem_4, EndItem_4, (Pallet_4_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoin_3 = pose_add (referencePoin_3,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_3_p = Pallet_4_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.44730669700166137,-0.020806760417117386,0.28415052390196704,7.591243583120778E-5,3.1329016644813428,0.03411921466967598]), p[-3.969743010129867E-4,0.0010016162906866955,-0.045642069499505555,-5.491687315487864E-5,-5.758846202849451E-5,3.0442775095410158E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_3)
  Approach_3_p = pose_trans(p[0.44730669700166137,-0.020806760417117386,0.28415052390196704,7.591243583109735E-5,3.1329016644814476,0.03411921466967713], pose_trans(pose_inv(referencePoin_3), Approach_3_p))
  ToolActionPoi_3_p = Pallet_4_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.44730669700166137,-0.020806760417117386,0.28415052390196704,7.591243583120778E-5,3.1329016644813428,0.03411921466967598]), p[0.0,0.0,0.0,0.0,0.0,0.0], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_3)
  ToolActionPoi_3_p = pose_trans(p[0.44730669700166137,-0.020806760417117386,0.28415052390196704,7.591243583109735E-5,3.1329016644814476,0.03411921466967713], pose_trans(pose_inv(referencePoin_3), ToolActionPoi_3_p))
  Exit_4_p = Pallet_4_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.44730669700166137,-0.020806760417117386,0.28415052390196704,7.591243583120778E-5,3.1329016644813428,0.03411921466967598]), p[-4.664642417919196E-4,0.0011837127234569974,-0.05392265880024788,2.9480595393634818E-5,-3.236236749207224E-5,-9.41142605553375E-6], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_3)
  Exit_4_p = pose_trans(p[0.44730669700166137,-0.020806760417117386,0.28415052390196704,7.591243583109735E-5,3.1329016644814476,0.03411921466967713], pose_trans(pose_inv(referencePoin_3), Exit_4_p))
  $ 61 "At Each Item" "noBreak"
  $ 62 "Generated Movements" "noBreak"
  $ 63 "MoveJ" "noBreak"
  $ 64 "Approach_3" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_3, pose_trans(p[.449709888964, .014633222442, .280721583182, -.000075912436, -3.132901664481, -.034119214670], Approach_3_p)), qnear=Approach_3_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 65 "MoveL" "noBreak"
  $ 66 "ToolActionPoi_3" "noBreak"
  movel(pose_trans(referencePoin_3, pose_trans(p[.449709888964, .014633222442, .280721583182, -.000075912436, -3.132901664481, -.034119214670], ToolActionPoi_3_p)), a=1.2, v=0.25)
  $ 67 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 68 "RG Grip" "noBreak"
on_return = rg_grip(101.4, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 69 "MoveL" "noBreak"
  $ 70 "Exit_4" "noBreak"
  movel(pose_trans(referencePoin_3, pose_trans(p[.449709888964, .014633222442, .280721583182, -.000075912436, -3.132901664481, -.034119214670], Exit_4_p)), a=1.2, v=0.25)
  Pallet_4_sep = False
  if (Pallet_4_cnt >= 3):
    Pallet_4_cnt = 1
  else:
    Pallet_4_cnt = Pallet_4_cnt + 1
  end
  Loop_2 = Loop_2 + 1
  end
  $ 71 "home" "breakAfter"
  movej(get_inverse_kin(home_p, qnear=home_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 72 "Loop 6 times"
  Loop_3 = 0
  while (Loop_3 < 6):
    $ 73 "Pallet_6"
    def Pallet_6_trans(pose):
    return p[pose[0], pose[1], pose[2], 0, 0, 0]
  end
  def Pallet_6_rot(pose):
  return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def Pallet_6_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(Pallet_6_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), Pallet_6_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(Pallet_6_rot(T_feature_referencePoint_taught), pose_trans(Pallet_6_rot(T_referencePoint_approach_taught), pose_inv(Pallet_6_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(Pallet_6_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, Pallet_6_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_6_tct = 6
  if (Pallet_6_cnt > 6 or Pallet_6_cnt < 1):
    Pallet_6_cnt = 1
  end
  $ 74 "Patterns" "noBreak"
  $ 75 "Line_Pattern_6" "noBreak"
  $ 78 "Line_Pattern_7" "noBreak"
  $ 81 "Layers" "noBreak"
  if (Pallet_6_cnt < 4):
    Pallet_6_lno = 1
    Pallet_6_lct = Pallet_6_cnt
    global StartItem_6=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.451088107289, .029416885797, .277635412047, .042916709394, 3.138531904310, .064476245315]))
    global EndItem_6=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.451128477526, -.022501696116, .279016945826, .042880379318, 3.138461490528, .064492114351]))
    referencePoin_5 = interpolate_pose(StartItem_6, EndItem_6, (Pallet_6_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoin_5 = pose_add (referencePoin_5,p[1.0E-5*direction[0],1.0E-5*direction[1],1.0E-5*direction[2],0,0,0])
  elif (Pallet_6_cnt < 7):
    Pallet_6_lno = 2
    Pallet_6_lct = Pallet_6_cnt - 3
    global StartItem_7=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.412532141254, .011007676174, .262002370786, 2.205248248350, 2.194287675303, .043237836988]))
    global EndItem_7=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.470337380389, .011012614941, .262017706829, 2.205203852446, 2.194268180238, .043290486233]))
    referencePoin_5 = interpolate_pose(StartItem_7, EndItem_7, (Pallet_6_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoin_5 = pose_add (referencePoin_5,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_4_p = Pallet_6_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.45112556212727756,0.029446302098062132,0.2627518661225257,0.042777531300032645,3.138451806196234,0.06448548807706121]), p[-8.98216782014849E-5,0.0028253176275261985,-0.06867654093193476,2.428621315517591E-5,9.095978732035028E-5,-1.1850302042617265E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_5)
  Approach_4_p = pose_trans(p[0.45112556212727756,0.029446302098062132,0.2627518661225257,0.04277753130003624,3.138451806196285,0.06448548807705987], pose_trans(pose_inv(referencePoin_5), Approach_4_p))
  ToolActionPoi_4_p = Pallet_6_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.45112556212727756,0.029446302098062132,0.2627518661225257,0.042777531300032645,3.138451806196234,0.06448548807706121]), p[0.0,0.0,0.0,0.0,0.0,0.0], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_5)
  ToolActionPoi_4_p = pose_trans(p[0.45112556212727756,0.029446302098062132,0.2627518661225257,0.04277753130003624,3.138451806196285,0.06448548807705987], pose_trans(pose_inv(referencePoin_5), ToolActionPoi_4_p))
  Exit_5_p = Pallet_6_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.45112556212727756,0.029446302098062132,0.2627518661225257,0.042777531300032645,3.138451806196234,0.06448548807706121]), p[-1.4694060719677715E-4,0.0038766203687740156,-0.09443490832263257,2.4149663279639477E-5,7.100964147531563E-6,2.1052479988589806E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_5)
  Exit_5_p = pose_trans(p[0.45112556212727756,0.029446302098062132,0.2627518661225257,0.04277753130003624,3.138451806196285,0.06448548807705987], pose_trans(pose_inv(referencePoin_5), Exit_5_p))
  $ 82 "At Each Item" "noBreak"
  $ 83 "Generated Movements" "noBreak"
  $ 84 "MoveJ" "noBreak"
  $ 85 "Approach_4" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_5, pose_trans(p[.450580790434, -.052479309773, .260082244685, -.042777531300, -3.138451806196, -.064485488077], Approach_4_p)), qnear=Approach_4_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 86 "MoveL" "noBreak"
  $ 87 "ToolActionPoi_4" "noBreak"
  movel(pose_trans(referencePoin_5, pose_trans(p[.450580790434, -.052479309773, .260082244685, -.042777531300, -3.138451806196, -.064485488077], ToolActionPoi_4_p)), a=1.2, v=0.25)
  $ 88 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 89 "RG Grip" "noBreak"
on_return = rg_grip(74.80000000000001, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 90 "MoveL" "noBreak"
  $ 91 "Exit_5" "noBreak"
  movel(pose_trans(referencePoin_5, pose_trans(p[.450580790434, -.052479309773, .260082244685, -.042777531300, -3.138451806196, -.064485488077], Exit_5_p)), a=1.2, v=0.25)
  Pallet_6_sep = False
  if (Pallet_6_cnt >= 6):
    Pallet_6_cnt = 1
  else:
    Pallet_6_cnt = Pallet_6_cnt + 1
  end
  $ 92 "Waypoint_1" "breakAfter"
  movej(get_inverse_kin(Waypoint_1_p, qnear=Waypoint_1_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 93 "If analog_in[0]>5"
  if (get_standard_analog_in(0)>5):
    $ 94 "Pallet_5"
    def Pallet_5_trans(pose):
    return p[pose[0], pose[1], pose[2], 0, 0, 0]
  end
  def Pallet_5_rot(pose):
  return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def Pallet_5_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(Pallet_5_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), Pallet_5_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(Pallet_5_rot(T_feature_referencePoint_taught), pose_trans(Pallet_5_rot(T_referencePoint_approach_taught), pose_inv(Pallet_5_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(Pallet_5_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, Pallet_5_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_5_tct = 3
  if (Pallet_5_cnt > 3 or Pallet_5_cnt < 1):
    Pallet_5_cnt = 1
  end
  $ 95 "Patterns" "noBreak"
  $ 96 "Line_Pattern_5" "noBreak"
  $ 99 "Layers" "noBreak"
  if (Pallet_5_cnt < 4):
    Pallet_5_lno = 1
    Pallet_5_lct = Pallet_5_cnt
    global StartItem_5=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.284197625249, .243934188656, .267233221575, 2.177404781675, -2.260348668966, .070271640319]))
    global EndItem_5=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.230082257716, .243914004410, .266797975802, 2.177408817050, -2.260348137094, .070215594011]))
    referencePoin_4 = interpolate_pose(StartItem_5, EndItem_5, (Pallet_5_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoin_4 = pose_add (referencePoin_4,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_6_p = Pallet_5_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.28419762524861225,0.24393418865565097,0.26723322157501056,2.1774047816750643,-2.2603486689659387,0.07027164031920444]), p[0.002689495111569129,-0.002503867738782972,-0.08176648463523523,-2.5782121606062102E-5,1.9833982185826243E-5,1.6103766466476243E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_4)
  Approach_6_p = pose_trans(p[0.28419762524861225,0.24393418865565097,0.26723322157501056,2.1774047816749937,-2.2603486689658716,0.07027164031923824], pose_trans(pose_inv(referencePoin_4), Approach_6_p))
  ToolActionPoi_6_p = Pallet_5_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.28419762524861225,0.24393418865565097,0.26723322157501056,2.1774047816750643,-2.2603486689659387,0.07027164031920444]), p[-5.551115123125783E-17,5.551115123125783E-17,0.0,0.0,0.0,0.0], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_4)
  ToolActionPoi_6_p = pose_trans(p[0.28419762524861225,0.24393418865565097,0.26723322157501056,2.1774047816749937,-2.2603486689658716,0.07027164031923824], pose_trans(pose_inv(referencePoin_4), ToolActionPoi_6_p))
  Exit_7_p = Pallet_5_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.28419762524861225,0.24393418865565097,0.26723322157501056,2.1774047816750643,-2.2603486689659387,0.07027164031920444]), p[0.0023382890761693975,-0.00217980569493309,-0.07170368438447983,-5.4991480168908204E-5,7.000127179079795E-5,-9.736936573915688E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_4)
  Exit_7_p = pose_trans(p[0.28419762524861225,0.24393418865565097,0.26723322157501056,2.1774047816749937,-2.2603486689658716,0.07027164031923824], pose_trans(pose_inv(referencePoin_4), Exit_7_p))
  $ 100 "At Each Item" "noBreak"
  $ 101 "Generated Movements" "noBreak"
  $ 102 "MoveJ" "noBreak"
  $ 103 "Approach_6" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_4, pose_trans(p[.245646326047, .283071389806, .266859970918, -2.177404781675, 2.260348668966, -.070271640319], Approach_6_p)), qnear=Approach_6_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 104 "MoveL" "noBreak"
  $ 105 "ToolActionPoi_6" "noBreak"
  movel(pose_trans(referencePoin_4, pose_trans(p[.245646326047, .283071389806, .266859970918, -2.177404781675, 2.260348668966, -.070271640319], ToolActionPoi_6_p)), a=1.2, v=0.25)
  $ 106 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 107 "RG Grip" "noBreak"
on_return = rg_grip(101.4, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 108 "MoveL" "noBreak"
  $ 109 "Exit_7" "noBreak"
  movel(pose_trans(referencePoin_4, pose_trans(p[.245646326047, .283071389806, .266859970918, -2.177404781675, 2.260348668966, -.070271640319], Exit_7_p)), a=1.2, v=0.25)
  Pallet_5_sep = False
  if (Pallet_5_cnt >= 3):
    Pallet_5_cnt = 1
  else:
    Pallet_5_cnt = Pallet_5_cnt + 1
  end
  else:
    $ 110 "Else" "noBreak"
    $ 111 "Pallet_7"
    def Pallet_7_trans(pose):
    return p[pose[0], pose[1], pose[2], 0, 0, 0]
  end
  def Pallet_7_rot(pose):
  return p[0, 0, 0, pose[3], pose[4], pose[5]]
  end
  def Pallet_7_compute_pallet_waypoint(T_base_feature_taught, T_feature_referencePoint_taught, T_referencePoint_approach_taught, T_base_feature, T_base_referencePoint):
  local trans_referencePoint_approach_in_feature_taught = pose_sub(Pallet_7_trans(pose_trans(T_feature_referencePoint_taught, T_referencePoint_approach_taught)), Pallet_7_trans(T_feature_referencePoint_taught))
  local rot_referencePoint_approach_in_feature_taught = pose_trans(Pallet_7_rot(T_feature_referencePoint_taught), pose_trans(Pallet_7_rot(T_referencePoint_approach_taught), pose_inv(Pallet_7_rot(T_feature_referencePoint_taught))))
  T_feature_referencePoint = pose_trans(pose_inv(T_base_feature), T_base_referencePoint)
  rot_referencePoint_approach = pose_trans(pose_inv(Pallet_7_rot(T_feature_referencePoint)), pose_trans(rot_referencePoint_approach_in_feature_taught, Pallet_7_rot(T_feature_referencePoint)))
  T_feature_approach = pose_trans(trans_referencePoint_approach_in_feature_taught, pose_trans(T_feature_referencePoint, rot_referencePoint_approach))
  T_base_approach = pose_trans(T_base_feature, T_feature_approach)
  return T_base_approach
  end
  Pallet_7_tct = 3
  if (Pallet_7_cnt > 3 or Pallet_7_cnt < 1):
    Pallet_7_cnt = 1
  end
  $ 112 "Patterns" "noBreak"
  $ 113 "Line_Pattern_8" "noBreak"
  $ 116 "Layers" "noBreak"
  if (Pallet_7_cnt < 4):
    Pallet_7_lno = 1
    Pallet_7_lct = Pallet_7_cnt
    global StartItem_8=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.286404685328, -.205785677591, .267224620690, 2.177405596580, -2.260347723500, .070320648223]))
    global EndItem_8=pose_trans(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(p[-.000000000000, -.000000000000, -.000000000000, .000000000000, .000000000000, .000000000000], p[.231883154263, -.205783120492, .265107585063, 2.177387035457, -2.260411948904, .070289806393]))
    referencePoin_6 = interpolate_pose(StartItem_8, EndItem_8, (Pallet_7_lct - 1)/2)
    direction = p[0,0,1,0,0,0]
    referencePoin_6 = pose_add (referencePoin_6,p[0.0*direction[0],0.0*direction[1],0.0*direction[2],0,0,0])
  end
  Approach_5_p = Pallet_7_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.28640468532845853,-0.20578567759056574,0.2672246206895357,2.177405596580339,-2.2603477235000353,0.07032064822261933]), p[0.0024417589702100395,-0.002306673471682452,-0.07473053630266902,-7.3402363399792415E-6,-7.125704019895508E-5,-3.5418066319054034E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_6)
  Approach_5_p = pose_trans(p[0.28640468532845853,-0.20578567759056574,0.2672246206895357,2.177405596580439,-2.260347723500142,0.07032064822259228], pose_trans(pose_inv(referencePoin_6), Approach_5_p))
  ToolActionPoi_5_p = Pallet_7_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.28640468532845853,-0.20578567759056574,0.2672246206895357,2.177405596580339,-2.2603477235000353,0.07032064822261933]), p[0.0,5.551115123125783E-17,-5.551115123125783E-17,0.0,0.0,0.0], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_6)
  ToolActionPoi_5_p = pose_trans(p[0.28640468532845853,-0.20578567759056574,0.2672246206895357,2.177405596580439,-2.260347723500142,0.07032064822259228], pose_trans(pose_inv(referencePoin_6), ToolActionPoi_5_p))
  Exit_6_p = Pallet_7_compute_pallet_waypoint(p[0.0,0.0,0.0,0.0,0.0,0.0], pose_trans(pose_inv(p[0.0,0.0,0.0,0.0,0.0,0.0]), p[0.28640468532845853,-0.20578567759056574,0.2672246206895357,2.177405596580339,-2.2603477235000353,0.07032064822261933]), p[0.0027005290963325324,-0.0025261260454686463,-0.08229201815748827,6.298767554440081E-5,-2.138541213699039E-5,2.007911640844259E-5], p[0.0,0.0,0.0,0.0,0.0,0.0], referencePoin_6)
  Exit_6_p = pose_trans(p[0.28640468532845853,-0.20578567759056574,0.2672246206895357,2.177405596580439,-2.260347723500142,0.07032064822259228], pose_trans(pose_inv(referencePoin_6), Exit_6_p))
  $ 117 "At Each Item" "noBreak"
  $ 118 "Generated Movements" "noBreak"
  $ 119 "MoveJ" "noBreak"
  $ 120 "Approach_5" "noBreak"
  movej(get_inverse_kin(pose_trans(referencePoin_6, pose_trans(p[-.203432267313, .301853259598, .251563727647, -2.177405596580, 2.260347723500, -.070320648223], Approach_5_p)), qnear=Approach_5_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 121 "MoveL" "noBreak"
  $ 122 "ToolActionPoi_5" "noBreak"
  movel(pose_trans(referencePoin_6, pose_trans(p[-.203432267313, .301853259598, .251563727647, -2.177405596580, 2.260347723500, -.070320648223], ToolActionPoi_5_p)), a=1.2, v=0.25)
  $ 123 "Tool action" "noBreak"
  # begin: URCap Program Node
  #   Source: OnRobot, 6.2.0, OnRobot A/S
  #   Type: RG Grip
  $ 124 "RG Grip" "noBreak"
on_return = rg_grip(101.4, 40.0, tool_index = 0, blocking = True, depth_comp = False, popupmsg = True)
rg_payload_set(mass = 0.0, tool_index = 0, use_guard = True)
  # end: URCap Program Node
  $ 125 "MoveL" "noBreak"
  $ 126 "Exit_6" "noBreak"
  movel(pose_trans(referencePoin_6, pose_trans(p[-.203432267313, .301853259598, .251563727647, -2.177405596580, 2.260347723500, -.070320648223], Exit_6_p)), a=1.2, v=0.25)
  Pallet_7_sep = False
  if (Pallet_7_cnt >= 3):
    Pallet_7_cnt = 1
  else:
    Pallet_7_cnt = Pallet_7_cnt + 1
  end
  end
  Loop_3 = Loop_3 + 1
  end
  $ 127 "home" "breakAfter"
  movej(get_inverse_kin(home_p, qnear=home_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 128 "Halt"
  halt
  end
end
