  #======    OnRobot Gripper Proximity Install    ======#
  
  textmsg("Gripper Proxi Install script started...")
  readString=""
  enableGripperProxiInstall=True
  of_gripper_proxi_install_running=False
  of_java_alive_thrd=0
  of_java_control_thrd=0
  thread of_gripper_proxi_install_thread():
  enter_critical
  of_gripper_proxi_install_running=True
  exit_critical
  local proxi_offsets=of_proxi_set_offsets_install()
  local proxi_str=of_RPC.strCon("",proxi_offsets)
  socket_send_line(proxi_str,"javaSocket")
  enter_critical
  of_gripper_proxi_install_running=False
  exit_critical
  end 
  thread OnRobotJavaAliveThread():
  local first_msg=True
  while(True):
  if of_portopened_javaSocket:
  if first_msg:
  local succ=socket_send_line("GRIPPER_PROXI_INSTALL","javaSocket")
  if succ:
  first_msg=False
  end 
  else:
  socket_send_line("RUNNING","javaSocket")
  end 
  end 
  of_wait_ms(100)
  sync()
  end 
  end 
  thread OnRobotJavaControlThread():
  while(True):
  if of_portopened_javaSocket:
  readString=socket_read_line("javaSocket",0)
  if length(readString)!=0:
  if OF_DEBUG_VAR:
  textmsg("ControlSocket readString: ",readString)
  end 
  end 
  if readString=="DISABLE":
  enableGripperProxiInstall=False
  end 
  end 
  sync()
  end 
  end 
  def closeAppEngine():
  if of_gripper_proxi_install_running:
  kill of_gripper_proxi_install_handler
  of_gripper_stop()
  end 
  kill of_java_alive_thrd
  kill of_java_control_thrd
  end 
  sync()
  of_java_alive_thrd=run OnRobotJavaAliveThread()
  sync()
  of_java_control_thrd=run OnRobotJavaControlThread()
  sync()
  of_gripper_proxi_install_handler=run of_gripper_proxi_install_thread()
  sync()
  while(enableGripperProxiInstall and of_gripper_proxi_install_running):
  sync()
  end 
  closeAppEngine()
  sync()
  stopl(1.2)
  of_wait_ms(100)
  textmsg("Gripper Proxi Install script stopped.")
  halt
  
  #======    End of OnRobot Gripper Proximity Install    ======#
